libmd-src/autodiff.libmd.cc File Reference
#include `../libmd.h`
Macros
#define __libmd_src_file__
Functions
bool operator== (dual F, dual G)
bool operator!= (dual F, dual G)
bool operator<= (dual F, dual G)
bool operator>= (dual F, dual G)
bool operator< (dual F, dual G)
bool operator> (dual F, dual G)
template<class X >
bool operator== (dual &F, X a)
template<class X >
bool operator!= (dual &F, X a)
template<class X >
bool operator<= (dual &F, X a)
template<class X >
bool operator>= (dual &F, X a)
template<class X >
bool operator< (dual F, X a)
template<class X >
bool operator> (dual F, X a)
template<class X >
bool operator== (X a, dual &F)
template<class X >
bool operator!= (X a, dual &F)
template<class X >
bool operator<= (X a, dual &F)
template<class X >
bool operator>= (X a, dual &F)
template<class X >
bool operator< (X a, dual F)
template<class X >
bool operator> (X a, dual F)
dual operator- (dual F)
dual operator+ (dual F, dual G)
dual operator- (dual F, dual G)
dual operator* (dual F, dual G)
dual operator/ (dual F, dual G)
dual operator+= (dual &F, dual G)
dual operator-= (dual &F, dual G)
dual operator*= (dual &F, dual G)
dual operator/= (dual &F, dual G)
template<class X >
dual operator+ (dual F, X a)
template<class X >
dual operator- (dual F, X a)
template<class X >
dual operator* (dual F, X a)
template<class X >
dual operator/ (dual F, X a)
template<class X >
dual operator+ (X a, dual F)
template<class X >
dual operator- (X a, dual F)
template<class X >
dual operator* (X a, dual F)
template<class X >
dual operator/ (X a, dual F)
template<class X >
dual operator+= (dual &F, X a)
template<class X >
dual operator-= (dual &F, X a)
template<class X >
dual operator*= (dual &F, X a)
template<class X >
dual operator/= (dual &F, X a)
dual sqrt (dual F)
template<class X >
dual pow (dual F, X n)
dual exp (dual F)
template<class X >
dual pow (X a, dual G)
dual pow (dual F, dual G)
dual log (dual F)
dual sin (dual F)
dual cos (dual F)
dual tan (dual F)
dual sinh (dual F)
dual cosh (dual F)
dual tanh (dual F)
dual asin (dual F)
dual acos (dual F)
dual atan (dual F)
dual asinh (dual F)
dual acosh (dual F)
dual atanh (dual F)
dual abs (dual F)
dual heaviside (dual F)
Macro Definition Documentation
__libmd_src_file__
#define __libmd_src_file__
Definition at line 1 of file autodiff.libmd.cc.
Function Documentation
abs()
dual abs (dual F)
Definition at line 364 of file autodiff.libmd.cc.
{
    return F.x<0.0?-F:F;
}
References dual::x.
acos()
dual acos (dual F)
Definition at line 339 of file autodiff.libmd.cc.
{
    return dual(std::acos(F.x),-F.dx/std::sqrt(1.0-std::pow(F.x,2)));
}
References dual::dx, pow(), sqrt(), and dual::x.
acosh()
dual acosh (dual F)
Definition at line 354 of file autodiff.libmd.cc.
{
    return dual(std::acosh(F.x),-F.dx/std::sqrt(std::pow(F.x,2)-1.0));
}
References dual::dx, pow(), sqrt(), and dual::x.
asin()
dual asin (dual F)
Definition at line 334 of file autodiff.libmd.cc.
{
    return dual(std::asin(F.x),F.dx/std::sqrt(1.0-std::pow(F.x,2)));
}
References dual::dx, pow(), sqrt(), and dual::x.
asinh()
dual asinh (dual F)
Definition at line 349 of file autodiff.libmd.cc.
{
    return dual(std::asinh(F.x),F.dx/std::sqrt(1.0+std::pow(F.x,2)));
}
References dual::dx, pow(), sqrt(), and dual::x.
atan()
dual atan (dual F)
Definition at line 344 of file autodiff.libmd.cc.
{
    return dual(std::atan(F.x),F.dx/(std::pow(F.x,2)+1.0));
}
References dual::dx, pow(), and dual::x.
atanh()
dual atanh (dual F)
Definition at line 359 of file autodiff.libmd.cc.
{
    return dual(std::atanh(F.x),F.dx/(1.0-std::pow(F.x,2)));
}
References dual::dx, pow(), and dual::x.
cos()
dual cos (dual F)
Definition at line 307 of file autodiff.libmd.cc.
{
    return dual(std::cos(F.x),-F.dx*std::sin(F.x));
}
References dual::dx, sin(), and dual::x.
cosh()
dual cosh (dual F)
Definition at line 323 of file autodiff.libmd.cc.
{
    return dual(std::cosh(F.x),F.dx*std::sinh(F.x));
}
References dual::dx, sinh(), and dual::x.
exp()
dual exp (dual F)
Definition at line 279 of file autodiff.libmd.cc.
{
    const ldf ex=std::exp(F.x);
    return dual(ex,F.dx*ex);
}
References dual::dx, and dual::x.
heaviside()
dual heaviside (dual F)
Definition at line 369 of file autodiff.libmd.cc.
{
    return dual(F.x<0.0?0.0:1.0, F.x==0.0?std::numeric_limits<ldf>::infinity():0.0);
}
log()
dual log (dual F)
Definition at line 297 of file autodiff.libmd.cc.
{
    return dual(std::log(F.x),F.dx/F.x);
}
References dual::dx, and dual::x.
operator!=() [1/3]
template<class X >
bool operator!= (dual & F, X a)
Definition at line 89 of file autodiff.libmd.cc.
{
    return F.x!=a;
}
References dual::x.
operator!=() [2/3]
bool operator!= (dual F, dual G)
Definition at line 59 of file autodiff.libmd.cc.
{
    return F.x!=G.x;
}
References dual::x.
operator!=() [3/3]
template<class X >
bool operator!= (X a, dual & F)
Definition at line 119 of file autodiff.libmd.cc.
{
    return a!=F.x;
}
References dual::x.
operator*() [1/3]
dual operator* (dual F, dual G)
Definition at line 162 of file autodiff.libmd.cc.
{
    return dual(F.x*G.x,F.dx*G.x+F.x*G.dx);
}
References dual::dx, and dual::x.
operator*() [2/3]
template<class X >
dual operator* (dual F, X a)
Definition at line 209 of file autodiff.libmd.cc.
{
    return dual(F.x*a,F.dx*a);
}
References dual::dx, and dual::x.
operator*() [3/3]
template<class X >
dual operator* (X a, dual F)
Definition at line 229 of file autodiff.libmd.cc.
{
    return F*a;
}
operator*=() [1/2]
dual operator*= (dual & F, dual G)
Definition at line 186 of file autodiff.libmd.cc.
{
    return F=F*G;
}
operator*=() [2/2]
template<class X >
dual operator*= (dual & F, X a)
Definition at line 251 of file autodiff.libmd.cc.
{
    F.x*=a;
    F.dx*=a;
    return F;
}
References dual::dx, and dual::x.
operator+() [1/3]
dual operator+ (dual F, dual G)
Definition at line 152 of file autodiff.libmd.cc.
{
    return dual(F.x+G.x, F.dx+G.dx);
}
References dual::dx, and dual::x.
operator+() [2/3]
template<class X >
dual operator+ (dual F, X a)
Definition at line 199 of file autodiff.libmd.cc.
{
    return dual(F.x+a,F.dx);
}
References dual::dx, and dual::x.
operator+() [3/3]
template<class X >
dual operator+ (X a, dual F)
Definition at line 219 of file autodiff.libmd.cc.
{
    return F+a;
}
operator+=() [1/2]
dual operator+= (dual & F, dual G)
Definition at line 172 of file autodiff.libmd.cc.
{
    F.x+=G.x;
    F.dx+=G.dx;
    return F;
}
References dual::dx, and dual::x.
operator+=() [2/2]
template<class X >
dual operator+= (dual & F, X a)
Definition at line 239 of file autodiff.libmd.cc.
{
    F.x+=a;
    return F;
}
References dual::x.
operator-() [1/4]
dual operator- (dual F)
Definition at line 147 of file autodiff.libmd.cc.
{
    return dual(-F.x,-F.dx);
}
References dual::dx, and dual::x.
operator-() [2/4]
dual operator- (dual F, dual G)
Definition at line 157 of file autodiff.libmd.cc.
{
    return dual(F.x-G.x, F.dx-G.dx);
}
References dual::dx, and dual::x.
operator-() [3/4]
template<class X >
dual operator- (dual F, X a)
Definition at line 204 of file autodiff.libmd.cc.
{
    return dual(F.x-a,F.dx);
}
References dual::dx, and dual::x.
operator-() [4/4]
template<class X >
dual operator- (X a, dual F)
Definition at line 224 of file autodiff.libmd.cc.
{
    return (-F)+a;
}
operator-=() [1/2]
dual operator-= (dual & F, dual G)
Definition at line 179 of file autodiff.libmd.cc.
{
    F.x-=G.x;
    F.dx-=G.dx;
    return F;
}
References dual::dx, and dual::x.
operator-=() [2/2]
template<class X >
dual operator-= (dual & F, X a)
Definition at line 245 of file autodiff.libmd.cc.
{
    F.x-=a;
    return F;
}
References dual::x.
operator/() [1/3]
dual operator/ (dual F, dual G)
Definition at line 167 of file autodiff.libmd.cc.
{
    return dual(F.x/G.x,(F.dx*G.x-F.x*G.dx)/std::pow(G.x,2));
}
References dual::dx, pow(), and dual::x.
operator/() [2/3]
template<class X >
dual operator/ (dual F, X a)
Definition at line 214 of file autodiff.libmd.cc.
{
    return dual(F.x/a,F.dx/a);
}
References dual::dx, and dual::x.
operator/() [3/3]
template<class X >
dual operator/ (X a, dual F)
Definition at line 234 of file autodiff.libmd.cc.
{
    return dual(a/F.x,-a*F.dx/std::pow(F.x,2));
}
References dual::dx, pow(), and dual::x.
operator/=() [1/2]
dual operator/= (dual & F, dual G)
Definition at line 191 of file autodiff.libmd.cc.
{
    return F=F/G;
}
operator/=() [2/2]
template<class X >
dual operator/= (dual & F, X a)
Definition at line 258 of file autodiff.libmd.cc.
{
    F.x/=a;
    F.dx/=a;
    return F;
}
References dual::dx, and dual::x.
operator<() [1/3]
bool operator< (dual F, dual G)
Definition at line 74 of file autodiff.libmd.cc.
{
    return F.x<G.x;
}
References dual::x.
operator<() [2/3]
template<class X >
bool operator< (dual F, X a)
Definition at line 104 of file autodiff.libmd.cc.
{
    return F.x<a;
}
References dual::x.
operator<() [3/3]
template<class X >
bool operator< (X a, dual F)
Definition at line 134 of file autodiff.libmd.cc.
{
    return a<F.x;
}
References dual::x.
operator<=() [1/3]
template<class X >
bool operator<= (dual & F, X a)
Definition at line 94 of file autodiff.libmd.cc.
{
    return F.x<=a;
}
References dual::x.
operator<=() [2/3]
bool operator<= (dual F, dual G)
Definition at line 64 of file autodiff.libmd.cc.
{
    return F.x<=G.x;
}
References dual::x.
operator<=() [3/3]
template<class X >
bool operator<= (X a, dual & F)
Definition at line 124 of file autodiff.libmd.cc.
{
    return a<=F.x;
}
References dual::x.
operator==() [1/3]
template<class X >
bool operator== (dual & F, X a)
Definition at line 84 of file autodiff.libmd.cc.
{
    return F.x==a;
}
References dual::x.
operator==() [2/3]
bool operator== (dual F, dual G)
Definition at line 54 of file autodiff.libmd.cc.
{
    return F.x==G.x;
}
References dual::x.
operator==() [3/3]
template<class X >
bool operator== (X a, dual & F)
Definition at line 114 of file autodiff.libmd.cc.
{
    return a==F.x;
}
References dual::x.
operator>() [1/3]
bool operator> (dual F, dual G)
Definition at line 79 of file autodiff.libmd.cc.
{
    return F.x>G.x;
}
References dual::x.
operator>() [2/3]
template<class X >
bool operator> (dual F, X a)
Definition at line 109 of file autodiff.libmd.cc.
{
    return F.x>a;
}
References dual::x.
operator>() [3/3]
template<class X >
bool operator> (X a, dual F)
Definition at line 139 of file autodiff.libmd.cc.
{
    return a>F.x;
}
References dual::x.
operator>=() [1/3]
template<class X >
bool operator>= (dual & F, X a)
Definition at line 99 of file autodiff.libmd.cc.
{
    return F.x>=a;
}
References dual::x.
operator>=() [2/3]
bool operator>= (dual F, dual G)
Definition at line 69 of file autodiff.libmd.cc.
{
    return F.x>=G.x;
}
References dual::x.
operator>=() [3/3]
template<class X >
bool operator>= (X a, dual & F)
Definition at line 129 of file autodiff.libmd.cc.
{
    return a>=F.x;
}
References dual::x.
pow() [1/3]
dual pow (dual F, dual G)
Definition at line 291 of file autodiff.libmd.cc.
{
    const ldf po=std::pow(F.x,G.x);
    return dual(po,(G.dx*log(F.x)+F.dx*G.x/F.x)*po);
}
References dual::dx, log(), pow(), and dual::x.
pow() [2/3]
template<class X >
dual pow (dual F, X n)
Definition at line 274 of file autodiff.libmd.cc.
{
    return dual(std::pow(F.x,n),F.dx*n*std::pow(F.x,n-1));
}
References dual::dx, and dual::x.
pow() [3/3]
template<class X >
dual pow (X a, dual G)
Definition at line 285 of file autodiff.libmd.cc.
{
    const ldf po=std::pow(a,G.x);
    return dual(po,G.dx*log(a)*po);
}
References dual::dx, log(), pow(), and dual::x.
sin()
dual sin (dual F)
Definition at line 302 of file autodiff.libmd.cc.
{
    return dual(std::sin(F.x),F.dx*std::cos(F.x));
}
References cos(), dual::dx, and dual::x.
sinh()
dual sinh (dual F)
Definition at line 318 of file autodiff.libmd.cc.
{
    return dual(std::sinh(F.x),F.dx*std::cosh(F.x));
}
References cosh(), dual::dx, and dual::x.
sqrt()
dual sqrt (dual F)
Definition at line 268 of file autodiff.libmd.cc.
{
    const ldf sqr=std::sqrt(F.x);
    return dual(sqr,F.dx/2.0/sqr);
}
References dual::dx, and dual::x.
tan()
dual tan (dual F)
Definition at line 312 of file autodiff.libmd.cc.
{
    const ldf ta=std::tan(F.x);
    return dual(ta,F.dx*(1.0+std::pow(ta,2)));
}
References dual::dx, pow(), and dual::x.
tanh()
dual tanh (dual F)
Definition at line 328 of file autodiff.libmd.cc.
{
    const ldf ta=std::tanh(F.x);
    return dual(ta,F.dx*(1.0-std::pow(ta,2)));
}
References dual::dx, pow(), and dual::x.