libmd-src/box.libmd.cc File Reference
#include `../libmd.h`
Macros
#define __libmd_src_file__
Functions
template<ui dim>
ldf det (ldf Ain[dim][dim], ldf B[dim][dim])
ldf det (ldf Ain[2][2], ldf B[2][2])
ldf det (ldf Ain[3][3], ldf B[3][3])
Variables
const ldf mxinv_eps =sqrt(std::numeric_limits<ldf>::epsilon())
Macro Definition Documentation
__libmd_src_file__
#define __libmd_src_file__
Definition at line 1 of file box.libmd.cc.
Function Documentation
det() [1/3]
ldf det (ldf Ain[2][2], ldf B[2][2])
Return the determinant of the array Ain, and store its inverse in the array B if the determinant is nonzero. Specialized function for dim=2
Definition at line 116 of file box.libmd.cc.
{
    ldf d = Ain[0][0]*Ain[1][1] - Ain[0][1]*Ain[1][0];
    if (std::abs(d) < mxinv_eps)
        return 0;
    B[0][0] = Ain[1][1] / d;
    B[0][1] = -Ain[0][1] / d;
    B[1][0] = -Ain[1][0] / d;
    B[1][1] = Ain[0][0] / d;
    return d;
}
References abs(), and mxinv_eps.
det() [2/3]
ldf det (ldf Ain[3][3], ldf B[3][3])
Return the determinant of the array Ain, and store its inverse in the array B if the determinant is nonzero. Specialized function for dim=3
Definition at line 133 of file box.libmd.cc.
{
    ldf d = Ain[0][0] * (Ain[1][1]*Ain[2][2] - Ain[1][2]*Ain[2][1])
            + Ain[0][1] * (Ain[1][2]*Ain[2][0] - Ain[1][0]*Ain[2][2])
            + Ain[0][2] * (Ain[1][0]*Ain[2][1] - Ain[1][1]*Ain[2][0]);
    if (std::abs(d) < mxinv_eps)
        return 0;
    B[0][0] = (Ain[1][1]*Ain[2][2] - Ain[1][2]*Ain[2][1]) / d;
    B[1][0] = (Ain[1][2]*Ain[2][0] - Ain[1][0]*Ain[2][2]) / d;
    B[2][0] = (Ain[1][0]*Ain[2][1] - Ain[1][1]*Ain[2][0]) / d;
    B[0][1] = (Ain[2][1]*Ain[0][2] - Ain[2][2]*Ain[0][1]) / d;
    B[1][1] = (Ain[2][2]*Ain[0][0] - Ain[2][0]*Ain[0][2]) / d;
    B[2][1] = (Ain[2][0]*Ain[0][1] - Ain[2][1]*Ain[0][0]) / d;
    B[0][2] = (Ain[0][1]*Ain[1][2] - Ain[0][2]*Ain[1][1]) / d;
    B[1][2] = (Ain[0][2]*Ain[1][0] - Ain[0][0]*Ain[1][2]) / d;
    B[2][2] = (Ain[0][0]*Ain[1][1] - Ain[0][1]*Ain[1][0]) / d;
    return d;
}
References abs(), and mxinv_eps.
det() [3/3]
template<ui dim>
ldf det (ldf Ain[dim][dim], ldf B[dim][dim])
Return the determinant of the array Ain, and store its inverse in the array B if the determinant is nonzero.
Definition at line 64 of file box.libmd.cc.
{
    ui i, j, k;
    int sgn = 1;
    ldf d = 1, t1, t2;
    // clone Ain so that it is unchanged
    ldf A[dim][dim];
    std::copy(&Ain[0][0], &Ain[0][0]+dim*dim,&A[0][0]);
    // Initialize B to identity matrix
    memset(B,0,dim*dim*sizeof(ldf));
    for(i=0;i<dim;i++) B[i][i]=1.0;
    for (i = 0; i < dim; i++)
    { // Look for largest pivot
        j = i;
        for (k = i+1; k < dim; k++)
            if (std::abs(A[j][i]) < std::abs(A[k][i]))
                j = k;
        // No nonzero pivot implies singular matrix
        if (std::abs(A[j][i]) < mxinv_eps)
            return 0;
        // Swap rows if necessary
        if (j > i)
        {
            sgn *= -1; // Switch sign of determinant
            std::swap_ranges(A[i]+i, A[i]+dim, A[j]+i);
            std::swap_ranges(B[i], B[i]+dim, B[j]);
        }
        // Reduce other rows
        t1 = A[i][i]/d;
        for (j = 0; j < dim; j++)
            if (j != i)
            {
                t2 = A[j][i]/d;
                for (k = i; k < dim; k++)
                    A[j][k] = t1 * A[j][k] - t2 * A[i][k];
                for (k = 0; k < dim; k++)
                    B[j][k] = t1 * B[j][k] - t2 * B[i][k];
            }
        d *= t1;
    }
    for (i = 0; i < dim; i++)
        for (j = 0; j < dim; j++)
            B[i][j] /= d;
    return sgn * d;
}
References abs(), and mxinv_eps.
Variable Documentation
mxinv_eps
const ldf mxinv_eps =sqrt(std::numeric_limits<ldf>::epsilon())
Definition at line 6 of file box.libmd.cc.