libmd.h File Reference
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <vector>
#include <map>
#include <unordered_map>
#include <list>
#include <stack>
#include <set>
#include <unordered_set>
#include <utility>
#include <limits>
#include <algorithm>
#include <functional>
#include <chrono>
#include <random>
#include `libmd-src/macros.libmd.h`
#include `libmd-src/enums.libmd.h`
#include `libmd.cc`
Classes
struct t_error
This structure handles errors/warnings/debug levels.
struct particle< dim >
This structure contains all the information for a single particle.
struct box< dim >
This structure contains information about the simulation box.
struct bcond< dim >
struct interactiontype
This structure saves the particle type interactions and calculates the the potentials.
struct interactionneighbor
This struct saves the neighboring particle number and the interaction type library number.
struct forcetype
This structure saves the external force functions and calculates them.
struct superparticle
This structure introduces `super_particles` i.e. particles that consist of (sub_)particles.
struct superparticletype
This structure caries a lookup device for a specific super particle type.
struct interact
This structure stores all interactions and their types.
struct dual
This structure automatically differentiates first order.
struct pairpotentials
This structure takes care of pair potentials (who live outside of the class)
struct externalforces< dim >
This structure takes care of additional (external) forces acting on particles.
struct integrators
This structure defines and saves integration metadata.
struct indexer< dim >
This structure is specific for the indexer.
struct indexer< dim >::celldatatype
struct indexer< dim >::kdtreedatatype
struct t_hook< dim >
This structure is the hook launchpad.
struct hooktype
This structure defines what hooks ought to be called with what parameters.
struct hooker< dim >
This structure implements the hooks with the hooktypes.
struct variadic_vars< dim >
This structure stores some cyclic variables for the variadic functions.
struct additional_vars< dim >
This structure stores additional variables.
struct md< dim >
This structure defines the molecular dynamics simulation.
struct duals< dim >
Autodiff for Monge patches.
struct mp< dim >
This structure defines the Monge patch manifold and its properties.
struct mpmd< dim >
This structure takes care of Monge patch molecular dynamics simulations.
Macros
#define F_LDF `%.17lg`
#define F_LDFs `%lg`
#define F_UI `%u`
#define F_UC `%c`
Typedefs
typedef double ldf
typedef unsigned int ui
typedef unsigned char uc
template<ui dim>
using bcondpptr = void(*)(ui d, ui i, void *sys)
Function pointer to particle bcond function is now called perodicitypptr.
template<ui dim>
using bcondxptr = void(*)(ui d, ldf x[dim], void *sys)
Function pointer to position bcond function is now called perodicityxptr.
template<class X >
using potentialptr = X(*)(X, std::vector< ldf > &)
Function pointer to potential functions is now called potentialptr.
template<ui dim>
using extforceptr = void(*)(ui, std::vector< ui > &, std::vector< ldf > &, void *)
Function pointer to external force functions is now called extforceptr.
template<class X , ui dim>
using fmpptr = X(*)(X x[dim], std::vector< ldf > &param)
Monge patch function pointer.
template<ui dim>
using hookptr = void(*)(std::vector< ldf > &, void *)
Function pointer to external force functions is now called extforceptr.
Functions
void __libmd__info ()
Basic libmd comilation info.
ldf TicToc ()
High precision timer.
template<ui dim>
ldf dotprod (ldf A[], ldf B[])
template<ui dim>
void BCOND_NONE (ui d, ui i, void *sys)
template<ui dim>
void BCOND_NONE (ui d, ldf x[dim], void *sys)
template<ui dim>
void BCOND_PERIODIC (ui d, ui i, void *sys)
template<ui dim>
void BCOND_PERIODIC (ui d, ldf x[dim], void *sys)
template<ui dim>
void BCOND_HARD (ui d, ui i, void *sys)
template<ui dim>
void BCOND_HARD (ui d, ldf x[dim], void *sys)
template<ui dim>
void BCOND_BOXSHEAR (ui d, ui i, void *sys)
template<ui dim>
void BCOND_BOXSHEAR (ui d, ldf x[dim], void *sys)
template<class X >
X COULOMB (X r, std::vector< ldf > &parameters)
Coulomb potential functions.
template<class X >
X YUKAWA (X r, std::vector< ldf > &parameters)
Yukawa potential functions.
template<class X >
X HOOKEAN (X r, std::vector< ldf > &parameters)
Hookean potential functions.
template<class X >
X LJ (X r, std::vector< ldf > &parameters)
The famous Lennard-Jones potential functions.
template<class X >
X MORSE (X r, std::vector< ldf > &parameters)
Morse potential functions.
template<class X >
X FORCEDIPOLE (X r, std::vector< ldf > &parameters)
Force dipole potential functions.
template<class X >
X HOOKEANFORCEDIPOLE (X r, std::vector< ldf > &parameters)
Hookean force dipole potential functions.
template<class X >
X ANHARMONICSPRING (X r, std::vector< ldf > &parameters)
Anharmonic spring potential functions.
template<ui dim>
void noise_gen (ldf noise[dim], ui seed=0U)
Fill an array with Gaussian distributed random variables ($\mu=0$, $\sigma=1$)
template<ui dim>
void DAMPING (ui i, std::vector< ui > &particles, std::vector< ldf > &parameters, void *sys)
Damping external force functions.
template<ui dim>
void DISSIPATION (ui i, std::vector< ui > &particles, std::vector< ldf > &parameters, void *sys)
Dissipation external force functions.
template<ui dim>
void LANGEVIN (ui i, std::vector< ui > &particles, std::vector< ldf > &parameters, void *sys)
Thermal noise external force functions.
template<ui dim>
void LANGEVIN_MP (ui i, std::vector< ui > &particles, std::vector< ldf > &parameters, void *sys)
Thermal noise with curvature external force functions.
ldf kdelta (ui i, ui j)
Kronecker delta function.
template<class X , ui dim>
X FLATSPACE (X x[dim], std::vector< ldf > &param)
Flat space Monge function.
template<class X , ui dim>
X GAUSSIANBUMP (X x[dim], std::vector< ldf > &param)
Gaussian bump Monge function.
template<class X , ui dim>
X EGGCARTON (X x[dim], std::vector< ldf > &param)
Egg carton bump Monge function.
template<class X , ui dim>
X MOLLIFIER (X x[dim], std::vector< ldf > &param)
Mollifier bump Monge function.
Variables
const ui UI_MAX =std::numeric_limits<ui>::max()
struct t_error error
Macro Definition Documentation
F_LDF
#define F_LDF `%.17lg`
Definition at line 45 of file libmd.h.
F_LDFs
#define F_LDFs `%lg`
Definition at line 46 of file libmd.h.
F_UC
#define F_UC `%c`
Definition at line 52 of file libmd.h.
F_UI
#define F_UI `%u`
Definition at line 50 of file libmd.h.
Typedef Documentation
bcondpptr
template<ui dim>
using bcondpptr = void (*)(ui d,ui i,void *sys)
Function pointer to particle bcond function is now called perodicitypptr.
Definition at line 96 of file libmd.h.
bcondxptr
template<ui dim>
using bcondxptr = void (*)(ui d,ldf x[dim],void *sys)
Function pointer to position bcond function is now called perodicityxptr.
Definition at line 97 of file libmd.h.
extforceptr
template<ui dim>
using extforceptr = void (*)(ui,std::vector<ui> &,std::vector<ldf> &,void *)
Function pointer to external force functions is now called extforceptr.
Definition at line 99 of file libmd.h.
fmpptr
template<class X , ui dim>
using fmpptr = X (*)(X x[dim],std::vector<ldf> &param)
Monge patch function pointer.
Definition at line 100 of file libmd.h.
hookptr
template<ui dim>
using hookptr = void (*)(std::vector<ldf> &,void *)
Function pointer to external force functions is now called extforceptr.
Definition at line 101 of file libmd.h.
ldf
typedef double ldf
Definition at line 44 of file libmd.h.
potentialptr
template<class X >
using potentialptr = X (*)(X,std::vector<ldf> &)
Function pointer to potential functions is now called potentialptr.
Definition at line 98 of file libmd.h.
uc
typedef unsigned char uc
Definition at line 51 of file libmd.h.
ui
typedef unsigned int ui
Definition at line 49 of file libmd.h.
Function Documentation
__libmd__info()
void __libmd__info ()
Basic libmd comilation info.
This function is designed to give the user an overview of the compilation
Definition at line 12 of file libmd.cc.
{
    #ifdef BRANCH
    printf("libmd branch: " IO_BOLDCYAN "%s" IO_RESET "\n",BRANCH);
    #endif
    #ifdef VER
    printf("libmd branch version: " IO_BOLDCYAN "%s" IO_RESET "\n",VER);
    #endif
    #ifdef CC
    printf("Compiler: " IO_WHITE "%s" IO_RESET "\n",CC);
    #endif
    printf("Compiler version: " IO_WHITE "%s" IO_RESET "\n",__VERSION__);
    printf("Floating point type: ");
    #ifdef LIBMD__LONG_DOUBLE__
    printf(IO_BLUE "long double" IO_RESET "\n");
    #elif defined LIBMD__FLOAT__
    printf(IO_YELLOW "float" IO_RESET "\n");
    #else
    printf(IO_WHITE "double" IO_RESET "\n");
    #endif
    printf("Thread option: %s\n",THREAD_MODEL);
    #ifdef CMSG
    printf("Compilation message: " IO_YELLOW "%s" IO_RESET "\n",CMSG);
    #endif
}
References IO_BLUE, IO_BOLDCYAN, IO_RESET, IO_WHITE, IO_YELLOW, and THREAD_MODEL.
ANHARMONICSPRING()
template<class X >
X ANHARMONICSPRING (X r, std::vector< ldf > & parameters)
Anharmonic spring potential functions.
Anharmoninc spring:
V_{\text{ANHARMONICSPRING}}(r)=\tfrac{k}{\alpha}{\lvert r-r_0 \rvert}^{\alpha}
 This function depends on three parameters:
the 'spring' constant $k$
the 'spring' rest length $r_0$
the exponent $\alpha$
Definition at line 107 of file potentials.libmd.cc.
{
    const ldf k=parameters[0];
    const ldf r0=parameters[1];
    const ldf alpha=parameters[2];
    return (k/alpha)*pow(abs(r-r0),alpha);
}
References abs(), and pow().
BCOND_BOXSHEAR() [1/2]
template<ui dim>
void BCOND_BOXSHEAR (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has sheared boundary conditions.
Checks if point x is outside the boundary perpendicular to dimension d and, if so, updates its position according to the box shear matrices stored in simbox.Lshear and simbox.vshear. The particle position
Definition at line 184 of file boundaryconditions.libmd.cc.
{
    const ldf boundaryCrossing=std::round(x[d]/SYS->simbox.L[d]);
    if((int)boundaryCrossing) for(ui k=0;k<dim;k++) x[k]-=SYS->simbox.Lshear[k][d]*boundaryCrossing;
}
References SYS.
BCOND_BOXSHEAR() [2/2]
template<ui dim>
void BCOND_BOXSHEAR (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has sheared boundary conditions.
Checks if particle i has crossed the boundary perpendicular to dimension d and, if so, updates its position and velocity according to the box shear matrices stored in simbox.Lshear and simbox.vshear. The particle position
Definition at line 164 of file boundaryconditions.libmd.cc.
{
    const ldf boundaryCrossing=std::round(SYS->particles[i].x[d]/SYS->simbox.L[d]);
    if((int)boundaryCrossing) for(ui k=0;k<dim;k++)
    {
        SYS->particles[i].x[k]-=SYS->simbox.Lshear[k][d]*boundaryCrossing;
        SYS->particles[i].xp[k]-=SYS->simbox.Lshear[k][d]*boundaryCrossing;
        SYS->particles[i].dx[k]-=SYS->simbox.vshear[k][d]*boundaryCrossing;
    }
}
References SYS.
BCOND_HARD() [1/2]
template<ui dim>
void BCOND_HARD (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has hard boundary conditions.
Checks if point x is outside the boundary perpendicular to dimension d and, if so, updates its position to respect a hard wall reflection. The particle position is mirrored across the boundary wall.
 This function correctly takes into account skewed boundary conditions, and uses the box matrices simbox.Lshear and simbox.vshear to calculate the reflections if simbox.useLshear is true.
Definition at line 119 of file boundaryconditions.libmd.cc.
{
    if (SYS->simbox.useLshear)
    {
        ldf s=0;
        for (ui k=0;k<dim;k++) s+=SYS->simbox.LshearInv[d][k]*x[k];
        if (std::abs(s) > 0.5) // particle has hit the hard boundary as distorted by the shear
        {
            if (std::abs(s) > 1.) { WARNING("dynamics led to particle displacement bigger than box size; hard boundary reflections undefined"); }
            ldf nhat[dim];
            ldf nlen=0.,xperp=0.,x0perp;
            // the normal vector to the box boundary in dimension d is the dth row of LshearInv
            for (ui k=0;k<dim;k++) nlen += SYS->simbox.LshearInv[d][k]*SYS->simbox.LshearInv[d][k];
            nlen = sqrt(nlen);
            // projection of velocity and position perpendicular to boundary wall
            for (ui k=0;k<dim;k++) {
                nhat[k] = SYS->simbox.LshearInv[d][k]/nlen;
                xperp += nhat[k]*x[k];
            }
            x0perp = nhat[d]*SYS->simbox.Lshear[d][d]*0.5*(s > 0.? 1.:-1.);
            // subtract perpendicular component twice to get reflected velocity
            for (ui k=0;k<dim;k++) x[k] -= 2.0*(xperp-x0perp)*nhat[k]; // reflection about a plane passing through point set by x0perp
        }
    }
    else
    {
        const ldf xnew=SYS->simbox.L[d]*(std::abs(x[d]/SYS->simbox.L[d]+0.5-2.0*floor(x[d]/(2.0*SYS->simbox.L[d])+0.75))-0.5);
        x[d]=xnew;
    }
}
References abs(), sqrt(), SYS, and WARNING.
BCOND_HARD() [2/2]
template<ui dim>
void BCOND_HARD (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has hard boundary conditions.
Checks if particle i has crossed the boundary perpendicular to dimension d and, if so, updates its position and velocity to respect a hard wall reflection. The particle position is mirrored across the boundary wall, whereas its velocity component perpendicular to the boundary wall is reversed.
 This function correctly takes into account skewed boundary conditions, and uses the box matrices simbox.Lshear and simbox.vshear to calculate the reflections if simbox.useLshear is true.
Definition at line 61 of file boundaryconditions.libmd.cc.
{
    if (SYS->simbox.useLshear)
    {
        ldf s=0;
        for (ui k=0;k<dim;k++) s+=SYS->simbox.LshearInv[d][k]*SYS->particles[i].x[k];
        if (std::abs(s) > 0.5) // particle has hit the hard boundary as distorted by the shear
        {
            if (std::abs(s) > 1.) { WARNING("dynamics led to particle displacement bigger than box size; hard boundary reflections undefined"); }
            ldf nhat[dim];
            ldf nlen=0.,vperp=0.,xperp=0.,x0perp;
            // the normal vector to the box boundary in dimension d is the dth row of LshearInv
            for (ui k=0;k<dim;k++) nlen += SYS->simbox.LshearInv[d][k]*SYS->simbox.LshearInv[d][k];
            nlen = sqrt(nlen);
            // projection of velocity and position perpendicular to boundary wall
            for (ui k=0;k<dim;k++) {
                nhat[k] = SYS->simbox.LshearInv[d][k]/nlen;
                vperp += nhat[k]*SYS->particles[i].dx[k];
                xperp += nhat[k]*SYS->particles[i].x[k];
            }
            x0perp = nhat[d]*SYS->simbox.Lshear[d][d]*0.5*(s > 0.? 1.:-1.);
            // subtract perpendicular component twice to get reflected velocity
            for (ui k=0;k<dim;k++)
            {
                SYS->particles[i].dx[k] -= 2.0*vperp*nhat[k];
                SYS->particles[i].x[k] -= 2.0*(xperp-x0perp)*nhat[k]; // reflection about a plane passing through point set by x0perp
                SYS->particles[i].xp[k] += 2.0*(xperp-x0perp)*nhat[k];
            }
        }
    }
    else
    {
        const ldf xnew=SYS->simbox.L[d]*(std::abs(SYS->particles[i].x[d]/SYS->simbox.L[d]+0.5-2.0*floor(SYS->particles[i].x[d]/(2.0*SYS->simbox.L[d])+0.75))-0.5);
        const ldf sign=(((int)std::round(SYS->particles[i].x[d]/SYS->simbox.L[d]))%2?-1.0:1.0);
        SYS->particles[i].xp[d]+=sign*(xnew-SYS->particles[i].x[d]);
        SYS->particles[i].x[d]=xnew;
        SYS->particles[i].dx[d]*=sign;
    }
}
References abs(), sqrt(), SYS, and WARNING.
BCOND_NONE() [1/2]
template<ui dim>
void BCOND_NONE (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has no boundary conditions.
This function does nothing
Definition at line 19 of file boundaryconditions.libmd.cc.
{
    (void) d;
    (void) x;
    (void) sys;
}
BCOND_NONE() [2/2]
template<ui dim>
void BCOND_NONE (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has no boundary conditions.
This function does nothing
Definition at line 6 of file boundaryconditions.libmd.cc.
{
    (void) d;
    (void) i;
    (void) sys;
}
BCOND_PERIODIC() [1/2]
template<ui dim>
void BCOND_PERIODIC (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has periodic boundary conditions.
Checks if point x is outside the boundary perpendicular to dimension d and, if so, shifts its coordinate in that dimension by multiples of simbox.L[d] so that it is within the bounds (-simbox.L[d]/2,simbox.L[d]/2).
Definition at line 47 of file boundaryconditions.libmd.cc.
{
    const ldf dx=SYS->simbox.L[d]*std::round(x[d]/SYS->simbox.L[d]);
    x[d]-=dx;
}
References SYS.
BCOND_PERIODIC() [2/2]
template<ui dim>
void BCOND_PERIODIC (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has periodic boundary conditions.
Checks if particle i has crossed the boundary perpendicular to dimension d and, if so, shifts its coordinate in that dimension by multiples of simbox.L[d] so that it is within the bounds (-simbox.L[d]/2,simbox.L[d]/2).
Definition at line 32 of file boundaryconditions.libmd.cc.
{
    const ldf dx=SYS->simbox.L[d]*std::round(SYS->particles[i].x[d]/SYS->simbox.L[d]);
    SYS->particles[i].xp[d]-=dx;
    SYS->particles[i].x[d]-=dx;
}
References SYS.
COULOMB()
template<class X >
X COULOMB (X r, std::vector< ldf > & parameters)
Coulomb potential functions.
Coulomb potential:
V_{\text{COULOMB}}(r)=\frac{q}{r}
 This function depends on one parameter:
The charge coupling between two partilces: $q$
Definition at line 6 of file potentials.libmd.cc.
{
    const ldf q=parameters[0];
    return q/r;
}
DAMPING()
template<ui dim>
void DAMPING (ui i, std::vector< ui > & particles, std::vector< ldf > & parameters, void * sys)
Damping external force functions.
This external damping force takes the form:
F^{\mu}_{\text{DAMPING}}(\dot{x}^{\mu})=-\gamma \dot{x}^{\mu}
 This function depends on one parameter:
the damping constant $\gamma$
Definition at line 21 of file forces.libmd.cc.
{
    (void) particles;
    ldf gamma=parameters[0];
    for(ui d=0;d<dim;d++) SYS->particles[i].F[d]-=gamma*SYS->particles[i].dx[d];
}
References SYS.
DISSIPATION()
template<ui dim>
void DISSIPATION (ui i, std::vector< ui > & particles, std::vector< ldf > & parameters, void * sys)
Dissipation external force functions.
This external dissipation force takes the form:
F^{\mu}_{\text{DISSIPATION}}(\dot{x}^{\mu})=b \dot{x}_j^{\mu} - \dot{x}_i^{\mu}
 Here the jth particle is given in the particles std::vector
 This function depends on one parameter:
the damping constant $b$
Definition at line 36 of file forces.libmd.cc.
{
    ldf b=parameters[0];
    for(auto it: particles) for(ui d=0;d<dim;d++) SYS->particles[i].F[d]+=b*(SYS->dv(d,i,it));
}
References SYS.
dotprod()
template<ui dim>
ldf dotprod (ldf A[], ldf B[])
Computes the dot product of A[] and B[], assumed to both be of size dim.
Definition at line 58 of file index.libmd.cc.
{
    ldf x = 0;
    for (ui d = 0; d < dim; d++)
        x += A[d]*B[d];
    return x;
}
EGGCARTON()
template<class X , ui dim>
X EGGCARTON (X x[dim], std::vector< ldf > & param)
Egg carton bump Monge function.
FLATSPACE()
template<class X , ui dim>
X FLATSPACE (X x[dim], std::vector< ldf > & param)
Flat space Monge function.
The trivial Monge patch:
f(x^{\rho})_{\text{FLATSPACE}} = 0 
 This function disregards all parameters.
Definition at line 15 of file mongepatches.libmd.cc.
{
    (void) x;
    (void) param;
    return 0.0;
}
FORCEDIPOLE()
template<class X >
X FORCEDIPOLE (X r, std::vector< ldf > & parameters)
Force dipole potential functions.
Definition at line 86 of file potentials.libmd.cc.
{
    // exerts a constant force f = parameters[0]. Positive force => extension of dipole
    const ldf f = parameters[0];
    return -f*r;
}
GAUSSIANBUMP()
template<class X , ui dim>
X GAUSSIANBUMP (X x[dim], std::vector< ldf > & param)
Gaussian bump Monge function.
The Gaussian bump Monge patch:
f(x^{\rho})_{\text{GAUSSIANBUMP}} = A e^{-K x^{\rho}x^{\rho}}
 This function depends on two parameters:
the bump amplitude $A$
the bump width $K$ </li
Definition at line 27 of file mongepatches.libmd.cc.
{
    using std::pow;
    const ldf A=param[0];
    const ldf K=param[1];
    X retval=0.0;
    for(ui d=0;d<dim;d++) retval+=pow(x[d],2);
    return A*exp(-K*retval);
}
References exp(), and pow().
HOOKEAN()
template<class X >
X HOOKEAN (X r, std::vector< ldf > & parameters)
Hookean potential functions.
Hookian potential (Harmonic spring potential):
V_{\text{HOOKEAN}}(r)=\tfrac{1}{2}k{(r-r_0)}^2
 This function depends on two parameters:
the spring constant $k$
the spring's rest length $r_0$
Definition at line 36 of file potentials.libmd.cc.
{
    const ldf k=parameters[0];
    const ldf r0=parameters[1];
    return k/2.0*pow(r-r0,2);
}
References pow().
HOOKEANFORCEDIPOLE()
template<class X >
X HOOKEANFORCEDIPOLE (X r, std::vector< ldf > & parameters)
Hookean force dipole potential functions.
Definition at line 93 of file potentials.libmd.cc.
{
    std::vector<ldf> sprparams(parameters.begin(),parameters.begin()+2);
    std::vector<ldf> fdparams(parameters.begin()+2,parameters.begin()+3);
    if (parameters.size() == 3) return HOOKEAN(r, sprparams) + FORCEDIPOLE(r, fdparams);
    // if threshold exists: force dipole kicks in when force due to spring extension/compression is larger than threshold.
    // positive f => threshold is in extension; negative f => threshold is in compression.
    // threshold must be positive for this interpretation to hold.
    const ldf threshold = parameters[3];
    return HOOKEAN(r, sprparams) + (sprparams[0]*(r-sprparams[1])*fdparams[0]/std::abs(fdparams[0]) > threshold)*FORCEDIPOLE(r, fdparams);
}
References abs(), FORCEDIPOLE(), and HOOKEAN().
kdelta()
ldf kdelta (ui i, ui j)
Kronecker delta function.
Kronecker delta function:
\delta_{ij}=\begin{cases} 1 &\quad i=j\\0&\quad i \neq j\end{cases}
Definition at line 6 of file mongepatches.libmd.cc.
{
    return (i==j)?1.0:0.0;
}
LANGEVIN()
template<ui dim>
void LANGEVIN (ui i, std::vector< ui > & particles, std::vector< ldf > & parameters, void * sys)
Thermal noise external force functions.
This external Langevin force takes the form:
F^{\mu}_{\text{LANGEVIN}}(\dot{x}^{\mu})=\sqrt{\left(2 \gamma k_B T\right)} \hat{\xi}(t)
 This function depends on one parameter:
the temperature $k_B T$
the damping constant $\gamma$
Definition at line 51 of file forces.libmd.cc.
{
    (void) particles;
    const ldf KbT=parameters[0];
    const ldf gamma=parameters[1];
    const ldf factor=sqrt(2.0*gamma*KbT/SYS->integrator.h);
    ldf noise[dim];
    noise_gen<dim>(noise);
    for(ui d=0;d<dim;d++) SYS->particles[i].F[d]+=factor*noise[d];
}
References sqrt(), and SYS.
LANGEVIN_MP()
template<ui dim>
void LANGEVIN_MP (ui i, std::vector< ui > & particles, std::vector< ldf > & parameters, void * sys)
Thermal noise with curvature external force functions.
This external Langevin force takes the form:
F^{\mu}_{\text{LANGEVIN}}(\dot{x}^{\mu})=\sqrt{\left(2 \gamma k_B T\right)} \hat{\xi}(t)
 This function depends on one parameter:
the temperature $k_B T$
the damping constant $\gamma$
Definition at line 72 of file forces.libmd.cc.
{
    (void) particles;
    const ldf KbT=parameters[0];
    const ldf gamma=parameters[1];
    const ldf factor=sqrt(2.0*gamma*KbT/SYS->integrator.h);
    ldf noise[dim],metric_noise[dim]={};
    noise_gen<dim>(noise);
    for(ui mu=0;mu<dim;mu++) for(ui nu=0;nu<dim;nu++) metric_noise[mu]+=MP_SYS->patch.sqrt_ginv(i,mu,nu)*noise[nu];
    for(ui d=0;d<dim;d++) SYS->particles[i].F[d]+=factor*metric_noise[d];
}
References MP_SYS, sqrt(), and SYS.
LJ()
template<class X >
X LJ (X r, std::vector< ldf > & parameters)
The famous Lennard-Jones potential functions.
The famous Lenard-Jones potential:
V_{\text{LJ}}(r)=4 \epsilon \left({\left( \frac{\sigma}{r} \right)}^{12} - {\left( \frac{\sigma}{r} \right)}^6 \right) 
 This function depends on two parameters:
the coupling constant $\epsilon$
the characteristic length scale $\sigma$
Definition at line 52 of file potentials.libmd.cc.
{
    const ldf e=parameters[0];
    const ldf s=parameters[1];
    return 4.0*e*(pow(s/r,12)-pow(s/r,6));
}
References pow().
MOLLIFIER()
template<class X , ui dim>
X MOLLIFIER (X x[dim], std::vector< ldf > & param)
Mollifier bump Monge function.
MORSE()
template<class X >
X MORSE (X r, std::vector< ldf > & parameters)
Morse potential functions.
Morse potential:
V_{\text{MORSE}}(r)=d{\left(1-e^{a(r_e-r)}\right)}^2
 This function depends on three parameters:
the dissociation energy $d$
the width $a$
the equilibrium bond distance $r_e$
Definition at line 68 of file potentials.libmd.cc.
{
    const ldf d=parameters[0];
    const ldf a=parameters[1];
    const ldf re=parameters[2];
    return d*pow(1.0-exp(a*(re-r)),2);
}
References exp(), and pow().
noise_gen()
template<ui dim>
void noise_gen (ldf noise[dim], ui seed = 0U)
Fill an array with Gaussian distributed random variables ($\mu=0$, $\sigma=1$)
This function fills noise[dim] with random Gaussian variables (provided noise[dim] exists). The seed can be set by the second argument seed which has default value 0U (which is neglected) To set the seed call noise_gen<dim>(nullptr,seed) By the default the seed is randomly set by the random device
Definition at line 6 of file forces.libmd.cc.
{
    static std::random_device rd;
    static std::mt19937 mt(rd());
    static std::normal_distribution<ldf> normal(0.0,1.0);
    if(seed) mt.seed(seed);
    if(noise) for(ui d=0;d<dim;d++) noise[d]=normal(mt);
}
TicToc()
ldf TicToc ()
High precision timer.
Definition at line 6 of file error.libmd.cc.
{
    static std::chrono::high_resolution_clock::time_point start,stop;
    start=stop,stop=std::chrono::high_resolution_clock::now();
    return std::chrono::duration<ldf>(stop-start).count();
}
YUKAWA()
template<class X >
X YUKAWA (X r, std::vector< ldf > & parameters)
Yukawa potential functions.
Yukawa potential:
V_{\text{YUKAWA}}(r)=\frac{b}{r e^{kr}}
 This function depends on two parameters:
the coupling strength between two partilces $b$
the Yukawa reciprocal length scale $k$
Definition at line 20 of file potentials.libmd.cc.
{
    const ldf b=parameters[0];
    const ldf k=parameters[1];
    return b/(r*exp(k*r));
}
References exp().
Variable Documentation
error
struct t_error error
UI_MAX
const ui UI_MAX =std::numeric_limits<ui>::max()
Definition at line 56 of file libmd.h.