libmd-src/mongepatches.libmd.cc File Reference
#include `../libmd.h`
Macros
#define __libmd_src_file__
Functions
ldf kdelta (ui i, ui j)
Kronecker delta function.
template<class X , ui dim>
X FLATSPACE (X x[dim], std::vector< ldf > &param)
Flat space Monge function.
template<class X , ui dim>
X GAUSSIANBUMP (X x[dim], std::vector< ldf > &param)
Gaussian bump Monge function.
template<class X , ui dim>
X EGGCARTON (X *x, std::vector< ldf > &param)
template<class X , ui dim>
X MOLLIFIER (X *x, std::vector< ldf > &param)
Macro Definition Documentation
__libmd_src_file__
#define __libmd_src_file__
Definition at line 1 of file mongepatches.libmd.cc.
Function Documentation
EGGCARTON()
template<class X , ui dim>
X EGGCARTON (X * x, std::vector< ldf > & param)
The egg carton Monge patch:
f(x^{\rho})_{\text{EGGCARTON}} = A \prod^{d}_{\rho=1} \cos \left( K^{\rho} x^{\rho} \right) 
 This function depends on $d+1$ parameters:
the amplitude $A$
the $d$-dimensional wave vector $K^{\rho}$
Definition at line 46 of file mongepatches.libmd.cc.
{
    using std::cos;
    X retval=param[0];
    for(ui d=0;d<dim;d++) retval*=cos(x[d]*param[d+1]);
    return retval;
}
References cos().
FLATSPACE()
template<class X , ui dim>
X FLATSPACE (X x[dim], std::vector< ldf > & param)
Flat space Monge function.
The trivial Monge patch:
f(x^{\rho})_{\text{FLATSPACE}} = 0 
 This function disregards all parameters.
Definition at line 15 of file mongepatches.libmd.cc.
{
    (void) x;
    (void) param;
    return 0.0;
}
GAUSSIANBUMP()
template<class X , ui dim>
X GAUSSIANBUMP (X x[dim], std::vector< ldf > & param)
Gaussian bump Monge function.
The Gaussian bump Monge patch:
f(x^{\rho})_{\text{GAUSSIANBUMP}} = A e^{-K x^{\rho}x^{\rho}}
 This function depends on two parameters:
the bump amplitude $A$
the bump width $K$ </li
Definition at line 27 of file mongepatches.libmd.cc.
{
    using std::pow;
    const ldf A=param[0];
    const ldf K=param[1];
    X retval=0.0;
    for(ui d=0;d<dim;d++) retval+=pow(x[d],2);
    return A*exp(-K*retval);
}
References exp(), and pow().
kdelta()
ldf kdelta (ui i, ui j)
Kronecker delta function.
Kronecker delta function:
\delta_{ij}=\begin{cases} 1 &\quad i=j\\0&\quad i \neq j\end{cases}
Definition at line 6 of file mongepatches.libmd.cc.
{
    return (i==j)?1.0:0.0;
}
MOLLIFIER()
template<class X , ui dim>
X MOLLIFIER (X * x, std::vector< ldf > & param)
The the mollifier Monge patch:
f(x^{\rho})_{\text{MOLLIFIER}} = \begin{cases} Ae^{\frac{x^{\rho}x^{\rho}}{x^{\rho}x^{\rho}-K^2}} &\quad \lvert x^{\rho} \rvert < K \\0&\quad \lvert x^{\rho} \rvert \geq K \end{cases} 
 This function depends on two parameters:
the amplitude $A$
the width $K$
Definition at line 63 of file mongepatches.libmd.cc.
{
    const ldf A=param[0];
    const ldf Ksq=std::pow(param[1],2);
    using std::pow;
    using std::exp;
    X retval=0.0;
    for(ui d=0;d<dim;d++) retval+=pow(x[d],2);
    return (retval<Ksq)?A*exp(retval/(retval-Ksq)):static_cast<X>(0.0);
}
References exp(), and pow().