libmd-src/potentials.libmd.cc File Reference
#include `../libmd.h`
Macros
#define __libmd_src_file__
Functions
template<class X >
X COULOMB (X r, std::vector< ldf > &parameters)
Coulomb potential functions.
template<class X >
X YUKAWA (X r, std::vector< ldf > &parameters)
Yukawa potential functions.
template<class X >
X HOOKEAN (X r, std::vector< ldf > &parameters)
Hookean potential functions.
template<class X >
X LJ (X r, std::vector< ldf > &parameters)
The famous Lennard-Jones potential functions.
template<class X >
X MORSE (X r, std::vector< ldf > &parameters)
Morse potential functions.
template<class X >
X FORCEDIPOLE (X r, std::vector< ldf > &parameters)
Force dipole potential functions.
template<class X >
X HOOKEANFORCEDIPOLE (X r, std::vector< ldf > &parameters)
Hookean force dipole potential functions.
template<class X >
X ANHARMONICSPRING (X r, std::vector< ldf > &parameters)
Anharmonic spring potential functions.
Macro Definition Documentation
__libmd_src_file__
#define __libmd_src_file__
Definition at line 1 of file potentials.libmd.cc.
Function Documentation
ANHARMONICSPRING()
template<class X >
X ANHARMONICSPRING (X r, std::vector< ldf > & parameters)
Anharmonic spring potential functions.
Anharmoninc spring:
V_{\text{ANHARMONICSPRING}}(r)=\tfrac{k}{\alpha}{\lvert r-r_0 \rvert}^{\alpha}
 This function depends on three parameters:
the 'spring' constant $k$
the 'spring' rest length $r_0$
the exponent $\alpha$
Definition at line 107 of file potentials.libmd.cc.
{
    const ldf k=parameters[0];
    const ldf r0=parameters[1];
    const ldf alpha=parameters[2];
    return (k/alpha)*pow(abs(r-r0),alpha);
}
References abs(), and pow().
COULOMB()
template<class X >
X COULOMB (X r, std::vector< ldf > & parameters)
Coulomb potential functions.
Coulomb potential:
V_{\text{COULOMB}}(r)=\frac{q}{r}
 This function depends on one parameter:
The charge coupling between two partilces: $q$
Definition at line 6 of file potentials.libmd.cc.
{
    const ldf q=parameters[0];
    return q/r;
}
FORCEDIPOLE()
template<class X >
X FORCEDIPOLE (X r, std::vector< ldf > & parameters)
Force dipole potential functions.
Definition at line 86 of file potentials.libmd.cc.
{
    // exerts a constant force f = parameters[0]. Positive force => extension of dipole
    const ldf f = parameters[0];
    return -f*r;
}
HOOKEAN()
template<class X >
X HOOKEAN (X r, std::vector< ldf > & parameters)
Hookean potential functions.
Hookian potential (Harmonic spring potential):
V_{\text{HOOKEAN}}(r)=\tfrac{1}{2}k{(r-r_0)}^2
 This function depends on two parameters:
the spring constant $k$
the spring's rest length $r_0$
Definition at line 36 of file potentials.libmd.cc.
{
    const ldf k=parameters[0];
    const ldf r0=parameters[1];
    return k/2.0*pow(r-r0,2);
}
References pow().
HOOKEANFORCEDIPOLE()
template<class X >
X HOOKEANFORCEDIPOLE (X r, std::vector< ldf > & parameters)
Hookean force dipole potential functions.
Definition at line 93 of file potentials.libmd.cc.
{
    std::vector<ldf> sprparams(parameters.begin(),parameters.begin()+2);
    std::vector<ldf> fdparams(parameters.begin()+2,parameters.begin()+3);
    if (parameters.size() == 3) return HOOKEAN(r, sprparams) + FORCEDIPOLE(r, fdparams);
    // if threshold exists: force dipole kicks in when force due to spring extension/compression is larger than threshold.
    // positive f => threshold is in extension; negative f => threshold is in compression.
    // threshold must be positive for this interpretation to hold.
    const ldf threshold = parameters[3];
    return HOOKEAN(r, sprparams) + (sprparams[0]*(r-sprparams[1])*fdparams[0]/std::abs(fdparams[0]) > threshold)*FORCEDIPOLE(r, fdparams);
}
References abs(), FORCEDIPOLE(), and HOOKEAN().
LJ()
template<class X >
X LJ (X r, std::vector< ldf > & parameters)
The famous Lennard-Jones potential functions.
The famous Lenard-Jones potential:
V_{\text{LJ}}(r)=4 \epsilon \left({\left( \frac{\sigma}{r} \right)}^{12} - {\left( \frac{\sigma}{r} \right)}^6 \right) 
 This function depends on two parameters:
the coupling constant $\epsilon$
the characteristic length scale $\sigma$
Definition at line 52 of file potentials.libmd.cc.
{
    const ldf e=parameters[0];
    const ldf s=parameters[1];
    return 4.0*e*(pow(s/r,12)-pow(s/r,6));
}
References pow().
MORSE()
template<class X >
X MORSE (X r, std::vector< ldf > & parameters)
Morse potential functions.
Morse potential:
V_{\text{MORSE}}(r)=d{\left(1-e^{a(r_e-r)}\right)}^2
 This function depends on three parameters:
the dissociation energy $d$
the width $a$
the equilibrium bond distance $r_e$
Definition at line 68 of file potentials.libmd.cc.
{
    const ldf d=parameters[0];
    const ldf a=parameters[1];
    const ldf re=parameters[2];
    return d*pow(1.0-exp(a*(re-r)),2);
}
References exp(), and pow().
YUKAWA()
template<class X >
X YUKAWA (X r, std::vector< ldf > & parameters)
Yukawa potential functions.
Yukawa potential:
V_{\text{YUKAWA}}(r)=\frac{b}{r e^{kr}}
 This function depends on two parameters:
the coupling strength between two partilces $b$
the Yukawa reciprocal length scale $k$
Definition at line 20 of file potentials.libmd.cc.
{
    const ldf b=parameters[0];
    const ldf k=parameters[1];
    return b/(r*exp(k*r));
}
References exp().