mp< dim > Struct Template Reference
This structure defines the Monge patch manifold and its properties.
#include <libmd.h>
Public Member Functions
mp ()
Constructor.
void setmp (ui i=MP::FLATSPACE)
Picks one of the builtin Monge patches.
void setmp (fmpptr< ldf, dim > f, fmpptr< duals< dim >, dim > df)
Picks a custom Monge patch.
void calc (ui i, ldf x[dim])
Calculate geometric information.
void calc (duals< dim > &z, ldf x[dim])
Calculate geometric information on the spot.
ldf f (ldf x[dim])
Monge patch.
ldf df (ui mu, ldf x[dim])
Monge patch gradient.
ldf ddf (ui mu, ui nu, ldf x[dim])
Monge patch laplacian.
ldf g (ui i, ui mu, ui nu)
Monge patch metric tensor.
ldf gp (ui i, ui mu, ui nu)
Monge patch metric tensor.
ldf ginv (ui i, ui mu, ui nu)
Monge patch metric tensor inverse.
ldf sqrt_ginv (ui i, ui mu, ui nu)
Square root of Monge patch metric tensor inverse.
ldf A (ui i, ui sigma, ui mu, ui nu)
Monge patch $ A_{\sigma \mu \nu} = \Gamma_{\nu \sigma \mu} $ where $ \Gamma_{\nu \sigma \mu} $ are the Christoffel symbols (of the first kind)
Public Attributes
ui patch
Monge patch type number UI_MAX is custom.
std::vector< ldf > parameters
Monge patch function parameters.
fmpptr< ldf, dim > fmp
Monge patch function.
fmpptr< duals< dim >, dim > dfmp
Derivatives of monge function.
std::vector< duals< dim > > geometryx
Geometric information for particle i in position at position x.
std::vector< duals< dim > > geometryxp
Geometric information for particle i in position at position xp.
Detailed Description
template<ui dim>
struct mp< dim >
This structure defines the Monge patch manifold and its properties.
Definition at line 591 of file libmd.h.
Constructor & Destructor Documentation
mp()
template<ui dim>
mp< dim >::mp
Constructor.
Constructor for the mp<dim> class By default loads a FLATSPACE Monge patch by calling setmp
Definition at line 6 of file mp.libmd.cc.
{
    setmp();
}
Member Function Documentation
A()
template<ui dim>
ldf mp< dim >::A (ui i, ui sigma, ui mu, ui nu)
Monge patch $ A_{\sigma \mu \nu} = \Gamma_{\nu \sigma \mu} $ where $ \Gamma_{\nu \sigma \mu} $ are the Christoffel symbols (of the first kind)
Calculates A symbol of the van Zuiden integrator element sigma mu nu for particle i
Definition at line 143 of file mp.libmd.cc.
{
    return geometryx[i].dx[nu]*geometryx[i].dxdy[sigma][mu];
}
calc() [1/2]
template<ui dim>
void mp< dim >::calc (duals< dim > & z, ldf x[dim])
Calculate geometric information on the spot.
Calculates geometric information for particle i at position x The results are stored in the first argument z
Definition at line 68 of file mp.libmd.cc.
{
    duals<dim> y[dim];
    for(ui d=0;d<dim;d++) y[d]=duals<dim>(x[d],d);
    z=dfmp(y,parameters);
}
calc() [2/2]
template<ui dim>
void mp< dim >::calc (ui i, ldf x[dim])
Calculate geometric information.
Calculates geometric information for particle i at position x The results are stored in the geometryx array
Definition at line 57 of file mp.libmd.cc.
{
    duals<dim> y[dim];
    for(ui d=0;d<dim;d++) y[d]=duals<dim>(x[d],d);
    geometryx[i]=dfmp(y,parameters);
}
ddf()
template<ui dim>
ldf mp< dim >::ddf (ui mu, ui nu, ldf x[dim])
Monge patch laplacian.
Calculates the second derivative in the directions mu nu of the(set) Monge function at position x
Definition at line 97 of file mp.libmd.cc.
{
    duals<dim> y[dim];
    for(ui d=0;d<dim;d++) y[d]=duals<dim>(x[d],d);
    return fmp(y,parameters).dxdy[mu][nu];
}
df()
template<ui dim>
ldf mp< dim >::df (ui mu, ldf x[dim])
Monge patch gradient.
Calculates the derivative in direction mu of the(set) Monge function at position x
Definition at line 87 of file mp.libmd.cc.
{
    duals<dim> y[dim];
    for(ui d=0;d<dim;d++) y[d]=duals<dim>(x[d],d);
    return fmp(y,parameters).dx[mu];
}
f()
template<ui dim>
ldf mp< dim >::f (ldf x[dim])
Monge patch.
Calculates value of the (set) Monge function at position x
Definition at line 79 of file mp.libmd.cc.
{
    return fmp(x,parameters);
}
g()
template<ui dim>
ldf mp< dim >::g (ui i, ui mu, ui nu)
Monge patch metric tensor.
Calculates Monge metric tensor element munu for particle i
Definition at line 107 of file mp.libmd.cc.
{
    return kdelta(mu,nu)+geometryx[i].dx[mu]*geometryx[i].dx[nu];
}
References kdelta().
ginv()
template<ui dim>
ldf mp< dim >::ginv (ui i, ui mu, ui nu)
Monge patch metric tensor inverse.
Calculates Monge metric tensor inverse element munu for particle i
Definition at line 123 of file mp.libmd.cc.
{
    ldf det=1.0;
    for(ui d=0;d<dim;d++) det+=std::pow(geometryx[i].dx[d],2);
    return kdelta(mu,nu)-(geometryx[i].dx[mu]*geometryx[i].dx[nu])/det;
}
References det(), kdelta(), and pow().
gp()
template<ui dim>
ldf mp< dim >::gp (ui i, ui mu, ui nu)
Monge patch metric tensor.
Calculates Monge metric tensor element munu for particle i at it's previous position xp
Definition at line 115 of file mp.libmd.cc.
{
    return kdelta(mu,nu)+geometryxp[i].dx[mu]*geometryxp[i].dx[nu];
}
References kdelta().
setmp() [1/2]
template<ui dim>
void mp< dim >::setmp (fmpptr< ldf, dim > f, fmpptr< duals< dim >, dim > df)
Picks a custom Monge patch.
Sets an externaly defined Monge patch
Definition at line 47 of file mp.libmd.cc.
{
    fmp=f;
    dfmp=df;
    patch=UI_MAX;
}
References UI_MAX.
setmp() [2/2]
template<ui dim>
void mp< dim >::setmp (ui i = MP::FLATSPACE)
Picks one of the builtin Monge patches.
Sets a builtin Monge patch i can be a ui or MP enum type e.g. MP::FLATSPACE (default e.g. MP::FLATSPACE (default).
Definition at line 15 of file mp.libmd.cc.
{
    patch=i;
    switch(i)
    {
        case MP::MOLLIFIER:
            parameters.assign(2,1.0);
            fmp=&MOLLIFIER<ldf,dim>;
            dfmp=&MOLLIFIER<duals<dim>,dim>;
        break;
        case MP::EGGCARTON:
            parameters.assign(dim+1,1.0);
            fmp=&EGGCARTON<ldf,dim>;
            dfmp=&EGGCARTON<duals<dim>,dim>;
        break;
        case MP::GAUSSIANBUMP:
            parameters.assign(2,1.0);
            fmp=&GAUSSIANBUMP<ldf,dim>;
            dfmp=&GAUSSIANBUMP<duals<dim>,dim>;
        break;
        default:
            parameters.assign(1,1.0);
            fmp=&FLATSPACE<ldf,dim>;
            dfmp=&FLATSPACE<duals<dim>,dim>;
        break;
    }
}
References MP::EGGCARTON, MP::GAUSSIANBUMP, and MP::MOLLIFIER.
sqrt_ginv()
template<ui dim>
ldf mp< dim >::sqrt_ginv (ui i, ui mu, ui nu)
Square root of Monge patch metric tensor inverse.
Calculates the square root of Monge metric tensor inverse element munu for particle i
Definition at line 133 of file mp.libmd.cc.
{
    ldf det=1.0;
    for(ui d=0;d<dim;d++) det+=std::pow(geometryx[i].dx[d],2);
    return kdelta(mu,nu)-(geometryx[i].dx[mu]*geometryx[i].dx[nu])/(det+std::sqrt(det));
}
References det(), kdelta(), pow(), and sqrt().
Member Data Documentation
dfmp
template<ui dim>
fmpptr<duals<dim>,dim> mp< dim >::dfmp
Derivatives of monge function.
Definition at line 596 of file libmd.h.
fmp
template<ui dim>
fmpptr<ldf,dim> mp< dim >::fmp
Monge patch function.
Definition at line 595 of file libmd.h.
geometryx
template<ui dim>
std::vector<duals<dim> > mp< dim >::geometryx
Geometric information for particle i in position at position x.
Definition at line 597 of file libmd.h.
geometryxp
template<ui dim>
std::vector<duals<dim> > mp< dim >::geometryxp
Geometric information for particle i in position at position xp.
Definition at line 598 of file libmd.h.
parameters
template<ui dim>
std::vector<ldf> mp< dim >::parameters
Monge patch function parameters.
Definition at line 594 of file libmd.h.
patch
template<ui dim>
ui mp< dim >::patch
Monge patch type number UI_MAX is custom.
Definition at line 593 of file libmd.h.
The documentation for this struct was generated from the following files:
libmd.h
libmd-src/mp.libmd.cc