t_error Struct Reference
This structure handles errors/warnings/debug levels.
#include <libmd.h>
Public Member Functions
t_error ()
Constructor.
~t_error ()
Destructor (to close the files)
void set_error_file (const char *fname)
Sets the error output file.
void set_warning_file (const char *fname)
Sets the warning output file.
void set_debug_1_file (const char *fname)
Sets the debug[1] output file.
void set_debug_2_file (const char *fname)
Sets the debug[2] output file.
void set_debug_3_file (const char *fname)
Sets the debug[3] output file.
void set_debug_timer_file (const char *fname)
Sets the debug[timer] output file.
void print_error (char *buffer)
Prints a error to the error output file (for internal use)
void print_warning (char *buffer)
Prints a warning to the warning output file (for internal use)
void print_debug_1 (char *buffer)
Prints debug[1] message to the debug[1] output file (for internal use)
void print_debug_2 (char *buffer)
Prints debug[2] message to the debug[2] output file (for internal use)
void print_debug_3 (char *buffer)
Prints debug[3] message to the debug[3] output file (for internal use)
void print_debug_timer (char *buffer)
Prints debug[timer] message to the debug[timer] output file (for internal use)
void terminate (ui term)
Terminate if termlevel allows it (for internal use)
Public Attributes
ui term_level
Terminate level for libmd. The default value is 1.
FILE * error_file
libmd error output file (default stderr)
FILE * warning_file
libmd warning output file (default stderr)
FILE * debug_1_file
libmd debug[1] output file (default stdout)
FILE * debug_2_file
libmd debug[2] output file (default stdout)
FILE * debug_3_file
libmd debug[3] output file (default stdout)
FILE * debug_timer_file
libmd debug[timer] output file (default stdout)
Detailed Description
This structure handles errors/warnings/debug levels.
Definition at line 104 of file libmd.h.
Constructor & Destructor Documentation
t_error()
t_error::t_error ()
Constructor.
Definition at line 13 of file error.libmd.cc.
{
    #ifdef FE
    #ifdef FE_ALL_EXCEPT
    feenableexcept(FE_ALL_EXCEPT);
    #elif defined FE_EXCEPT
    feenableexcept(FE_DIVBYZERO|FE_INVALID|FE_OVERFLOW);
    #elif defined FE_LOW_EXCEPT
    feenableexcept(FE_DIVBYZERO);
    #else
    feclearexcept(FE_ALL_EXCEPT);
    #endif
    #endif
    term_level=1;
    error_file=stderr;
    warning_file=stderr;
    debug_1_file=stdout;
    debug_2_file=stdout;
    debug_3_file=stdout;
    debug_timer_file=stdout;
    TicToc();
}
References debug_1_file, debug_2_file, debug_3_file, debug_timer_file, error_file, term_level, TicToc(), and warning_file.
 t_error()
t_error::~t_error ()
Destructor (to close the files)
Definition at line 36 of file error.libmd.cc.
{
    fclose(error_file);
    fclose(warning_file);
    fclose(debug_1_file);
    fclose(debug_2_file);
    fclose(debug_3_file);
    fclose(debug_timer_file);
}
References debug_1_file, debug_2_file, debug_3_file, debug_timer_file, error_file, and warning_file.
Member Function Documentation
print_debug_1()
void t_error::print_debug_1 (char * buffer)
Prints debug[1] message to the debug[1] output file (for internal use)
Definition at line 100 of file error.libmd.cc.
{
    fprintf(debug_1_file,"%s\n",buffer);
    terminate(4);
}
References debug_1_file, and terminate().
print_debug_2()
void t_error::print_debug_2 (char * buffer)
Prints debug[2] message to the debug[2] output file (for internal use)
Definition at line 106 of file error.libmd.cc.
{
    fprintf(debug_2_file,"%s\n",buffer);
    terminate(3);
}
References debug_2_file, and terminate().
print_debug_3()
void t_error::print_debug_3 (char * buffer)
Prints debug[3] message to the debug[3] output file (for internal use)
Definition at line 112 of file error.libmd.cc.
{
    fprintf(debug_3_file,"%s\n",buffer);
    terminate(2);
}
References debug_3_file, and terminate().
print_debug_timer()
void t_error::print_debug_timer (char * buffer)
Prints debug[timer] message to the debug[timer] output file (for internal use)
Definition at line 118 of file error.libmd.cc.
{
    fprintf(debug_timer_file,"%s\n",buffer);
    terminate(5);
}
References debug_timer_file, and terminate().
print_error()
void t_error::print_error (char * buffer)
Prints a error to the error output file (for internal use)
Definition at line 88 of file error.libmd.cc.
{
    fprintf(error_file,"%s\n",buffer);
    terminate(0);
}
References error_file, and terminate().
print_warning()
void t_error::print_warning (char * buffer)
Prints a warning to the warning output file (for internal use)
Definition at line 94 of file error.libmd.cc.
{
    fprintf(warning_file,"%s\n",buffer);
    terminate(1);
}
References terminate(), and warning_file.
set_debug_1_file()
void t_error::set_debug_1_file (const char * fname)
Sets the debug[1] output file.
Definition at line 60 of file error.libmd.cc.
{
    if(!strcmp(fname,"stdout")) debug_1_file=stdout;
    else if(!strcmp(fname,"stderr")) debug_1_file=stderr;
    else debug_1_file=fopen(fname,"w");
}
References debug_1_file.
set_debug_2_file()
void t_error::set_debug_2_file (const char * fname)
Sets the debug[2] output file.
Definition at line 67 of file error.libmd.cc.
{
    if(!strcmp(fname,"stdout")) debug_2_file=stdout;
    else if(!strcmp(fname,"stderr")) debug_2_file=stderr;
    else debug_2_file=fopen(fname,"w");
}
References debug_2_file.
set_debug_3_file()
void t_error::set_debug_3_file (const char * fname)
Sets the debug[3] output file.
Definition at line 74 of file error.libmd.cc.
{
    if(!strcmp(fname,"stdout")) debug_3_file=stdout;
    else if(!strcmp(fname,"stderr")) debug_3_file=stderr;
    else debug_3_file=fopen(fname,"w");
}
References debug_3_file.
set_debug_timer_file()
void t_error::set_debug_timer_file (const char * fname)
Sets the debug[timer] output file.
Definition at line 81 of file error.libmd.cc.
{
    if(!strcmp(fname,"stdout")) debug_timer_file=stdout;
    else if(!strcmp(fname,"stderr")) debug_timer_file=stderr;
    else debug_timer_file=fopen(fname,"w");
}
References debug_timer_file.
set_error_file()
void t_error::set_error_file (const char * fname)
Sets the error output file.
Definition at line 46 of file error.libmd.cc.
{
    if(!strcmp(fname,"stdout")) error_file=stdout;
    else if(!strcmp(fname,"stderr")) error_file=stderr;
    else error_file=fopen(fname,"w");
}
References error_file.
set_warning_file()
void t_error::set_warning_file (const char * fname)
Sets the warning output file.
Definition at line 53 of file error.libmd.cc.
{
    if(!strcmp(fname,"stdout")) warning_file=stdout;
    else if(!strcmp(fname,"stderr")) warning_file=stderr;
    else warning_file=fopen(fname,"w");
}
References warning_file.
terminate()
void t_error::terminate (ui term)
Terminate if termlevel allows it (for internal use)
Definition at line 124 of file error.libmd.cc.
{
    if(term<term_level) exit(EXIT_FAILURE);
}
References term_level.
Member Data Documentation
debug_1_file
FILE* t_error::debug_1_file
libmd debug[1] output file (default stdout)
Definition at line 109 of file libmd.h.
debug_2_file
FILE* t_error::debug_2_file
libmd debug[2] output file (default stdout)
Definition at line 110 of file libmd.h.
debug_3_file
FILE* t_error::debug_3_file
libmd debug[3] output file (default stdout)
Definition at line 111 of file libmd.h.
debug_timer_file
FILE* t_error::debug_timer_file
libmd debug[timer] output file (default stdout)
Definition at line 112 of file libmd.h.
error_file
FILE* t_error::error_file
libmd error output file (default stderr)
Definition at line 107 of file libmd.h.
term_level
ui t_error::term_level
Terminate level for libmd. The default value is 1.
Definition at line 106 of file libmd.h.
warning_file
FILE* t_error::warning_file
libmd warning output file (default stderr)
Definition at line 108 of file libmd.h.
The documentation for this struct was generated from the following files:
libmd.h
libmd-src/error.libmd.cc