.TH "BCOND" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BCOND
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBbcond\fP : uc { \fBNONE\fP, \fBPERIODIC\fP, \fBHARD\fP, \fBBOXSHEAR\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBBCOND::bcond\fP : \fBuc\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIPERIODIC \fP\fP
.TP
\fB\fIHARD \fP\fP
.TP
\fB\fIBOXSHEAR \fP\fP
.PP
Definition at line 7 of file enums\&.libmd\&.h\&.
.PP
.nf
7 {enum bcond:uc {NONE,PERIODIC,HARD,BOXSHEAR};};                    
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
