.TH "hooker< dim >" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hooker< dim > \- This structure implements the hooks with the hooktypes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_hook\fP< dim > \fBhook\fP"
.br
.RI "Hook functions\&. "
.ti -1c
.RI "std::vector< \fBhooktype\fP > \fBhookers\fP"
.br
.RI "Hook type\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<ui dim>
.br
struct hooker< dim >"
This structure implements the hooks with the hooktypes\&. 
.PP
Definition at line 345 of file libmd\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<ui dim> \fBt_hook\fP<dim> \fBhooker\fP< dim >::hook"

.PP
Hook functions\&. 
.PP
Definition at line 347 of file libmd\&.h\&.
.SS "template<ui dim> std::vector<\fBhooktype\fP> \fBhooker\fP< dim >::hookers"

.PP
Hook type\&. 
.PP
Definition at line 348 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
