.TH "md_doc_markdown_superparticles" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_doc_markdown_superparticles \- Superparticles 

.SH "Superparticles"
.PP
A superparticle is a collection of particles that can be referenced and cloned as if it were a single particle\&. 
