.TH "superparticletype" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
superparticletype \- This structure caries a lookup device for a specific super particle type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< std::pair< \fBui\fP, \fBui\fP >, \fBui\fP > \fBsplookup\fP"
.br
.RI "This is the interaction lookup device\&. "
.in -1c
.SH "Detailed Description"
.PP 
This structure caries a lookup device for a specific super particle type\&. 
.PP
Definition at line 220 of file libmd\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::map<std::pair<\fBui\fP,\fBui\fP>,\fBui\fP> superparticletype::splookup"

.PP
This is the interaction lookup device\&. 
.PP
Definition at line 222 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
