.TH "EXTFORCE" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTFORCE \- External force options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBextforce\fP : ui { \fBDAMPING\fP, \fBDISSIPATION\fP, \fBLANGEVIN\fP, \fBLANGEVIN_MP\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
External force options\&. 
.PP
Definition at line 21 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBEXTFORCE::extforce\fP : \fBui\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDAMPING \fP\fP
.TP
\fB\fIDISSIPATION \fP\fP
.TP
\fB\fILANGEVIN \fP\fP
.TP
\fB\fILANGEVIN_MP \fP\fP
.PP
Definition at line 21 of file enums\&.libmd\&.h\&.
.PP
.nf
21                 {enum extforce:ui
22 {
23     DAMPING,
24     DISSIPATION,
25     LANGEVIN,
26     LANGEVIN_MP
27 };};
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
