.TH "libmd-src/index.libmd.cc" 3 "Thu Sep 3 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmd-src/index.libmd.cc
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libmd\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__libmd_src_file__\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<ui dim> \fBldf\fP \fBdotprod\fP (\fBldf\fP A[], \fBldf\fP B[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __libmd_src_file__"

.PP
Definition at line 1 of file index\&.libmd\&.cc\&.
.SH "Function Documentation"
.PP 
.SS "template<ui dim> \fBldf\fP dotprod (\fBldf\fP A[], \fBldf\fP B[])"
Computes the dot product of \fCA[]\fP and \fCB[]\fP, assumed to both be of size \fCdim\fP\&.
.PP
Definition at line 58 of file index\&.libmd\&.cc\&.
.PP
.nf
59 {
63     ldf x = 0;
64     for (ui d = 0; d < dim; d++)
65         x += A[d]*B[d];
66     return x;
67 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
