.TH "INDEX" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INDEX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBindex\fP : uc { \fBCELL\fP, \fBBRUTE_FORCE\fP, \fBKD_TREE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBINDEX::index\fP : \fBuc\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICELL \fP\fP
.TP
\fB\fIBRUTE_FORCE \fP\fP
.TP
\fB\fIKD_TREE \fP\fP
.PP
Definition at line 8 of file enums\&.libmd\&.h\&.
.PP
.nf
8 {enum index:uc {CELL,BRUTE_FORCE,KD_TREE};};                       
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
