.TH "indexer< dim >::kdtreedatatype" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
indexer< dim >::kdtreedatatype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBkdtreedatatype\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~kdtreedatatype\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBui\fP * \fBIdx\fP"
.br
.RI "Indices of particles, ordered by tree-structure\&. "
.ti -1c
.RI "\fBui\fP \fBDivideByDim\fP [30]"
.br
.RI "Dimension to divide by at each recursion level (assuming N <= 2^30) "
.ti -1c
.RI "\fBldf\fP(* \fBPmin\fP )[dim]"
.br
.ti -1c
.RI "\fBldf\fP((* \fBPmax\fP )[dim]"
.br
.RI "Minimum and maximum value of each coordinate, for every subtree\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<ui dim>
.br
struct indexer< dim >::kdtreedatatype"

.PP
Definition at line 312 of file libmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<ui dim> \fBindexer\fP< dim >::kdtreedatatype::kdtreedatatype"

.PP
Constructor\&. Constructor for \fCkdtreedatatype\fP, used by the indexing algorithm \fBmd<dim>::kdtree()\fP\&.
.PP
Definition at line 28 of file index\&.libmd\&.cc\&.
.PP
.nf
29 {
33     Idx = nullptr;
34     Pmin = nullptr;
35     Pmax = nullptr;
36 }
.fi
.SS "template<ui dim> \fBindexer\fP< dim >::kdtreedatatype::~kdtreedatatype"

.PP
Destructor\&. Destructor for \fCkdtreedatatype\fP, used by the indexing algorithm \fBmd<dim>::kdtree()\fP\&.
.PP
Definition at line 38 of file index\&.libmd\&.cc\&.
.PP
.nf
39 {
43     if (Idx)
44     {   delete[] Idx;
45         delete[] Pmin;
46         delete[] Pmax;
47     }
48 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<ui dim> \fBui\fP \fBindexer\fP< dim >::kdtreedatatype::DivideByDim[30]"

.PP
Dimension to divide by at each recursion level (assuming N <= 2^30) 
.PP
Definition at line 315 of file libmd\&.h\&.
.SS "template<ui dim> \fBui\fP* \fBindexer\fP< dim >::kdtreedatatype::Idx"

.PP
Indices of particles, ordered by tree-structure\&. 
.PP
Definition at line 314 of file libmd\&.h\&.
.SS "template<ui dim> \fBldf\fP((* \fBindexer\fP< dim >::kdtreedatatype::Pmax)[dim]"

.PP
Minimum and maximum value of each coordinate, for every subtree\&. 
.PP
Definition at line 316 of file libmd\&.h\&.
.SS "template<ui dim> \fBldf\fP(* \fBindexer\fP< dim >::kdtreedatatype::Pmin)[dim]"

.PP
Definition at line 316 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
