.TH "indexer< dim >::celldatatype" 3 "Thu Sep 3 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
indexer< dim >::celldatatype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcelldatatype\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~celldatatype\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBui\fP \fBQ\fP [dim]"
.br
.RI "Number of cells per dimension\&. "
.ti -1c
.RI "\fBui\fP \fBnCells\fP"
.br
.RI "Total number of cells (= prod(Q)) "
.ti -1c
.RI "\fBui\fP \fBtotNeighbors\fP"
.br
.RI "Total number of (potential) neighboring cells to check (= (3^d-1)/2) "
.ti -1c
.RI "\fBldf\fP \fBCellSize\fP [dim]"
.br
.RI "Length of cell in each dimension\&. "
.ti -1c
.RI "int(* \fBIndexDelta\fP )[dim]"
.br
.RI "Indices of neighboring cells relative to cell\&. "
.ti -1c
.RI "std::vector< \fBui\fP > * \fBCells\fP"
.br
.RI "List of particles per cell\&. "
.ti -1c
.RI "bool * \fBOutsideBox\fP"
.br
.RI "Indicates for each particle whether it is outside the simbox\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<ui dim>
.br
struct indexer< dim >::celldatatype"

.PP
Definition at line 298 of file libmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<ui dim> \fBindexer\fP< dim >::celldatatype::celldatatype"

.PP
Constructor\&. Constructor for \fCcelldatatype\fP, used by the indexing algorithm \fBmd<dim>::cell()\fP\&.
.PP
Definition at line 6 of file index\&.libmd\&.cc\&.
.PP
.nf
7 {
11     IndexDelta = nullptr;
12     Cells=nullptr;
13     OutsideBox=nullptr;
14 }
.fi
.PP
References indexer< dim >::celldatatype::Cells, indexer< dim >::celldatatype::IndexDelta, and indexer< dim >::celldatatype::OutsideBox\&.
.SS "template<ui dim> \fBindexer\fP< dim >::celldatatype::~celldatatype"

.PP
Destructor\&. Destructor for \fCcelldatatype\fP, used by the indexing algorithm \fBmd<dim>::cell()\fP\&.
.PP
Definition at line 16 of file index\&.libmd\&.cc\&.
.PP
.nf
17 {
21     if (IndexDelta)
22     {   delete[] IndexDelta;
23         delete[] Cells;
24         delete[] OutsideBox;
25     }
26 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<ui dim> std::vector<\fBui\fP>* \fBindexer\fP< dim >::celldatatype::Cells"

.PP
List of particles per cell\&. 
.PP
Definition at line 305 of file libmd\&.h\&.
.SS "template<ui dim> \fBldf\fP \fBindexer\fP< dim >::celldatatype::CellSize[dim]"

.PP
Length of cell in each dimension\&. 
.PP
Definition at line 303 of file libmd\&.h\&.
.SS "template<ui dim> int(* \fBindexer\fP< dim >::celldatatype::IndexDelta)[dim]"

.PP
Indices of neighboring cells relative to cell\&. 
.PP
Definition at line 304 of file libmd\&.h\&.
.SS "template<ui dim> \fBui\fP \fBindexer\fP< dim >::celldatatype::nCells"

.PP
Total number of cells (= prod(Q)) 
.PP
Definition at line 301 of file libmd\&.h\&.
.SS "template<ui dim> bool* \fBindexer\fP< dim >::celldatatype::OutsideBox"

.PP
Indicates for each particle whether it is outside the simbox\&. 
.PP
Definition at line 306 of file libmd\&.h\&.
.SS "template<ui dim> \fBui\fP \fBindexer\fP< dim >::celldatatype::Q[dim]"

.PP
Number of cells per dimension\&. 
.PP
Definition at line 300 of file libmd\&.h\&.
.SS "template<ui dim> \fBui\fP \fBindexer\fP< dim >::celldatatype::totNeighbors"

.PP
Total number of (potential) neighboring cells to check (= (3^d-1)/2) 
.PP
Definition at line 302 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
