.TH "interactionneighbor" 3 "Thu Sep 3 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interactionneighbor \- This struct saves the neighboring particle number and the interaction type library number\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinteractionneighbor\fP (\fBui\fP noneighbor, \fBui\fP nointeraction)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBui\fP \fBneighbor\fP"
.br
.RI "Neighbor number\&. "
.ti -1c
.RI "\fBui\fP \fBinteraction\fP"
.br
.RI "Interaction number\&. "
.in -1c
.SH "Detailed Description"
.PP 
This struct saves the neighboring particle number and the interaction type library number\&. 
.PP
Definition at line 191 of file libmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "interactionneighbor::interactionneighbor (\fBui\fP noneighbor, \fBui\fP nointeraction)"

.PP
Constructor\&. Constructor for interactionneighbor\&. Sets \fCneighbor\fP to \fCnoneighbor\fP and \fCinteraction\fP to \fCnointeraction\fP\&.
.PP
Definition at line 18 of file interact\&.libmd\&.cc\&.
.PP
.nf
19 {
24     neighbor=noneighbor;
25     interaction=nointeraction;
26 }
.fi
.PP
References interaction, and neighbor\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBui\fP interactionneighbor::interaction"

.PP
Interaction number\&. 
.PP
Definition at line 194 of file libmd\&.h\&.
.SS "\fBui\fP interactionneighbor::neighbor"

.PP
Neighbor number\&. 
.PP
Definition at line 193 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
