.TH "INTEGRATOR" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INTEGRATOR
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBintegrator\fP : uc { \fBSEULER\fP, \fBVVERLET\fP, \fBFO\fP, \fBFO_OVERDAMPED\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBINTEGRATOR::integrator\fP : \fBuc\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISEULER \fP\fP
.TP
\fB\fIVVERLET \fP\fP
.TP
\fB\fIFO \fP\fP
.TP
\fB\fIFO_OVERDAMPED \fP\fP
.PP
Definition at line 5 of file enums\&.libmd\&.h\&.
.PP
.nf
5 {enum integrator:uc {SEULER,VVERLET,FO,FO_OVERDAMPED};};      
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
