.TH "interact" 3 "Thu Sep 3 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interact \- This structure stores all interactions and their types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinteract\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "std::pair< \fBui\fP, \fBui\fP > \fBhash\fP (\fBui\fP type1, \fBui\fP type2)"
.br
.RI "Hash function\&. "
.ti -1c
.RI "bool \fBprobe\fP (\fBui\fP type1, \fBui\fP type2)"
.br
.RI "Check if a typeinteraction exists between two types\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBupdate\fP"
.br
.RI "Should we update the network\&. "
.ti -1c
.RI "\fBldf\fP \fBrco\fP"
.br
.RI "Default R_cutoff radius\&. "
.ti -1c
.RI "\fBldf\fP \fBssz\fP"
.br
.RI "Skin radius\&. "
.ti -1c
.RI "std::vector< std::vector< \fBui\fP > > \fBforces\fP"
.br
.RI "List of external forces acting on the particles\&. "
.ti -1c
.RI "std::vector< \fBforcetype\fP > \fBforcelibrary\fP"
.br
.RI "Library of external forces\&. "
.ti -1c
.RI "std::vector< std::vector< \fBinteractionneighbor\fP > > \fBskins\fP"
.br
.RI "Particle skin by index (array of vector) "
.ti -1c
.RI "std::vector< \fBinteractiontype\fP > \fBlibrary\fP"
.br
.RI "This is the interaction library\&. "
.ti -1c
.RI "std::unordered_set< \fBui\fP > \fBfree_library_slots\fP"
.br
.RI "Stores free library slots\&. "
.ti -1c
.RI "std::map< std::pair< \fBui\fP, \fBui\fP >, \fBui\fP > \fBlookup\fP"
.br
.RI "This is the interaction lookup device\&. "
.ti -1c
.RI "std::vector< \fBui\fP > \fBspid\fP"
.br
.RI "Super particle identifier array\&. "
.ti -1c
.RI "std::vector< \fBsuperparticle\fP > \fBsuperparticles\fP"
.br
.RI "Actual super particle array\&. "
.ti -1c
.RI "std::vector< \fBsuperparticletype\fP > \fBsptypes\fP"
.br
.RI "Super particle type array\&. "
.in -1c
.SH "Detailed Description"
.PP 
This structure stores all interactions and their types\&. 
.PP
Definition at line 226 of file libmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "interact::interact ()"

.PP
Constructor\&. Constructor for interact\&. Sets \fCupdate\fP to \fCtrue\fP and both \fCrco\fP and \fCssz\fP to 1\&.
.PP
Definition at line 28 of file interact\&.libmd\&.cc\&.
.PP
.nf
29 {
34     update=true;
35     rco=ssz=1\&.0;
36 }
.fi
.PP
References rco, ssz, and update\&.
.SH "Member Function Documentation"
.PP 
.SS "std::pair< \fBui\fP, \fBui\fP > interact::hash (\fBui\fP type1, \fBui\fP type2)"

.PP
Hash function\&. Returns a pair containing \fCtype1\fP and \fCtype2\fP with the largest of the two as the first\&.
.PP
Definition at line 38 of file interact\&.libmd\&.cc\&.
.PP
.nf
39 {
43     return (type2>type1)?std::pair<ui,ui>(type2,type1):std::pair<ui,ui>(type1,type2);
44 }
.fi
.SS "bool interact::probe (\fBui\fP type1, \fBui\fP type2)"

.PP
Check if a typeinteraction exists between two types\&. Returns whether there is an interaction associated with \fCtype1\fP and \fCtype2\fP\&.
.PP
Definition at line 46 of file interact\&.libmd\&.cc\&.
.PP
.nf
47 {
51     return static_cast<bool>(lookup\&.count(hash(type1,type2)));
52 }
.fi
.PP
References hash(), and lookup\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBforcetype\fP> interact::forcelibrary"

.PP
Library of external forces\&. 
.PP
Definition at line 232 of file libmd\&.h\&.
.SS "std::vector<std::vector<\fBui\fP> > interact::forces"

.PP
List of external forces acting on the particles\&. 
.PP
Definition at line 231 of file libmd\&.h\&.
.SS "std::unordered_set<\fBui\fP> interact::free_library_slots"

.PP
Stores free library slots\&. 
.PP
Definition at line 235 of file libmd\&.h\&.
.SS "std::vector<\fBinteractiontype\fP> interact::library"

.PP
This is the interaction library\&. 
.PP
Definition at line 234 of file libmd\&.h\&.
.SS "std::map<std::pair<\fBui\fP,\fBui\fP>,\fBui\fP> interact::lookup"

.PP
This is the interaction lookup device\&. 
.PP
Definition at line 236 of file libmd\&.h\&.
.SS "\fBldf\fP interact::rco"

.PP
Default R_cutoff radius\&. 
.PP
Definition at line 229 of file libmd\&.h\&.
.SS "std::vector<std::vector<\fBinteractionneighbor\fP> > interact::skins"

.PP
Particle skin by index (array of vector) 
.PP
Definition at line 233 of file libmd\&.h\&.
.SS "std::vector<\fBui\fP> interact::spid"

.PP
Super particle identifier array\&. 
.PP
Definition at line 237 of file libmd\&.h\&.
.SS "std::vector<\fBsuperparticletype\fP> interact::sptypes"

.PP
Super particle type array\&. 
.PP
Definition at line 239 of file libmd\&.h\&.
.SS "\fBldf\fP interact::ssz"

.PP
Skin radius\&. 
.PP
Definition at line 230 of file libmd\&.h\&.
.SS "std::vector<\fBsuperparticle\fP> interact::superparticles"

.PP
Actual super particle array\&. 
.PP
Definition at line 238 of file libmd\&.h\&.
.SS "bool interact::update"

.PP
Should we update the network\&. 
.PP
Definition at line 228 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
