.TH "libmd-src/macros.libmd.h" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmd-src/macros.libmd.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__libmd_h_file__\fP"
.br
.ti -1c
.RI "#define \fBmacros_libmd_h\fP"
.br
.ti -1c
.RI "#define \fBSYS\fP   ((\fBmd\fP<dim>*)sys)"
.br
.ti -1c
.RI "#define \fBMP_SYS\fP   ((\fBmpmd\fP<dim>*)sys)"
.br
.ti -1c
.RI "#define \fBIO_RESET\fP   '\\033[0m'"
.br
.ti -1c
.RI "#define \fBIO_BLACK\fP   '\\033[30m'"
.br
.ti -1c
.RI "#define \fBIO_RED\fP   '\\033[31m'"
.br
.ti -1c
.RI "#define \fBIO_GREEN\fP   '\\033[32m'"
.br
.ti -1c
.RI "#define \fBIO_YELLOW\fP   '\\033[33m'"
.br
.ti -1c
.RI "#define \fBIO_BLUE\fP   '\\033[34m'"
.br
.ti -1c
.RI "#define \fBIO_MAGENTA\fP   '\\033[35m'"
.br
.ti -1c
.RI "#define \fBIO_CYAN\fP   '\\033[36m'"
.br
.ti -1c
.RI "#define \fBIO_WHITE\fP   '\\033[37m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDBLACK\fP   '\\033[1m\\033[30m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDRED\fP   '\\033[1m\\033[31m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDGREEN\fP   '\\033[1m\\033[32m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDYELLOW\fP   '\\033[1m\\033[33m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDBLUE\fP   '\\033[1m\\033[34m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDMAGENTA\fP   '\\033[1m\\033[35m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDCYAN\fP   '\\033[1m\\033[36m'"
.br
.ti -1c
.RI "#define \fBIO_BOLDWHITE\fP   '\\033[1m\\033[37m'"
.br
.ti -1c
.RI "#define \fBBUFFERSIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBERROR\fP(str, \&.\&.\&.)   ;"
.br
.ti -1c
.RI "#define \fBWARNING\fP(\&.\&.\&.)   ;"
.br
.ti -1c
.RI "#define \fBDEBUG_1\fP(str, \&.\&.\&.)   ;"
.br
.ti -1c
.RI "#define \fBDEBUG_2\fP(str, \&.\&.\&.)   ;"
.br
.ti -1c
.RI "#define \fBDEBUG_3\fP(str, \&.\&.\&.)   ;"
.br
.ti -1c
.RI "#define \fBDEBUG_TIMER\fP(str, \&.\&.\&.)   ;"
.br
.ti -1c
.RI "#define \fBMSG_ERROR\fP   \fBIO_BOLDRED\fP 'libmd\-error: ' IO_RESET"
.br
.ti -1c
.RI "#define \fBMSG_WARNING\fP   \fBIO_BOLDBLUE\fP 'libmd\-warning: ' IO_RESET"
.br
.ti -1c
.RI "#define \fBMSG_DEBUG_1\fP   \fBIO_BOLDYELLOW\fP 'libmd\-debug[1]: ' IO_RESET"
.br
.ti -1c
.RI "#define \fBMSG_DEBUG_2\fP   \fBIO_BOLDMAGENTA\fP 'libmd\-debug[2]: ' IO_RESET"
.br
.ti -1c
.RI "#define \fBMSG_DEBUG_3\fP   \fBIO_BOLDCYAN\fP 'libmd\-debug[3]: ' IO_RESET"
.br
.ti -1c
.RI "#define \fBMSG_DEBUG_T\fP   \fBIO_BOLDGREEN\fP 'libmd\-timer['"
.br
.ti -1c
.RI "#define \fBTHREAD_MODEL\fP   (\fBIO_BOLDYELLOW\fP 'disabled' IO_RESET)"
.br
.ti -1c
.RI "#define \fBSTRING_ME\fP(x)   #x"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __libmd_h_file__"

.PP
Definition at line 1 of file macros\&.libmd\&.h\&.
.SS "#define BUFFERSIZE   2048"

.PP
Definition at line 47 of file macros\&.libmd\&.h\&.
.SS "#define DEBUG_1(str,  \&.\&.\&.)   ;"

.PP
Definition at line 82 of file macros\&.libmd\&.h\&.
.SS "#define DEBUG_2(str,  \&.\&.\&.)   ;"

.PP
Definition at line 94 of file macros\&.libmd\&.h\&.
.SS "#define DEBUG_3(str,  \&.\&.\&.)   ;"

.PP
Definition at line 106 of file macros\&.libmd\&.h\&.
.SS "#define DEBUG_TIMER(str,  \&.\&.\&.)   ;"

.PP
Definition at line 118 of file macros\&.libmd\&.h\&.
.SS "#define ERROR(str,  \&.\&.\&.)   ;"

.PP
Definition at line 58 of file macros\&.libmd\&.h\&.
.SS "#define IO_BLACK   '\\033[30m'"

.PP
Definition at line 11 of file macros\&.libmd\&.h\&.
.SS "#define IO_BLUE   '\\033[34m'"

.PP
Definition at line 15 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDBLACK   '\\033[1m\\033[30m'"

.PP
Definition at line 19 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDBLUE   '\\033[1m\\033[34m'"

.PP
Definition at line 23 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDCYAN   '\\033[1m\\033[36m'"

.PP
Definition at line 25 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDGREEN   '\\033[1m\\033[32m'"

.PP
Definition at line 21 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDMAGENTA   '\\033[1m\\033[35m'"

.PP
Definition at line 24 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDRED   '\\033[1m\\033[31m'"

.PP
Definition at line 20 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDWHITE   '\\033[1m\\033[37m'"

.PP
Definition at line 26 of file macros\&.libmd\&.h\&.
.SS "#define IO_BOLDYELLOW   '\\033[1m\\033[33m'"

.PP
Definition at line 22 of file macros\&.libmd\&.h\&.
.SS "#define IO_CYAN   '\\033[36m'"

.PP
Definition at line 17 of file macros\&.libmd\&.h\&.
.SS "#define IO_GREEN   '\\033[32m'"

.PP
Definition at line 13 of file macros\&.libmd\&.h\&.
.SS "#define IO_MAGENTA   '\\033[35m'"

.PP
Definition at line 16 of file macros\&.libmd\&.h\&.
.SS "#define IO_RED   '\\033[31m'"

.PP
Definition at line 12 of file macros\&.libmd\&.h\&.
.SS "#define IO_RESET   '\\033[0m'"

.PP
Definition at line 10 of file macros\&.libmd\&.h\&.
.SS "#define IO_WHITE   '\\033[37m'"

.PP
Definition at line 18 of file macros\&.libmd\&.h\&.
.SS "#define IO_YELLOW   '\\033[33m'"

.PP
Definition at line 14 of file macros\&.libmd\&.h\&.
.SS "#define macros_libmd_h"

.PP
Definition at line 4 of file macros\&.libmd\&.h\&.
.SS "#define MP_SYS   ((\fBmpmd\fP<dim>*)sys)"

.PP
Definition at line 7 of file macros\&.libmd\&.h\&.
.SS "#define MSG_DEBUG_1   \fBIO_BOLDYELLOW\fP 'libmd\-debug[1]: ' IO_RESET"

.PP
Definition at line 123 of file macros\&.libmd\&.h\&.
.SS "#define MSG_DEBUG_2   \fBIO_BOLDMAGENTA\fP 'libmd\-debug[2]: ' IO_RESET"

.PP
Definition at line 124 of file macros\&.libmd\&.h\&.
.SS "#define MSG_DEBUG_3   \fBIO_BOLDCYAN\fP 'libmd\-debug[3]: ' IO_RESET"

.PP
Definition at line 125 of file macros\&.libmd\&.h\&.
.SS "#define MSG_DEBUG_T   \fBIO_BOLDGREEN\fP 'libmd\-timer['"

.PP
Definition at line 126 of file macros\&.libmd\&.h\&.
.SS "#define MSG_ERROR   \fBIO_BOLDRED\fP 'libmd\-error: ' IO_RESET"

.PP
Definition at line 121 of file macros\&.libmd\&.h\&.
.SS "#define MSG_WARNING   \fBIO_BOLDBLUE\fP 'libmd\-warning: ' IO_RESET"

.PP
Definition at line 122 of file macros\&.libmd\&.h\&.
.SS "#define STRING_ME(x)   #x"

.PP
Definition at line 130 of file macros\&.libmd\&.h\&.
.SS "#define SYS   ((\fBmd\fP<dim>*)sys)"

.PP
Definition at line 6 of file macros\&.libmd\&.h\&.
.SS "#define THREAD_MODEL   (\fBIO_BOLDYELLOW\fP 'disabled' IO_RESET)"

.PP
Definition at line 128 of file macros\&.libmd\&.h\&.
.SS "#define WARNING( \&.\&.\&.)   ;"

.PP
Definition at line 70 of file macros\&.libmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
