.TH "md-authors" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md-authors \- libmd -- AUTHORS 

.SS "This molecular dynamics library 'libmd' is brought to you by:"
.IP "\(bu" 2
Dr\&. Benjamin C\&. van Zuiden mail2benny+libmd@gmail.com (maintainer)
.IP "\(bu" 2
Dr\&. Jayson Paulose
.IP "\(bu" 2
Dr\&. Thomas H\&. Beuman
.PP
.SS "Under the supervision of:"
.IP "\(bu" 2
Prof\&.Dr\&. Vincenzo Vitelli
.PP
.PP
libmd was originally written at: The Lorentz institute for theoretical physics, Leiden university\&. Niels Bohrweg 2, Leiden, NL-2333 CA, The Netherlands 
