.TH "md_doc_markdown_integrator" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_doc_markdown_integrator \- Integrators 

.SH "Integrators in libmd"
.PP
In libmd there are integrators for flat space (discussed here) and integrators for \fCcurved space\fP\&. All integrators in libmd are symplectic, see \fC1\fP and \fC2\fP\&. Symplectic integrators are integrators that preserve the Lagrangian symmetries\&. Therefore integration methods like explicit Euler or Runge-Kutta are not used\&.
.SS "Flat space integrators"
For flat space molecular dynamics two integrators are provided:
.PP
.IP "\(bu" 2
\fCSymplectic Euler\fP (also called semi-implicit Euler, semi-explicit Euler, Euler–Cromer, and Newton–Størmer–Verlet)
.IP "\(bu" 2
\fCVelocity Verlet\fP
.PP
.PP
These
.SS "Symplectic Euler"
Symplectic Euler is a first order method of the form \begin{align*} \dot{x}^{\mu}_{i+1} &= \dot{x}^{\mu}_{i}+\tfrac{h}{m_i}F^{\mu}_{i} \\ x^{\mu}_{i+1} &= x^{\mu}_{i}+h\dot{x}^{\mu}_{i+1} \end{align*} where $h$ is a timestep\&.
.SS "Velocity Verlet"
Velocity Verlet is a second order method of the form \begin{align} x^{\mu}_{i+1} &= x^{\mu}_{i} + h \dot{x}^{\mu}_{i} + \tfrac{h^2}{2 m} F^{\mu}_{i} \\ \dot{x}^{\mu}_{i+1} &= \dot{x}^{\mu}_{i} + \tfrac{h^2}{2 m} (F^{\mu}_{i}+F^{\mu}_{i+1}) \end{align} where $h$ is a time step\&.
.SS "Integrators structure"
Integrators in libmd can be controlled with the integrate structure in \fC\fBmd<dim>::integrator\fP\fP of type \fC\fBintegrators\fP\fP\&. For flat space two objects are relevant:
.IP "\(bu" 2
\fC\fBintegrators::h\fP\fP the time step
.IP "\(bu" 2
\fC\fBintegrators::method\fP\fP the integration method
.PP
.PP
The time step controls the time evolution\&. As a rule of thumb the time steps shouldn't be to big because the velocities will arbitrarily rise as the potentials give too large energies, as particles end up where they shouldn't be (due to errors)\&. A time step should not be to large as floating point errors will accumulate creating an error and/or barely any evolution takes place\&. Keep in mind that the physics should not be dependent on the choice of time step, it it does, than the time step is probably too small or too large\&. If the time step is not to small and not to large the symplecticity of the integrator will ensure the Lagrangian symmetries are preserved\&. The default time step size is $h=10^{-3}$\&.
.PP
The flat space integration methods supported by libmd are enumerated in \fBINTEGRATOR::integrator\fP\&. The default method is velocity Verlet\&.
.SS "References"
.IP "1." 4
\fCDiscrete mechanics and variational integrators JE Marsden, M West - Acta Numerica 2001, 2001 - Cambridge Univ Press\fP
.IP "2." 4
\fCDiscrete geometric mechanics for variational time integrator nt-refs A Stern, M Desbrun - ACM SIGGRAPH 2006 Courses, 2006\fP 
.PP

