.TH "md_doc_markdown_mongepatch" 3 "Thu Sep 3 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_doc_markdown_mongepatch \- Monge patch 

.SH "Curvature in libmd"
.PP
libmd supports Molecular dynamics on manifolds (curved surfaces) in any dimension\&. Although the \fBintegrator for curved surfaces\fP supports any manifold, a Monge gauge/patch is chosen\&. A Monge patch basically assumes that the curvature is introduced by using a scalar function $f:\mathbb{R}^{d}\rightarrow\mathbb{R}$, for any dimension $d$\&. Such that the metric yields: \begin{align} g_{\mu \nu}= \delta_{\mu \nu} + \partial_{\mu} \partial_{\nu} f \end{align} In libmd $f$ can be controlled by the user\&. Using automatic differentiation libmd calculates all the required differential geometric forms like the metric determinant, the metric inverse, and the Christoffel symbols\&.
.PP
STUB STUB STUB 
