.TH "MP" 3 "Thu Sep 3 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MP \- Monge patch options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBmp\fP : ui { \fBFLATSPACE\fP, \fBGAUSSIANBUMP\fP, \fBEGGCARTON\fP, \fBMOLLIFIER\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Monge patch options\&. 
.PP
Definition at line 29 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMP::mp\fP : \fBui\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFLATSPACE \fP\fP
.TP
\fB\fIGAUSSIANBUMP \fP\fP
.TP
\fB\fIEGGCARTON \fP\fP
.TP
\fB\fIMOLLIFIER \fP\fP
.PP
Definition at line 29 of file enums\&.libmd\&.h\&.
.PP
.nf
29           {enum mp:ui
30 {
31     FLATSPACE,
32     GAUSSIANBUMP,
33     EGGCARTON,
34     MOLLIFIER
35 };};
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
