.TH "MP_INTEGRATOR" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MP_INTEGRATOR
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBmp_integrator\fP : uc { \fBVZ\fP, \fBVZ_P\fP, \fBVZ_WFI\fP, \fBSEULER\fP, \fBVVERLET\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMP_INTEGRATOR::mp_integrator\fP : \fBuc\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVZ \fP\fP
.TP
\fB\fIVZ_P \fP\fP
.TP
\fB\fIVZ_WFI \fP\fP
.TP
\fB\fISEULER \fP\fP
.TP
\fB\fIVVERLET \fP\fP
.PP
Definition at line 6 of file enums\&.libmd\&.h\&.
.PP
.nf
6 {enum mp_integrator:uc {VZ,VZ_P,VZ_WFI,SEULER,VVERLET};};  
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
