.TH "pairpotentials" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pairpotentials \- This structure takes care of pair potentials (who live outside of the class)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmd\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpairpotentials\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBui\fP \fBadd\fP (\fBpotentialptr\fP< \fBdual\fP > p)"
.br
.RI "Add a potentials\&. "
.ti -1c
.RI "\fBldf\fP \fBoperator()\fP (\fBui\fP type, \fBldf\fP r, std::vector< \fBldf\fP > &parameters)"
.br
.RI "Pair potential executer\&. "
.ti -1c
.RI "\fBldf\fP \fBdr\fP (\fBui\fP type, \fBldf\fP r, std::vector< \fBldf\fP > &parameters)"
.br
.RI "Pair potential d/dr executer\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBpotentialptr\fP< \fBdual\fP > > \fBpotentials\fP"
.br
.RI "Pair potential vector\&. "
.in -1c
.SH "Detailed Description"
.PP 
This structure takes care of pair potentials (who live outside of the class) 
.PP
Definition at line 262 of file libmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pairpotentials::pairpotentials ()"

.PP
Constructor\&. pairpotentials constuctor\&. 
.br
 Reserves 16 slot in the potentials vector\&. 
.br
 Adds the builtin pairpotentials\&. 
.br

.PP
Definition at line 6 of file pairpotentials\&.libmd\&.cc\&.
.PP
.nf
7 {
13     potentials\&.reserve(16);
14     add(COULOMB<dual>);
15     add(YUKAWA<dual>);
16     add(HOOKEAN<dual>);
17     add(LJ<dual>);
18     add(MORSE<dual>);
19     add(FORCEDIPOLE<dual>);
20     add(HOOKEANFORCEDIPOLE<dual>);
21     add(ANHARMONICSPRING<dual>);
22 }
.fi
.PP
References add(), and potentials\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBui\fP pairpotentials::add (\fBpotentialptr\fP< \fBdual\fP > p)"

.PP
Add a potentials\&. This function adds a custom potential function \fCp\fP to the potentials vector\&. 
.br

.PP
Definition at line 24 of file pairpotentials\&.libmd\&.cc\&.
.PP
.nf
25 {
29     potentials\&.push_back(p);
30     return potentials\&.size()-1;
31 }
.fi
.PP
References potentials\&.
.SS "\fBldf\fP pairpotentials::dr (\fBui\fP type, \fBldf\fP r, std::vector< \fBldf\fP > & parameters)"

.PP
Pair potential d/dr executer\&. This function evaluates the derivative of a potential function in \fCpairpotentials[type]\fP at \fCr\fP with \fCparameters\fP 
.br
 Make sure that if you use a custom potential function \fCtype\fP and \fCpotentials\fP align\&.
.PP
Definition at line 43 of file pairpotentials\&.libmd\&.cc\&.
.PP
.nf
44 {
49     dual rdx(r,1\&.0);
50     return (potentials[type])(rdx,parameters)\&.dx;
51 }
.fi
.PP
References potentials\&.
.SS "\fBldf\fP pairpotentials::operator() (\fBui\fP type, \fBldf\fP r, std::vector< \fBldf\fP > & parameters)"

.PP
Pair potential executer\&. This function evaluates a potential function in \fCpairpotentials[type]\fP at \fCr\fP with \fCparameters\fP 
.br
 Make sure that if you use a custom potential function \fCtype\fP and \fCpotentials\fP align\&.
.PP
Definition at line 33 of file pairpotentials\&.libmd\&.cc\&.
.PP
.nf
34 {
39     dual rdx(r,1\&.0);
40     return (potentials[type])(rdx,parameters)\&.x;
41 }
.fi
.PP
References potentials\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBpotentialptr\fP<\fBdual\fP> > pairpotentials::potentials"

.PP
Pair potential vector\&. 
.PP
Definition at line 264 of file libmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
