.TH "POT" 3 "Tue Sep 29 2020" "Version -0." "libmd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
POT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums\&.libmd\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBpot\fP : ui { \fBCOULOMB\fP, \fBYUKAWA\fP, \fBHOOKEAN\fP, \fBLJ\fP, \fBMORSE\fP, \fBFORCEDIPOLE\fP, \fBHOOKEANFORCEDIPOLE\fP, \fBANHARMONICSPRING\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file enums\&.libmd\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPOT::pot\fP : \fBui\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOULOMB \fP\fP
.TP
\fB\fIYUKAWA \fP\fP
.TP
\fB\fIHOOKEAN \fP\fP
.TP
\fB\fILJ \fP\fP
.TP
\fB\fIMORSE \fP\fP
.TP
\fB\fIFORCEDIPOLE \fP\fP
.TP
\fB\fIHOOKEANFORCEDIPOLE \fP\fP
.TP
\fB\fIANHARMONICSPRING \fP\fP
.PP
Definition at line 9 of file enums\&.libmd\&.h\&.
.PP
.nf
9            {enum pot:ui                                                         
10 {
11     COULOMB,
12     YUKAWA,
13     HOOKEAN,
14     LJ,
15     MORSE,
16     FORCEDIPOLE,
17     HOOKEANFORCEDIPOLE,
18     ANHARMONICSPRING
19 };};
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libmd from the source code\&.
