libmd-src/autodiff2.libmd.cc File Reference
#include `../libmd.h`
Macros
#define __libmd_src_file__
Functions
template<ui dim>
bool operator== (duals< dim > F, duals< dim > G)
template<ui dim>
bool operator!= (duals< dim > F, duals< dim > G)
template<ui dim>
bool operator<= (duals< dim > F, duals< dim > G)
template<ui dim>
bool operator>= (duals< dim > F, duals< dim > G)
template<ui dim>
bool operator< (duals< dim > F, duals< dim > G)
template<ui dim>
bool operator> (duals< dim > F, duals< dim > G)
template<ui dim, class X >
bool operator== (duals< dim > F, X a)
template<ui dim, class X >
bool operator!= (duals< dim > F, X a)
template<ui dim, class X >
bool operator<= (duals< dim > F, X a)
template<ui dim, class X >
bool operator>= (duals< dim > F, X a)
template<ui dim, class X >
bool operator< (duals< dim > F, X a)
template<ui dim, class X >
bool operator> (duals< dim > F, X a)
template<ui dim, class X >
bool operator== (X a, duals< dim > F)
template<ui dim, class X >
bool operator!= (X a, duals< dim > F)
template<ui dim, class X >
bool operator<= (X a, duals< dim > F)
template<ui dim, class X >
bool operator>= (X a, duals< dim > F)
template<ui dim, class X >
bool operator< (X a, duals< dim > F)
template<ui dim, class X >
bool operator> (X a, duals< dim > F)
template<ui dim>
duals< dim > operator- (duals< dim > F)
template<ui dim>
duals< dim > operator+ (duals< dim > F, duals< dim > G)
template<ui dim>
duals< dim > operator- (duals< dim > F, duals< dim > G)
template<ui dim>
duals< dim > operator* (duals< dim > F, duals< dim > G)
template<ui dim>
duals< dim > operator/ (duals< dim > F, duals< dim > G)
template<ui dim>
duals< dim > operator+= (duals< dim > &F, duals< dim > G)
template<ui dim>
duals< dim > operator-= (duals< dim > &F, duals< dim > G)
template<ui dim>
duals< dim > operator*= (duals< dim > &F, duals< dim > G)
template<ui dim>
duals< dim > operator/= (duals< dim > &F, duals< dim > G)
template<ui dim, class X >
duals< dim > operator+ (duals< dim > F, X a)
template<ui dim, class X >
duals< dim > operator- (duals< dim > F, X a)
template<ui dim, class X >
duals< dim > operator* (duals< dim > F, X a)
template<ui dim, class X >
duals< dim > operator/ (duals< dim > F, X a)
template<ui dim, class X >
duals< dim > operator+ (X a, duals< dim > F)
template<ui dim, class X >
duals< dim > operator- (X a, duals< dim > F)
template<ui dim, class X >
duals< dim > operator* (X a, duals< dim > F)
template<ui dim, class X >
duals< dim > operator/ (X a, duals< dim > F)
template<ui dim, class X >
duals< dim > operator+= (duals< dim > &F, X a)
template<ui dim, class X >
duals< dim > operator-= (duals< dim > &F, X a)
template<ui dim, class X >
duals< dim > operator*= (duals< dim > &F, X a)
template<ui dim, class X >
duals< dim > operator/= (duals< dim > &F, X a)
template<ui dim>
duals< dim > sqrt (duals< dim > F)
template<ui dim, class X >
duals< dim > pow (duals< dim > F, X n)
template<ui dim>
duals< dim > exp (duals< dim > F)
template<ui dim, class X >
duals< dim > pow (X a, duals< dim > F)
template<ui dim>
duals< dim > pow (duals< dim > F, duals< dim > G)
template<ui dim>
duals< dim > log (duals< dim > F)
template<ui dim>
duals< dim > sin (duals< dim > F)
template<ui dim>
duals< dim > cos (duals< dim > F)
template<ui dim>
duals< dim > tan (duals< dim > F)
template<ui dim>
duals< dim > sinh (duals< dim > F)
template<ui dim>
duals< dim > cosh (duals< dim > F)
template<ui dim>
duals< dim > tanh (duals< dim > F)
template<ui dim>
duals< dim > asin (duals< dim > F)
template<ui dim>
duals< dim > acos (duals< dim > F)
template<ui dim>
duals< dim > atan (duals< dim > F)
template<ui dim>
duals< dim > asinh (duals< dim > F)
template<ui dim>
duals< dim > acosh (duals< dim > F)
template<ui dim>
duals< dim > atanh (duals< dim > F)
template<ui dim>
duals< dim > abs (duals< dim > F)
Macro Definition Documentation
__libmd_src_file__
#define __libmd_src_file__
Definition at line 1 of file autodiff2.libmd.cc.
Function Documentation
abs()
template<ui dim>
duals<dim> abs (duals< dim > F)
Definition at line 536 of file autodiff2.libmd.cc.
{
    return F.x<0.0?-F:F;
}
References duals< dim >::x.
acos()
template<ui dim>
duals<dim> acos (duals< dim > F)
Definition at line 476 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::acos(F.x));
    const ldf z1=std::pow(1.0-std::pow(F.x,2),-0.5),z2=std::pow(1.0-std::pow(F.x,2),-1.5);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=-F.dx[i]*z1;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=-F.dxdy[i][j]*z1-F.dx[i]*F.dx[j]*F.x*z2;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
acosh()
template<ui dim>
duals<dim> acosh (duals< dim > F)
Definition at line 512 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::acosh(F.x));
    const ldf z1=std::pow(std::pow(F.x,2)-1.0,-0.5),z2=-std::pow(std::pow(F.x,2)-1.0,-1.5);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*z1;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]*z1+F.dx[i]*F.dx[j]*F.x*z2;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
asin()
template<ui dim>
duals<dim> asin (duals< dim > F)
Definition at line 464 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::asin(F.x));
    const ldf z1=std::pow(1.0-std::pow(F.x,2),-0.5),z2=std::pow(1.0-std::pow(F.x,2),-1.5);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*z1;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]*z1+F.dx[i]*F.dx[j]*F.x*z2;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
asinh()
template<ui dim>
duals<dim> asinh (duals< dim > F)
Definition at line 500 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::asinh(F.x));
    const ldf z1=std::pow(1.0+std::pow(F.x,2),-0.5),z2=-std::pow(1.0+std::pow(F.x,2),-1.5);
    for (ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*z1;
        for (ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]*z1+F.dx[i]*F.dx[j]*F.x*z2;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
atan()
template<ui dim>
duals<dim> atan (duals< dim > F)
Definition at line 488 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::atan(F.x));
    const ldf z=1.0/(1.0+std::pow(F.x,2));
    for (ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*z;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]-F.dx[i]*F.dx[j]*2.0*F.x*z)*z;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
atanh()
template<ui dim>
duals<dim> atanh (duals< dim > F)
Definition at line 524 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::atanh(F.x));
    const ldf z = 1.0/(1.0-std::pow(F.x,2));
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*z;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]+F.dx[i]*F.dx[j]*2.0*F.x*z)*z;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
cos()
template<ui dim>
duals<dim> cos (duals< dim > F)
Definition at line 404 of file autodiff2.libmd.cc.
{
    const ldf cf=std::cos(F.x),sf=std::sin(F.x);
    duals<dim> H(cf);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=-F.dx[i]*sf;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=-F.dxdy[i][j]*sf-F.dx[i]*F.dx[j]*cf;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, sin(), and duals< dim >::x.
cosh()
template<ui dim>
duals<dim> cosh (duals< dim > F)
Definition at line 440 of file autodiff2.libmd.cc.
{
    const ldf cf=std::cosh(F.x),sf=std::sinh(F.x);
    duals<dim> H(cf);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*sf;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]*sf+F.dx[i]*F.dx[j]*cf;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, sinh(), and duals< dim >::x.
exp()
template<ui dim>
duals<dim> exp (duals< dim > F)
Definition at line 344 of file autodiff2.libmd.cc.
{
    const ldf z=std::exp(F.x);
    duals<dim> H(z);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*z;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]+F.dx[i]*F.dx[j])*z;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
log()
template<ui dim>
duals<dim> log (duals< dim > F)
Definition at line 380 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::log(F.x));
    const ldf f2=std::pow(F.x,2);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]/F.x;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]*F.x-F.dx[i]*F.dx[j])/f2;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
operator!=() [1/3]
template<ui dim>
bool operator!= (duals< dim > F, duals< dim > G)
Definition at line 73 of file autodiff2.libmd.cc.
{
    return F.x!=G.x;
}
References duals< dim >::x.
operator!=() [2/3]
template<ui dim, class X >
bool operator!= (duals< dim > F, X a)
Definition at line 103 of file autodiff2.libmd.cc.
{
    return F.x!=a;
}
References duals< dim >::x.
operator!=() [3/3]
template<ui dim, class X >
bool operator!= (X a, duals< dim > F)
Definition at line 133 of file autodiff2.libmd.cc.
{
    return a!=F.x;
}
References duals< dim >::x.
operator*() [1/3]
template<ui dim>
duals<dim> operator* (duals< dim > F, duals< dim > G)
Definition at line 188 of file autodiff2.libmd.cc.
{
    duals<dim> H(F.x*G.x);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*G.x+F.x*G.dx[i];
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.x*G.dxdy[i][j]+F.dx[i]*G.dx[j]+F.dx[j]*G.dx[i]+F.dxdy[i][j]*G.x;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
operator*() [2/3]
template<ui dim, class X >
duals<dim> operator* (duals< dim > F, X a)
Definition at line 246 of file autodiff2.libmd.cc.
{
    F.x*=a;
    for(ui i=0;i<dim;i++)
    {
        F.dx[i]*=a;
        for(ui j=0;j<dim;j++) F.dxdy[i][j]*=a;
    }
    return F;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
operator*() [3/3]
template<ui dim, class X >
duals<dim> operator* (X a, duals< dim > F)
Definition at line 278 of file autodiff2.libmd.cc.
{
    return F*a;
}
operator*=() [1/2]
template<ui dim>
duals<dim> operator*= (duals< dim > & F, duals< dim > G)
Definition at line 221 of file autodiff2.libmd.cc.
{
    return F=F*G;
}
operator*=() [2/2]
template<ui dim, class X >
duals<dim> operator*= (duals< dim > & F, X a)
Definition at line 307 of file autodiff2.libmd.cc.
{
    return F=F*a;
}
operator+() [1/3]
template<ui dim>
duals<dim> operator+ (duals< dim > F, duals< dim > G)
Definition at line 166 of file autodiff2.libmd.cc.
{
    duals<dim> H(F.x+G.x);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]+G.dx[i];
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]+G.dxdy[i][j];
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
operator+() [2/3]
template<ui dim, class X >
duals<dim> operator+ (duals< dim > F, X a)
Definition at line 234 of file autodiff2.libmd.cc.
{
    F.x+=a;
    return F;
}
References duals< dim >::x.
operator+() [3/3]
template<ui dim, class X >
duals<dim> operator+ (X a, duals< dim > F)
Definition at line 268 of file autodiff2.libmd.cc.
{
    return F+a;
}
operator+=() [1/2]
template<ui dim>
duals<dim> operator+= (duals< dim > & F, duals< dim > G)
Definition at line 211 of file autodiff2.libmd.cc.
{
    return F=F+G;
}
operator+=() [2/2]
template<ui dim, class X >
duals<dim> operator+= (duals< dim > & F, X a)
Definition at line 295 of file autodiff2.libmd.cc.
{
    F.x+=a;
    return F;
}
References duals< dim >::x.
operator-() [1/4]
template<ui dim>
duals<dim> operator- (duals< dim > F)
Definition at line 161 of file autodiff2.libmd.cc.
{
    return F*(-1.0);
}
operator-() [2/4]
template<ui dim>
duals<dim> operator- (duals< dim > F, duals< dim > G)
Definition at line 177 of file autodiff2.libmd.cc.
{
    duals<dim> H(F.x-G.x);
    for (ui i=0;i<dim; i++)
    {
        H.dx[i]=F.dx[i]-G.dx[i];
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]-G.dxdy[i][j];
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
operator-() [3/4]
template<ui dim, class X >
duals<dim> operator- (duals< dim > F, X a)
Definition at line 240 of file autodiff2.libmd.cc.
{
    F.x-=a;
    return F;
}
References duals< dim >::x.
operator-() [4/4]
template<ui dim, class X >
duals<dim> operator- (X a, duals< dim > F)
Definition at line 273 of file autodiff2.libmd.cc.
{
    return (-F)+a;
}
operator-=() [1/2]
template<ui dim>
duals<dim> operator-= (duals< dim > & F, duals< dim > G)
Definition at line 216 of file autodiff2.libmd.cc.
{
    return F=F-G;
}
operator-=() [2/2]
template<ui dim, class X >
duals<dim> operator-= (duals< dim > & F, X a)
Definition at line 301 of file autodiff2.libmd.cc.
{
    F.x-=a;
    return F;
}
References duals< dim >::x.
operator/() [1/3]
template<ui dim>
duals<dim> operator/ (duals< dim > F, duals< dim > G)
Definition at line 199 of file autodiff2.libmd.cc.
{
    duals<dim>H(F.x/G.x);
    const ldf g2=std::pow(G.x,2),g3=std::pow(G.x,3);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=(F.dx[i]*G.x-F.x*G.dx[i])/g2;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(2.0*F.x*G.dx[i]*G.dx[j]-G.x*(F.x*G.dxdy[i][j]+F.dx[i]*G.dx[j]+F.dx[j]*G.dx[i]-G.x*F.dxdy[i][j]))/g3;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
operator/() [2/3]
template<ui dim, class X >
duals<dim> operator/ (duals< dim > F, X a)
Definition at line 257 of file autodiff2.libmd.cc.
{
    F.x/=a;
    for(ui i=0;i<dim;i++)
    {
        F.dx[i]/=a;
        for(ui j=0;j<dim;j++) F.dxdy[i][j]/=a;
    }
    return F;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
operator/() [3/3]
template<ui dim, class X >
duals<dim> operator/ (X a, duals< dim > F)
Definition at line 283 of file autodiff2.libmd.cc.
{
    duals<dim> H(a/F.x);
    const ldf f2=std::pow(F.x,2),f3=std::pow(F.x,3);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=-a*F.dx[i]/f2;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=a*(2.0*F.dx[i]*F.dx[j]-F.x*F.dxdy[i][j])/f3;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, pow(), and duals< dim >::x.
operator/=() [1/2]
template<ui dim>
duals<dim> operator/= (duals< dim > & F, duals< dim > G)
Definition at line 226 of file autodiff2.libmd.cc.
{
    return F=F/G;
}
operator/=() [2/2]
template<ui dim, class X >
duals<dim> operator/= (duals< dim > & F, X a)
Definition at line 312 of file autodiff2.libmd.cc.
{
    return F=F/a;
}
operator<() [1/3]
template<ui dim>
bool operator< (duals< dim > F, duals< dim > G)
Definition at line 88 of file autodiff2.libmd.cc.
{
    return F.x<G.x;
}
References duals< dim >::x.
operator<() [2/3]
template<ui dim, class X >
bool operator< (duals< dim > F, X a)
Definition at line 118 of file autodiff2.libmd.cc.
{
    return F.x<a;
}
References duals< dim >::x.
operator<() [3/3]
template<ui dim, class X >
bool operator< (X a, duals< dim > F)
Definition at line 148 of file autodiff2.libmd.cc.
{
    return a<F.x;
}
References duals< dim >::x.
operator<=() [1/3]
template<ui dim>
bool operator<= (duals< dim > F, duals< dim > G)
Definition at line 78 of file autodiff2.libmd.cc.
{
    return F.x<=G.x;
}
References duals< dim >::x.
operator<=() [2/3]
template<ui dim, class X >
bool operator<= (duals< dim > F, X a)
Definition at line 108 of file autodiff2.libmd.cc.
{
    return F.x<=a;
}
References duals< dim >::x.
operator<=() [3/3]
template<ui dim, class X >
bool operator<= (X a, duals< dim > F)
Definition at line 138 of file autodiff2.libmd.cc.
{
    return a<=F.x;
}
References duals< dim >::x.
operator==() [1/3]
template<ui dim>
bool operator== (duals< dim > F, duals< dim > G)
Definition at line 68 of file autodiff2.libmd.cc.
{
    return F.x==G.x;
}
References duals< dim >::x.
operator==() [2/3]
template<ui dim, class X >
bool operator== (duals< dim > F, X a)
Definition at line 98 of file autodiff2.libmd.cc.
{
    return F.x==a;
}
References duals< dim >::x.
operator==() [3/3]
template<ui dim, class X >
bool operator== (X a, duals< dim > F)
Definition at line 128 of file autodiff2.libmd.cc.
{
    return a==F.x;
}
References duals< dim >::x.
operator>() [1/3]
template<ui dim>
bool operator> (duals< dim > F, duals< dim > G)
Definition at line 93 of file autodiff2.libmd.cc.
{
    return F.x>G.x;
}
References duals< dim >::x.
operator>() [2/3]
template<ui dim, class X >
bool operator> (duals< dim > F, X a)
Definition at line 123 of file autodiff2.libmd.cc.
{
    return F.x>a;
}
References duals< dim >::x.
operator>() [3/3]
template<ui dim, class X >
bool operator> (X a, duals< dim > F)
Definition at line 153 of file autodiff2.libmd.cc.
{
    return a>F.x;
}
References duals< dim >::x.
operator>=() [1/3]
template<ui dim>
bool operator>= (duals< dim > F, duals< dim > G)
Definition at line 83 of file autodiff2.libmd.cc.
{
    return F.x>=G.x;
}
References duals< dim >::x.
operator>=() [2/3]
template<ui dim, class X >
bool operator>= (duals< dim > F, X a)
Definition at line 113 of file autodiff2.libmd.cc.
{
    return F.x>=a;
}
References duals< dim >::x.
operator>=() [3/3]
template<ui dim, class X >
bool operator>= (X a, duals< dim > F)
Definition at line 143 of file autodiff2.libmd.cc.
{
    return a>=F.x;
}
References duals< dim >::x.
pow() [1/3]
template<ui dim>
duals<dim> pow (duals< dim > F, duals< dim > G)
Definition at line 368 of file autodiff2.libmd.cc.
{
    const ldf z=std::pow(F.x,G.x),lf=std::log(F.x);
    duals<dim> H(z);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=(G.dx[i]*lf+F.dx[i]*G.x/F.x)*z;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=((G.dx[i]*lf+F.dx[i]*G.x/F.x)*(G.dx[j]*lf+F.dx[j]*G.x/F.x)+G.dxdy[i][j]*lf+(F.dx[i]*G.dx[j]+F.dx[j]*G.dx[i]+F.dxdy[i][j]*G.x-F.dx[i]*F.dx[j]*G.x/F.x)/F.x)*z;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, log(), pow(), and duals< dim >::x.
pow() [2/3]
template<ui dim, class X >
duals<dim> pow (duals< dim > F, X n)
Definition at line 332 of file autodiff2.libmd.cc.
{
    duals<dim> H(std::pow(F.x,n));
    const ldf z1=std::pow(F.x,n-1),z2=std::pow(F.x,n-2);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*n*z1;
        for (ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=n*(F.dxdy[i][j]*F.x+(n-1)*F.dx[i]*F.dx[j])*z2;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
pow() [3/3]
template<ui dim, class X >
duals<dim> pow (X a, duals< dim > F)
Definition at line 356 of file autodiff2.libmd.cc.
{
    const ldf z=std::pow(a,F.x),la=std::log(a);
    duals<dim> H(z);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*la*z;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]+F.dx[i]*F.dx[j]*la)*la*z;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, log(), pow(), and duals< dim >::x.
sin()
template<ui dim>
duals<dim> sin (duals< dim > F)
Definition at line 392 of file autodiff2.libmd.cc.
{
    const ldf sf=std::sin(F.x),cf=std::cos(F.x);
    duals<dim> H(sf);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*cf;
        for (ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]*cf-F.dx[i]*F.dx[j]*sf;
    }
    return H;
}
References cos(), duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
sinh()
template<ui dim>
duals<dim> sinh (duals< dim > F)
Definition at line 428 of file autodiff2.libmd.cc.
{
    const ldf sf=std::sinh(F.x),cf=std::cosh(F.x);
    duals<dim> H(sf);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*cf;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=F.dxdy[i][j]*cf+F.dx[i]*F.dx[j]*sf;
    }
    return H;
}
References cosh(), duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
sqrt()
template<ui dim>
duals<dim> sqrt (duals< dim > F)
Definition at line 320 of file autodiff2.libmd.cc.
{
    const ldf r=std::sqrt(F.x);
    duals<dim> H(r);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]/2.0/r;
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]-F.dx[i]*F.dx[j]/2.0/F.x)/2.0/r;
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
tan()
template<ui dim>
duals<dim> tan (duals< dim > F)
Definition at line 416 of file autodiff2.libmd.cc.
{
    const ldf tf=std::tan(F.x);
    duals<dim> H(tf);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*(1.0+tf*tf);
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]+F.dx[i]*F.dx[j]*2.0*tf)*(1.0+tf*tf);
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.
tanh()
template<ui dim>
duals<dim> tanh (duals< dim > F)
Definition at line 452 of file autodiff2.libmd.cc.
{
    const ldf tf=std::tanh(F.x);
    duals<dim> H(tf);
    for(ui i=0;i<dim;i++)
    {
        H.dx[i]=F.dx[i]*(1.0-tf*tf);
        for(ui j=i;j<dim;j++) H.dxdy[i][j]=H.dxdy[j][i]=(F.dxdy[i][j]-F.dx[i]*F.dx[j]*2.0*tf)*(1.0-tf*tf);
    }
    return H;
}
References duals< dim >::dx, duals< dim >::dxdy, and duals< dim >::x.