libmd-src/boundaryconditions.libmd.cc File Reference
#include `../libmd.h`
Macros
#define __libmd_src_file__
Functions
template<ui dim>
void BCOND_NONE (ui d, ui i, void *sys)
template<ui dim>
void BCOND_NONE (ui d, ldf x[dim], void *sys)
template<ui dim>
void BCOND_PERIODIC (ui d, ui i, void *sys)
template<ui dim>
void BCOND_PERIODIC (ui d, ldf x[dim], void *sys)
template<ui dim>
void BCOND_HARD (ui d, ui i, void *sys)
template<ui dim>
void BCOND_HARD (ui d, ldf x[dim], void *sys)
template<ui dim>
void BCOND_BOXSHEAR (ui d, ui i, void *sys)
template<ui dim>
void BCOND_BOXSHEAR (ui d, ldf x[dim], void *sys)
Macro Definition Documentation
__libmd_src_file__
#define __libmd_src_file__
Definition at line 1 of file boundaryconditions.libmd.cc.
Function Documentation
BCOND_BOXSHEAR() [1/2]
template<ui dim>
void BCOND_BOXSHEAR (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has sheared boundary conditions.
Checks if point x is outside the boundary perpendicular to dimension d and, if so, updates its position according to the box shear matrices stored in simbox.Lshear and simbox.vshear. The particle position
Definition at line 184 of file boundaryconditions.libmd.cc.
{
    const ldf boundaryCrossing=std::round(x[d]/SYS->simbox.L[d]);
    if((int)boundaryCrossing) for(ui k=0;k<dim;k++) x[k]-=SYS->simbox.Lshear[k][d]*boundaryCrossing;
}
References SYS.
BCOND_BOXSHEAR() [2/2]
template<ui dim>
void BCOND_BOXSHEAR (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has sheared boundary conditions.
Checks if particle i has crossed the boundary perpendicular to dimension d and, if so, updates its position and velocity according to the box shear matrices stored in simbox.Lshear and simbox.vshear. The particle position
Definition at line 164 of file boundaryconditions.libmd.cc.
{
    const ldf boundaryCrossing=std::round(SYS->particles[i].x[d]/SYS->simbox.L[d]);
    if((int)boundaryCrossing) for(ui k=0;k<dim;k++)
    {
        SYS->particles[i].x[k]-=SYS->simbox.Lshear[k][d]*boundaryCrossing;
        SYS->particles[i].xp[k]-=SYS->simbox.Lshear[k][d]*boundaryCrossing;
        SYS->particles[i].dx[k]-=SYS->simbox.vshear[k][d]*boundaryCrossing;
    }
}
References SYS.
BCOND_HARD() [1/2]
template<ui dim>
void BCOND_HARD (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has hard boundary conditions.
Checks if point x is outside the boundary perpendicular to dimension d and, if so, updates its position to respect a hard wall reflection. The particle position is mirrored across the boundary wall.
 This function correctly takes into account skewed boundary conditions, and uses the box matrices simbox.Lshear and simbox.vshear to calculate the reflections if simbox.useLshear is true.
Definition at line 119 of file boundaryconditions.libmd.cc.
{
    if (SYS->simbox.useLshear)
    {
        ldf s=0;
        for (ui k=0;k<dim;k++) s+=SYS->simbox.LshearInv[d][k]*x[k];
        if (std::abs(s) > 0.5) // particle has hit the hard boundary as distorted by the shear
        {
            if (std::abs(s) > 1.) { WARNING("dynamics led to particle displacement bigger than box size; hard boundary reflections undefined"); }
            ldf nhat[dim];
            ldf nlen=0.,xperp=0.,x0perp;
            // the normal vector to the box boundary in dimension d is the dth row of LshearInv
            for (ui k=0;k<dim;k++) nlen += SYS->simbox.LshearInv[d][k]*SYS->simbox.LshearInv[d][k];
            nlen = sqrt(nlen);
            // projection of velocity and position perpendicular to boundary wall
            for (ui k=0;k<dim;k++) {
                nhat[k] = SYS->simbox.LshearInv[d][k]/nlen;
                xperp += nhat[k]*x[k];
            }
            x0perp = nhat[d]*SYS->simbox.Lshear[d][d]*0.5*(s > 0.? 1.:-1.);
            // subtract perpendicular component twice to get reflected velocity
            for (ui k=0;k<dim;k++) x[k] -= 2.0*(xperp-x0perp)*nhat[k]; // reflection about a plane passing through point set by x0perp
        }
    }
    else
    {
        const ldf xnew=SYS->simbox.L[d]*(std::abs(x[d]/SYS->simbox.L[d]+0.5-2.0*floor(x[d]/(2.0*SYS->simbox.L[d])+0.75))-0.5);
        x[d]=xnew;
    }
}
References abs(), sqrt(), SYS, and WARNING.
BCOND_HARD() [2/2]
template<ui dim>
void BCOND_HARD (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has hard boundary conditions.
Checks if particle i has crossed the boundary perpendicular to dimension d and, if so, updates its position and velocity to respect a hard wall reflection. The particle position is mirrored across the boundary wall, whereas its velocity component perpendicular to the boundary wall is reversed.
 This function correctly takes into account skewed boundary conditions, and uses the box matrices simbox.Lshear and simbox.vshear to calculate the reflections if simbox.useLshear is true.
Definition at line 61 of file boundaryconditions.libmd.cc.
{
    if (SYS->simbox.useLshear)
    {
        ldf s=0;
        for (ui k=0;k<dim;k++) s+=SYS->simbox.LshearInv[d][k]*SYS->particles[i].x[k];
        if (std::abs(s) > 0.5) // particle has hit the hard boundary as distorted by the shear
        {
            if (std::abs(s) > 1.) { WARNING("dynamics led to particle displacement bigger than box size; hard boundary reflections undefined"); }
            ldf nhat[dim];
            ldf nlen=0.,vperp=0.,xperp=0.,x0perp;
            // the normal vector to the box boundary in dimension d is the dth row of LshearInv
            for (ui k=0;k<dim;k++) nlen += SYS->simbox.LshearInv[d][k]*SYS->simbox.LshearInv[d][k];
            nlen = sqrt(nlen);
            // projection of velocity and position perpendicular to boundary wall
            for (ui k=0;k<dim;k++) {
                nhat[k] = SYS->simbox.LshearInv[d][k]/nlen;
                vperp += nhat[k]*SYS->particles[i].dx[k];
                xperp += nhat[k]*SYS->particles[i].x[k];
            }
            x0perp = nhat[d]*SYS->simbox.Lshear[d][d]*0.5*(s > 0.? 1.:-1.);
            // subtract perpendicular component twice to get reflected velocity
            for (ui k=0;k<dim;k++)
            {
                SYS->particles[i].dx[k] -= 2.0*vperp*nhat[k];
                SYS->particles[i].x[k] -= 2.0*(xperp-x0perp)*nhat[k]; // reflection about a plane passing through point set by x0perp
                SYS->particles[i].xp[k] += 2.0*(xperp-x0perp)*nhat[k];
            }
        }
    }
    else
    {
        const ldf xnew=SYS->simbox.L[d]*(std::abs(SYS->particles[i].x[d]/SYS->simbox.L[d]+0.5-2.0*floor(SYS->particles[i].x[d]/(2.0*SYS->simbox.L[d])+0.75))-0.5);
        const ldf sign=(((int)std::round(SYS->particles[i].x[d]/SYS->simbox.L[d]))%2?-1.0:1.0);
        SYS->particles[i].xp[d]+=sign*(xnew-SYS->particles[i].x[d]);
        SYS->particles[i].x[d]=xnew;
        SYS->particles[i].dx[d]*=sign;
    }
}
References abs(), sqrt(), SYS, and WARNING.
BCOND_NONE() [1/2]
template<ui dim>
void BCOND_NONE (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has no boundary conditions.
This function does nothing
Definition at line 19 of file boundaryconditions.libmd.cc.
{
    (void) d;
    (void) x;
    (void) sys;
}
BCOND_NONE() [2/2]
template<ui dim>
void BCOND_NONE (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has no boundary conditions.
This function does nothing
Definition at line 6 of file boundaryconditions.libmd.cc.
{
    (void) d;
    (void) i;
    (void) sys;
}
BCOND_PERIODIC() [1/2]
template<ui dim>
void BCOND_PERIODIC (ui d, ldf x[dim], void * sys)
Periodicity function to be called if dimension d has periodic boundary conditions.
Checks if point x is outside the boundary perpendicular to dimension d and, if so, shifts its coordinate in that dimension by multiples of simbox.L[d] so that it is within the bounds (-simbox.L[d]/2,simbox.L[d]/2).
Definition at line 47 of file boundaryconditions.libmd.cc.
{
    const ldf dx=SYS->simbox.L[d]*std::round(x[d]/SYS->simbox.L[d]);
    x[d]-=dx;
}
References SYS.
BCOND_PERIODIC() [2/2]
template<ui dim>
void BCOND_PERIODIC (ui d, ui i, void * sys)
Periodicity function to be called if dimension d has periodic boundary conditions.
Checks if particle i has crossed the boundary perpendicular to dimension d and, if so, shifts its coordinate in that dimension by multiples of simbox.L[d] so that it is within the bounds (-simbox.L[d]/2,simbox.L[d]/2).
Definition at line 32 of file boundaryconditions.libmd.cc.
{
    const ldf dx=SYS->simbox.L[d]*std::round(SYS->particles[i].x[d]/SYS->simbox.L[d]);
    SYS->particles[i].xp[d]-=dx;
    SYS->particles[i].x[d]-=dx;
}
References SYS.