mpmd< dim > Struct Template Reference
This structure takes care of Monge patch molecular dynamics simulations.
#include <libmd.h>
Public Member Functions
ldf embedded_distsq (ui p1, ui p2)
Calculate distances between two particles (squared)
ldf embedded_distsq (ldf x1[dim], ldf x2[dim])
Calculate distances between two particles (squared)
ldf embedded_distsq (ui p1, ldf x2[dim])
Calculate distances between two particles (squared)
ldf embedded_distsq (ldf x2[dim], ui p2)
Calculate distances between two particles (squared)
ldf embedded_dd_p1 (ui d, ui p1, ui p2)
Calculate particles relative particle in certain dimension i wrt p1.
ldf embedded_dd_p2 (ui d, ui p1, ui p2)
Calculate particles relative particle in certain dimension i wrt p2.
void zuiden_C (ui i, ldf ZC[dim])
Calculates $g^{\rho \sigma} C_{\sigma}$ for particle i of the van Zuiden integrator.
void zuiden_A (ui i, ldf eps[dim])
Calculates $g^{\rho \sigma} A_{\sigma \mu \nu} \epsilon^{\mu} \epsilon^{\nu}$ for particle i of the van Zuiden integrator.
void thread_zuiden_wfi (ui i)
The van Zuiden integrator without fixed point itterations.
void thread_zuiden_protect (ui i)
The van Zuiden integrator with protected fixed point itterations (makes sure you don't get stuck in a loop)
void thread_zuiden (ui i)
The van Zuiden integrator for Riemannian manifolds (fails for pseudo-Riemannian manifolds)
void thread_history (ui i)
Set the history of particle i.
void history ()
Set the history of all particles.
void thread_calc_geometry (ui i)
Calculate Monge patch derivatives for partice i.
void calc_geometry ()
Calculate Monge patch derivatives.
void mp_thread_calc_pot_forces (ui i)
Calculate the forces for particle i>j with atomics.
void integrate () override final
Integrate particle trajectoriess.
void calc_forces () override final
Integrate particle trajectoriess.
void recalc_forces () override final
Integrate particle trajectoriess.
ldf thread_T (ui i) override final
Calculate kinetic energy of a particle.
ldf thread_V (ui i, bool higher_index_only=false) override final
Calculate potential energy.
void set_langevin (ldf T, ldf gamma) override final
Enables Langevin thermostat (and damping) and sets T and gamma (does not use metric)
void init (ui particlenr)
Copy of the particle number constructor.
ldf dap (ui d, ldf ad)
Manipulate particle distances with respect to periodic boundary conditions.
ldf distsq (ui p1, ui p2)
Calculate distances between two particles (squared)
ldf distsq (ldf x1[dim], ldf x2[dim])
Calculate distances between two particles (squared) ldf distsq(ui p1,ldf x2[dim]); ///< Calculate distances between two particles (squared)
ldf distsq (ui p1, ldf x2[dim])
Calculate distances between two particles (squared)
ldf distsq (ldf x1[dim], ui p2)
Calculate distances between two particles (squared)
ldf dd (ui d, ui p1, ui p2)
Calculate difference in particle positions in certain dimension i by particle index.
ldf dd (ui d, ldf x1[dim], ldf x2[dim])
Calculate difference in particle positions in certain dimension i by particle index.
ldf dd (ui d, ui p1, ldf x2[dim])
Calculate difference in particle positions in certain dimension i by particle index.
ldf dd (ui d, ldf x1[dim], ui p2)
Calculate difference in particle positions in certain dimension i by particle index.
ldf dv (ui d, ui p1, ui p2)
Calculate difference in particle velocities in certain dimension i by particle index.
void interactions (ui i, std::vector< std::pair< ui, ui >> &table)
Dump interactions of a certain particle into a table.
void all_interactions (std::vector< std::pair< ui, ui >> &table)
Dump all interaction into a table.
ui add_interaction (ui potential, std::vector< ldf > &parameters)
Add type interaction rule.
ui add_interaction (ui potential, ldf rco, std::vector< ldf > &parameters)
Add type interaction rule.
bool mod_interaction (ui interaction, ui potential, std::vector< ldf > &parameters)
Modify type interaction rule.
bool mod_interaction (ui interaction, ui potential, ldf rco, std::vector< ldf > &parameters)
Modify type interaction rule.
bool rem_interaction (ui interaction)
Delete type interaction rule.
bool add_typeinteraction (ui type1, ui type2, ui interaction)
Add type interaction rule.
bool add_typeinteraction (ui type1, ui type2, ui potential, std::vector< ldf > &parameters)
Add type interaction rule.
bool add_typeinteraction (ui type1, ui type2, ui potential, ldf rco, std::vector< ldf > &parameters)
Add type interaction rule.
bool mod_typeinteraction (ui type1, ui type2, ui interaction)
Modify type interaction rule.
bool mod_typeinteraction (ui type1, ui type2, ui potential, std::vector< ldf > &parameters)
Modify type interaction rule.
bool mod_typeinteraction (ui type1, ui type2, ui potential, ldf rco, std::vector< ldf > &parameters)
Modify type interaction rule.
void mad_typeinteraction (ui type1, ui type2, ui interaction)
Force add/mod type interaction rule.
void mad_typeinteraction (ui type1, ui type2, ui potential, std::vector< ldf > &parameters)
Force add/mod type interaction rule.
void mad_typeinteraction (ui type1, ui type2, ui potential, ldf rco, std::vector< ldf > &parameters)
Force add/mod type interaction rule.
bool rem_typeinteraction (ui type1, ui type2)
Delete type interaction rule.
ui add_sptype ()
Add superparticletype.
bool rem_sptype (ui spt)
Delete superparticletype.
bool add_sp_interaction (ui spt, ui p1, ui p2, ui interaction)
Add superparticle interaction rule.
bool add_sp_interaction (ui spt, ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Add superparticle interaction rule.
bool add_sp_interaction (ui spt, ui p1, ui p2, ui potential, ldf rco, std::vector< ldf > &parameters)
Add superparticle interaction rule.
bool mod_sp_interaction (ui spt, ui p1, ui p2, ui interaction)
Modify superparticle interaction rule.
bool mod_sp_interaction (ui spt, ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Modify superparticle interaction rule.
bool mod_sp_interaction (ui spt, ui p1, ui p2, ui potential, ldf rco, std::vector< ldf > &parameters)
Modify superparticle interaction rule.
ui mad_sp_interaction (ui spt, ui p1, ui p2, ui interaction)
Force add/mod superparticle interaction rule.
ui mad_sp_interaction (ui spt, ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Force add/mod superparticle interaction rule.
ui mad_sp_interaction (ui spt, ui p1, ui p2, ui potential, ldf rco, std::vector< ldf > &parameters)
Force add/mod superparticle interaction rule.
bool rem_sp_interaction (ui spt, ui p1, ui p2)
Delete superparticle interaction rule.
ui add_forcetype (ui force, std::vector< ldf > &parameters)
Add force type.
ui add_forcetype (ui force, std::vector< std::vector< ui >> &plist, std::vector< ldf > &parameters)
Add force type with plist.
bool mod_forcetype (ui ftype, ui force, std::vector< ldf > &parameters)
Modify force type.
bool mod_forcetype (ui ftype, ui force, std::vector< std::vector< ui >> &plist, std::vector< ldf > &parameters)
Modify force type plist.
bool rem_forcetype (ui ftype)
Delete force type.
bool assign_forcetype (ui i, ui ftype)
Assign force type to particle.
void assign_all_forcetype (ui ftype)
Assign force type to all particles.
bool unassign_forcetype (ui i, ui ftype)
Unassign force type to particle.
void unassign_all_forcetype (ui ftype)
Unassign force type to all particles.
void clear_all_assigned_forcetype ()
Clear all assigned forces.
ui add_hook (ui nohook, std::vector< ldf > &parameters)
Add a hook.
bool mod_hook (ui htype, ui nohook, std::vector< ldf > &parameters)
Modify a hook.
bool rem_hook (ui htype)
Remove a hook.
bool run_hook (ui htype)
Run a certain hook.
void run_hooks ()
Run all hooks.
ldf get_rco (ui i, ui j)
Gets the cuttoff radius for a certain pair of particles.
ldf get_rco (ui interaction)
Gets the cuttoff radius for a certain interaction.
void set_rco (ldf rco)
Sets the cuttoff radius.
void set_rco (ui interaction, ldf rco)
Sets the cuttoff radius.
void set_ssz (ldf ssz)
Sets the skin size radius and its square.
void set_reserve (ldf ssz)
Set reserve memory according to skin size.
void set_reserve (ldf ssz, ui M)
Set reserve memory according to skin size and some arbitrary number of particles.
void set_type (ui p, ui newtype)
Update the type associated with particle p.
void set_index_method (ui method)
Set indexmethod.
void index ()
Find neighbors.
bool test_index ()
Test if we need to run the indexing algorithm.
void thread_index_stick (ui i)
Save the particle position at indexing.
ui kdtree_build (ui first, ui last, ui level)
k-d tree indexing algorithm: tree build function (recursive)
void kdtree_index (ui first1, ui last1, ui first2, ui last2)
k-d tree indexing algorithm: neighbor finder (recursive)
void kdtree ()
k-d tree indexing algorithm
void cell ()
Cell indexing algorithm.
void thread_cell (ui c)
Cell indexer for cell c (thread)
void bruteforce ()
Bruteforce indexing algorithm.
void skinner (ui i, ui j, ldf sszsq)
Places interactionneighbor in skin.
void thread_clear_forces (ui i)
Clear forces for particle i.
void thread_calc_pot_forces (ui i)
Calculate the forces for particle i>j with atomics.
void thread_calc_ext_forces (ui i)
Calculate the forces for particle i>j with atomics.
void update_boundaries ()
Shifts the periodic boxes appropriately for sheared BC.
void periodicity ()
Called after integration to keep the particle within the defined boundaries.
void thread_periodicity (ui i)
Apply periodicity to one particle only.
void thread_periodicity (ldf x[dim])
Apply periodicity to one particle only.
void thread_seuler (ui i)
Symplectic euler integrator (threaded)
void thread_vverlet_x (ui i)
Velocity verlet integrator for position (threaded)
void thread_vverlet_dx (ui i)
Velocity verlet integrator for velocity (threaded)
void thread_first_order (ui i)
First order (Euler) integrator (threaded)
void thread_overdamped (ui i)
First order (Euler) integrator for overdamped dynamics (threaded)
void timestep ()
Do one timestep.
void timesteps (ui k)
Do multiple timesteps.
void import_pos (ldf *x)
Load positions from arrays.
template<typename... arg>
void import_pos (ldf *x, arg...argv)
Load positions from arrays.
void import_pos (ui i, ldf x)
Load position for i from value.
template<typename... arg>
void import_pos (ui i, ldf x, arg...argv)
Load position for i from value.
void import_vel (ldf *dx)
Load velocity from arrays.
template<typename... arg>
void import_vel (ldf *dx, arg...argv)
Load velocity from arrays.
void import_vel (ui i, ldf dx)
Load velocity for i from value.
template<typename... arg>
void import_vel (ui i, ldf dx, arg...argv)
Load velocity for i from value.
void import_force (ldf *F)
Load forces from arrays.
template<typename... arg>
void import_force (ldf *F, arg...argv)
Load forces from arrays.
void import_force (ui i, ldf F)
Load position for i from value.
template<typename... arg>
void import_force (ui i, ldf F, arg...argv)
Load position for i from value.
void export_pos (ldf *x)
Save positions from arrays.
template<typename... arg>
void export_pos (ldf *x, arg...argv)
Save positions to arrays.
void export_pos (ui i, ldf &x)
Save positions from arrays.
template<typename... arg>
void export_pos (ui i, ldf &x, arg...argv)
Save positions to arrays.
void export_vel (ldf *dx)
Save velocity from arrays.
template<typename... arg>
void export_vel (ldf *dx, arg...argv)
Save velocity to arrays.
void export_vel (ui i, ldf &dx)
Save positions from arrays.
template<typename... arg>
void export_vel (ui i, ldf &dx, arg...argv)
Save positions to arrays.
void export_force (ldf *F)
Save forces from arrays.
template<typename... arg>
void export_force (ldf *F, arg...argv)
Save forces to arrays.
void export_force (ui i, ldf &F)
Save forces from arrays.
template<typename... arg>
void export_force (ui i, ldf &F, arg...argv)
Save forces to arrays.
ldf direct_readout_x (ui d, ui i)
Directly readout a position.
ldf direct_readout_dx (ui d, ui i)
Directly readout a velocity.
ldf direct_readout_F (ui d, ui i)
Directly readout a forces.
ldf direct_readout (ui d, ui i, uc type)
Directly readout a position'x'/velocity'v'/forces'F'.
ldf direct_readout (ui i, uc type)
Directly readout a position'x'/velocity'v'/forces'F'.
void fix_particle (ui i, bool fix)
Fix a particle.
void fix_sp (ui spi, bool fix)
Fix a super particles.
ui clone_particle (ui i, ldf x[dim])
Clone a particle and translate.
ui clone_sp (ui spi, ldf x[dim])
Clone a superparticle and translate.
void translate_particle (ui i, ldf x[dim])
Translate (or move) a particle.
void translate_sp (ui spi, ldf x[dim])
Translate (or move) a super particle.
void drift_particle (ui i, ldf dx[dim])
Add velocity to a particle.
void drift_sp (ui spi, ldf dx[dim])
Add velocity to a super particle (all particles the same)
void heat_particle (ui i, ldf lambda)
Multiply velocity vector of a particle with a scalar.
void heat_sp (ui spi, ldf lambda)
Multiply velocity vectors of a super particle with a scalar (all particles the same)
void set_position_sp (ui spi, ldf x[dim])
Get center of mass of super particle.
void set_velocity_sp (ui spi, ldf dx[dim])
Assign velocity to a super particle (all particles the same)
void get_position_sp (ui spi, ldf x[dim])
Get center of mass of super particle.
void get_velocity_sp (ui spi, ldf dx[dim])
Get average velocity of a super particle.
ui add_sp (ui sptype)
Add a superparticle.
bool rem_sp (ui spi)
Remove a superparticle (i.e. the structure, not the particles)
bool rem_sp_particles (ui spi)
Remove all particles in a superparticle.
ui sp_ingest (ui spi, ui i, ui idx=UI_MAX)
Add a particle to a superparticle.
bool sp_dispose (ui i)
Remove a particle from a superparticle.
bool sp_dispose_idx (ui spi, ui idx)
Remove a particle from a superparticle.
ui sp_pid (ui spi, ui idx)
Reverse lookup of particle id in superparticle.
ui add_particle (ldf mass=1.0, ui ptype=0, bool fixed=false)
Add a particle to the system.
ui add_particle (ldf x[dim], ldf mass=1.0, ui ptype=0, bool fixed=false)
Add a particle to the system at certain position.
ui add_particle (ldf x[dim], ldf dx[dim], ldf mass=1.0, ui ptype=0, bool fixed=false)
Add a particle to the system at certain position with certain velocity.
ui add_particle (ldf x[dim], ldf dx[dim], uc bcond[dim], ldf mass=1.0, ui ptype=0, bool fixed=false, bool bconded=true)
Add a particle to the system at certain position with certain velocity with certain bconds.
void rem_particle (ui i)
Remove a particle from the system.
void clear ()
Clear all particles and interactions.
void set_damping (ldf coefficient)
Enables damping and sets damping coefficient.
bool unset_damping ()
Disables damping.
bool unset_langevin ()
Disable Langevin thermostat.
void set_overdamped (ldf coefficient)
Enable overdamped dynamics (with First oder integration)
bool unset_overdamped ()
Disable overdamped dynamics.
void update_skins (ui p1, ui p2)
Modify skins after adding/modifying/removing bond.
bool add_bond (ui p1, ui p2, ui interaction)
Add a bond.
bool add_bond (ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Add a bond.
bool mod_bond (ui p1, ui p2, ui interaction)
Modify a bond.
bool mod_bond (ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Modify a bond.
void mad_bond (ui p1, ui p2, ui interaction)
Force add/modify bond.
void mad_bond (ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Force add/modify bond.
bool rem_bond (ui p1, ui p2)
Remove a bond from the system.
void assign_unique_types (ui p1, ui p2)
Assign unique types to particles, modify lookup.
void add_spring (ui p1, ui p2, ldf springconstant, ldf l0)
Add a harmonic bond to the system.
bool add_sp_bond (ui p1, ui p2, ui interaction)
Add a superparticle bond.
bool add_sp_bond (ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Add a superparticle bond.
bool mod_sp_bond (ui p1, ui p2, ui interaction)
Modify a superparticle bond.
bool mod_sp_bond (ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Modify a superparticle bond.
void mad_sp_bond (ui p1, ui p2, ui interaction)
Force add/modify superparticle bond.
void mad_sp_bond (ui p1, ui p2, ui potential, std::vector< ldf > &parameters)
Force add/modify superparticle bond.
bool rem_sp_bond (ui p1, ui p2)
Remove a superparticle bond from the system.
ui clone_sptype (ui sp)
Make a new sptype for superparticle sp if it is not unique to sp.
void set_bcond (uc bcond[dim])
Set the global boundary conditions.
void set_pbcond (ui i, uc bcond[dim], bool toggle=true)
Set the boundary conditions for particle i.
void set_spbcond (ui spi, uc bcond[dim], bool toggle=true)
Set the boundary conditions for superparticle spi.
ldf thread_H (ui i)
Measure Hamiltonian for particle i.
ldf H ()
Measure Hamiltonian.
ldf T ()
Measure kinetic energy.
ldf V ()
Measure potential energy.
Public Attributes
mp< dim > patch
Geometric monge patch information.
ui N
Number of particles.
box< dim > simbox
Simulation box.
bcond< dim > boundary
Boundary conditions functor.
std::vector< particle< dim > > particles
Particle array.
interact network
Interaction network.
indexer< dim > indexdata
Data structure for indexing.
pairpotentials v
Pair potential functor.
externalforces< dim > f
External forces functor.
hooker< dim > hooks
Hook functor.
integrators integrator
Integration method.
variadic_vars< dim > vvars
Bunch of variables for variadic functions.
additional_vars< dim > avars
Bunch of additonal variables.
Detailed Description
template<ui dim>
struct mpmd< dim >
This structure takes care of Monge patch molecular dynamics simulations.
Definition at line 617 of file libmd.h.
Member Function Documentation
add_bond() [1/2]
template<ui dim>
bool md< dim >::add_bond (ui p1, ui p2, ui interaction) [inherited]
Add a bond.
This function adds a bond between particles p1 and p2 of previously-defined interaction type interaction. (See the Interactions documentation for more information on interaction types.)
 Does nothing and returns false if one of the following holds:
an interaction already exists between p1 and p2,
the interaction specified by the third argument does not exist or was previously removed.
Otherwise, creates a bond of the specified type between p1 and p2, and returns true.
Definition at line 42 of file bonds.md.libmd.cc.
{
    if (network.lookup.count(network.hash(particles[p1].type,particles[p2].type)))
        return false;
    else if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    { assign_unique_types(p1, p2);
        network.lookup[network.hash(particles[p1].type,particles[p2].type)]=interaction;
        update_skins(p1,p2);
        return true;
    }
}
References WARNING.
add_bond() [2/2]
template<ui dim>
bool md< dim >::add_bond (ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Add a bond.
This function adds a bond between particles p1 and p2 with the potential type and parameters specified in the arguments. (See the Interactions documentation for more information on potential types and passing parameters.)
 Does nothing if an interaction already exists between p1 and p2, and returns false. Otherwise, creates a bond of the specified type between p1 and p2, and returns true.
Definition at line 130 of file bonds.md.libmd.cc.
{
    if (!network.lookup.count(network.hash(particles[p1].type,particles[p2].type)))
    { mad_bond(p1, p2, add_interaction(potential, parameters));
        return true;
    }
    else
        return false;
}
add_forcetype() [1/2]
template<ui dim>
ui md< dim >::add_forcetype (ui force, std::vector< ldf > & parameters) [inherited]
Add force type.
This function adds a new forcetype, of the given type and with the given parameters, to network.forcelibrary[] and returns its index.
Definition at line 512 of file interaction.md.libmd.cc.
{
    forcetype temp(force,parameters);
    network.forcelibrary.push_back(temp);
    return network.forcelibrary.size()-1;
}
add_forcetype() [2/2]
template<ui dim>
ui md< dim >::add_forcetype (ui force, std::vector< std::vector< ui >> & plist, std::vector< ldf > & parameters) [inherited]
Add force type with plist.
This function adds a new forcetype, of the given type and with the given parameters, to network.forcelibrary[] and returns its index.
Definition at line 522 of file interaction.md.libmd.cc.
{
    forcetype temp(force,plist,parameters);
    network.forcelibrary.push_back(temp);
    return network.forcelibrary.size()-1;
}
add_hook()
template<ui dim>
ui md< dim >::add_hook (ui nohook, std::vector< ldf > & parameters) [inherited]
Add a hook.
This function adds a new hook, of the given type and with the given parameters, to hooks.hookers[] and returns its index.
Definition at line 6 of file hooks.md.libmd.cc.
{
    hooktype temp(hook,parameters);
    hooks.hookers.push_back(temp);
    return hooks.hookers.size()-1;
}
add_interaction() [1/2]
template<ui dim>
ui md< dim >::add_interaction (ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Add type interaction rule.
This function adds a new interaction, of the given type and with the given parameters, to network.library[] and returns its index.
Definition at line 33 of file interaction.md.libmd.cc.
{
    interactiontype itype(potential,parameters,rco,v(potential,rco,parameters));
    if(network.free_library_slots.empty())
    {
        network.library.push_back(itype);
        return network.library.size()-1;
    }
    else
    {
        ui retval=*network.free_library_slots.begin();
        network.free_library_slots.erase(network.free_library_slots.begin());
        network.library[retval]=itype;
        return retval;
    }
}
add_interaction() [2/2]
template<ui dim>
ui md< dim >::add_interaction (ui potential, std::vector< ldf > & parameters) [inherited]
Add type interaction rule.
This function adds a new interaction, of the given type and with the given parameters, to network.library[] and returns its index.
Definition at line 25 of file interaction.md.libmd.cc.
{
    return add_interaction(potential,network.rco,parameters);
}
add_particle() [1/4]
template<ui dim>
ui md< dim >::add_particle (ldf mass = 1.0, ui ptype = 0, bool fixed = false) [inherited]
Add a particle to the system.
This function adds a particle to the system and returns its index. Optionally, provide its mass (default: 1.0), type (default: 0) and/or whether it is fixed (default: false). The position and velocity of the new particle are not set.
Definition at line 6 of file particles.md.libmd.cc.
{
    avars.export_force_calc=true;
    N++;
    particles.push_back(particle<dim>(mass,ptype,fixed));
    network.spid.push_back(UI_MAX);
    network.skins.resize(N);
    network.forces.resize(N);
    for(auto lib: network.forcelibrary) lib.particles.resize(N);
    avars.reindex=true;
    return N-1;
}
References UI_MAX.
add_particle() [2/4]
template<ui dim>
ui md< dim >::add_particle (ldf x[dim], ldf dx[dim], ldf mass = 1.0, ui ptype = 0, bool fixed = false) [inherited]
Add a particle to the system at certain position with certain velocity.
This function adds a particle to the system at position x[] with velocity dx[] and returns its index. Optionally, provide its mass (default: 1.0), type (default: 0) and/or whether it is fixed (default: false).
Definition at line 40 of file particles.md.libmd.cc.
{
    ldf tempx[dim],tempdx[dim];
    memcpy(tempx,x,dim*sizeof(ldf));
    memcpy(tempdx,dx,dim*sizeof(ldf));
    ui i=add_particle(mass,ptype,fixed);
    DEBUG_2("created particle #" F_UI " with given position and velocity",i);
    memcpy(particles[i].x,tempx,dim*sizeof(ldf));
    memcpy(particles[i].dx,tempdx,dim*sizeof(ldf));
    return i;
}
References DEBUG_2, and F_UI.
add_particle() [3/4]
template<ui dim>
ui md< dim >::add_particle (ldf x[dim], ldf dx[dim], uc bcond[dim], ldf mass = 1.0, ui ptype = 0, bool fixed = false, bool bconded = true) [inherited]
Add a particle to the system at certain position with certain velocity with certain bconds.
This function adds a particle to the system at position x[] with velocity dx[] and returns its index. Optionally, provide its mass (default: 1.0), type (default: 0) and/or whether it is fixed (default: false).
Definition at line 56 of file particles.md.libmd.cc.
{
    ldf tempx[dim],tempdx[dim];
    uc tempbcond[dim];
    memcpy(tempx,x,dim*sizeof(ldf));
    memcpy(tempdx,dx,dim*sizeof(ldf));
    memcpy(tempbcond,bcond,dim*sizeof(uc));
    ui i=add_particle(mass,ptype,fixed);
    particles[i].usepbcond=bconded;
    DEBUG_2("created particle #" F_UI " with given position, velocity and bconds",i);
    memcpy(particles[i].x,tempx,dim*sizeof(ldf));
    memcpy(particles[i].dx,tempdx,dim*sizeof(ldf));
    memcpy(particles[i].bcond,tempbcond,dim*sizeof(uc));
    return i;
}
References DEBUG_2, and F_UI.
add_particle() [4/4]
template<ui dim>
ui md< dim >::add_particle (ldf x[dim], ldf mass = 1.0, ui ptype = 0, bool fixed = false) [inherited]
Add a particle to the system at certain position.
This function adds a particle to the system at position x[] and returns its index. Optionally, provide its mass (default: 1.0), type (default: 0) and/or whether it is fixed (default: false). The velocity of the new particle is not set.
Definition at line 24 of file particles.md.libmd.cc.
{
    ldf tempx[dim];
    memcpy(tempx,x,dim*sizeof(ldf));
    ui i=add_particle(mass,ptype,fixed);
    DEBUG_2("created particle #" F_UI " with given position",i);
    memcpy(particles[i].x,tempx,dim*sizeof(ldf));
    memset(particles[i].dx,0,dim*sizeof(ldf));
    return i;
}
References DEBUG_2, and F_UI.
add_sp()
template<ui dim>
ui md< dim >::add_sp (ui sptype) [inherited]
Add a superparticle.
This function adds a superparticle of type sptype to network.superparticles[] and returns its index
Definition at line 6 of file sp.md.libmd.cc.
{
    ui spi = network.superparticles.size();
    network.superparticles.push_back(superparticle());
    network.superparticles[spi].sptype = sptype;
    DEBUG_2("added superparticle #" F_UI " with type " F_UI "",spi,sptype);
    return spi;
}
References DEBUG_2, and F_UI.
add_sp_bond() [1/2]
template<ui dim>
bool md< dim >::add_sp_bond (ui p1, ui p2, ui interaction) [inherited]
Add a superparticle bond.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then adds an interaction between the two particles, using element interaction from network.library[]. If the two particles are not in the same superparticle, or have an interaction already, it does nothing and returns false.
Definition at line 261 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    if (spi == UI_MAX || spi != network.spid[p2])
        return false;
    ui spt = network.superparticles[spi].sptype;
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    if (network.sptypes[spt].splookup.count(id))
        return false;
    network.sptypes[clone_sptype(spi)].splookup[id] = interaction;
    update_skins(p1,p2);
    return true;
}
References UI_MAX.
add_sp_bond() [2/2]
template<ui dim>
bool md< dim >::add_sp_bond (ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Add a superparticle bond.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then adds an interaction between the two particles, using a new interaction of the given type and with the given parameters. If the two particles are not in the same superparticle, or have an interaction already, it does nothing and returns false.
Definition at line 312 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    if (spi == UI_MAX || spi != network.spid[p2])
        return false;
    ui spt = network.superparticles[spi].sptype;
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    if (network.sptypes[spt].splookup.count(id))
        return false;
    network.sptypes[clone_sptype(spi)].splookup[id] = add_interaction(potential, parameters);
    update_skins(p1,p2);
    return true;
}
References UI_MAX.
add_sp_interaction() [1/3]
template<ui dim>
bool md< dim >::add_sp_interaction (ui spt, ui p1, ui p2, ui interaction) [inherited]
Add superparticle interaction rule.
This function adds an interaction between particle numbers p1 and p2 of superparticles of type spt, using element interaction from network.library[]. It returns whether the given superparticletype and interaction exist and the particle numbers do not already have an interaction. If the two particle numbers already have an interaction, it is not modified.
Definition at line 300 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(p1,p2);
    if(spt>=network.sptypes.size())
    {
        WARNING("superparticletype %d does not exist", spt);
        return false;
    }
    else if(network.sptypes[spt].splookup.count(id))
        return false;
    else if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    {
        network.sptypes[spt].splookup[id]=interaction;
        avars.reindex=true;
        return true;
    }
}
References WARNING.
add_sp_interaction() [2/3]
template<ui dim>
bool md< dim >::add_sp_interaction (ui spt, ui p1, ui p2, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Add superparticle interaction rule.
This function adds an interaction between particle numbers p1 and p2 of superparticles of type spt, using a new interaction of the given type and with the given parameters. It returns whether the given superparticletype exists and the particle numbers do not already have an interaction. If the two particle numbers already have an interaction, it is not modified and the interaction is not added to network.library[].
Definition at line 398 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(p1,p2);
    if(spt>=network.sptypes.size())
    {
        WARNING("superparticletype %d does not exist", spt);
        return false;
    }
    else if(network.sptypes[spt].splookup.count(id))
        return false;
    else
    {
        network.sptypes[spt].splookup[id] = add_interaction(potential,rco,parameters);
        avars.reindex=true;
        return true;
    }
}
References WARNING.
add_sp_interaction() [3/3]
template<ui dim>
bool md< dim >::add_sp_interaction (ui spt, ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Add superparticle interaction rule.
This function adds an interaction between particle numbers p1 and p2 of superparticles of type spt, using a new interaction of the given type and with the given parameters. It returns whether the given superparticletype exists and the particle numbers do not already have an interaction. If the two particle numbers already have an interaction, it is not modified and the interaction is not added to network.library[].
Definition at line 386 of file interaction.md.libmd.cc.
{
    return add_sp_interaction(spt,p1,p2,potential,network.rco,parameters);
}
add_spring()
template<ui dim>
void md< dim >::add_spring (ui p1, ui p2, ldf springconstant, ldf l0) [inherited]
Add a harmonic bond to the system.
Create a hookean spring [potential type HOOKEAN()] between p1 and p2, with spring constant and rest length prescribed by the third and fourth arguments respectively.
Definition at line 248 of file bonds.md.libmd.cc.
{
    /* add a spring between two points with specified springconstant and equilibrium length */
    std::vector<ldf> params = {springconstant, l0};
    add_bond(p1,p2,POT::HOOKEAN,params);
}
References POT::HOOKEAN.
add_sptype()
template<ui dim>
ui md< dim >::add_sptype [inherited]
Add superparticletype.
This function adds an empty superparticletype to network.sptypes[] and returns its index.
Definition at line 268 of file interaction.md.libmd.cc.
{
    network.sptypes.push_back(superparticletype());
    return network.sptypes.size()-1;
}
add_typeinteraction() [1/3]
template<ui dim>
bool md< dim >::add_typeinteraction (ui type1, ui type2, ui interaction) [inherited]
Add type interaction rule.
This function adds a type interaction between the given types, using element interaction from network.library[]. It returns whether the given interaction exists and the two types do not already have an interaction. If the two types already have an interaction, it is not modified.
Definition at line 116 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(type1,type2);
    if(network.lookup.count(id))
        return false;
    else if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    {
        network.lookup[id]=interaction;
        avars.reindex=true;
        return true;
    }
}
References WARNING.
add_typeinteraction() [2/3]
template<ui dim>
bool md< dim >::add_typeinteraction (ui type1, ui type2, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Add type interaction rule.
This function adds a type interaction between the given types, using a new interaction of the given type and with the given parameters. It returns whether the two types do not already have an interaction. If the two types already have an interaction, it is not modified and the interaction is not added to network.library[].
Definition at line 192 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(type1,type2);
    if(!network.lookup.count(id))
    {
        network.lookup[id]=add_interaction(potential,rco,parameters);
        avars.reindex=true;
        return true;
    }
    else return false;
}
add_typeinteraction() [3/3]
template<ui dim>
bool md< dim >::add_typeinteraction (ui type1, ui type2, ui potential, std::vector< ldf > & parameters) [inherited]
Add type interaction rule.
This function adds a type interaction between the given types, using a new interaction of the given type and with the given parameters. It returns whether the two types do not already have an interaction. If the two types already have an interaction, it is not modified and the interaction is not added to network.library[].
Definition at line 182 of file interaction.md.libmd.cc.
{
    return add_typeinteraction(type1,type2,potential,network.rco,parameters);
}
all_interactions()
template<ui dim>
void md< dim >::all_interactions (std::vector< std::pair< ui, ui >> & table) [inherited]
Dump all interaction into a table.
This function puts a list of all interaction neighbors in table, as pairs of particles.
Definition at line 16 of file interaction.md.libmd.cc.
{
    table.clear();
    for(ui i=0;i<N;i++) for(auto sij: network.skins[i]) if(i>sij.neighbor and distsq(i,sij.neighbor)<std::pow(get_rco(sij.interaction),2)) table.push_back(std::pair<ui,ui>(i,sij.neighbor));
}
References pow().
assign_all_forcetype()
template<ui dim>
void md< dim >::assign_all_forcetype (ui ftype) [inherited]
Assign force type to all particles.
This function assigns the forcetype network.forcelibrary[ftype] to all particles.
Definition at line 602 of file interaction.md.libmd.cc.
{
    for(ui i=0;i<N;i++) assign_forcetype(i,ftype);
}
assign_forcetype()
template<ui dim>
bool md< dim >::assign_forcetype (ui i, ui ftype) [inherited]
Assign force type to particle.
This function assigns a forcetype to particle i, using element ftype from network.forcelibrary[]. It returns whether the given forcetype was not already assigned to the given particle.
Definition at line 591 of file interaction.md.libmd.cc.
{
    for(ui j=network.forces[i].size()-1;j<UI_MAX;j--) if(network.forces[i][j]==ftype) return false;
    network.forces[i].push_back(ftype);
    return true;
}
References UI_MAX.
assign_unique_types()
template<ui dim>
void md< dim >::assign_unique_types (ui p1, ui p2) [inherited]
Assign unique types to particles, modify lookup.
Assign unique particle types to p1 and p2, that are not shared by any other particles. Preserves all pairwise interactions that existed between p1 or p2 and any other particles.
Definition at line 200 of file bonds.md.libmd.cc.
{
    // assign unique types to points
    ui P[2], old_type[2], new_type[2];
    P[0] = p1;
    P[1] = p2;
    ui maxtype = network.lookup.empty() ? 0 : network.lookup.rbegin()->first.first, i, j, q;
    for (j = 0; j < 2; j++)
        new_type[j] = old_type[j] = particles[P[j]].type;
    for (i = 0; i < N; i++)
        if (maxtype < particles[i].type)
            maxtype = particles[i].type;
    for (j = 0; j < 2; j++)
    {
        for (i = 0; i < N && (i == P[j] || particles[i].type != old_type[j]); i++); // Check if there is at least one other particle with same type as p1
        if (i < N) // P[j] does not have a unique type; reassign.
            set_type(P[j], new_type[j] = ++maxtype); // use one greater than largest used particle type
        if (old_type[0] == old_type[1])
        { set_type(P[1], new_type[1] = new_type[0]);
            break;
        }
    }
    for (j = 0; j < 2; j++)
        if (new_type[j] != old_type[j])
        { // clone previously defined interactions
            std::map<std::pair<ui,ui>,ui>::iterator it = (old_type[j]==0 ? network.lookup.begin() : network.lookup.upper_bound(std::pair<ui,ui>(old_type[j]-1, UI_MAX)));
            for (; it != network.lookup.end() && it->first.first == old_type[j]; it++)
                if ((q = it->first.second) != new_type[1-j])
                    mad_typeinteraction(new_type[j], q, it->second);
            for (; it != network.lookup.end(); it++)
                if (it->first.second == old_type[j] && (q = it->first.first) != new_type[1-j])
                    mad_typeinteraction(new_type[j], q, it->second);
            if (old_type[0] == old_type[1])
                break;
        }
}
References UI_MAX.
bruteforce()
template<ui dim>
void md< dim >::bruteforce [inherited]
Bruteforce indexing algorithm.
This brute force indexing algorithm simply checks every pair of particles.
 This function is to be preferred over md<dim>::cell() and md<dim>::kdtree() if all (or most) particles are within network.ssz of each other.
Definition at line 369 of file index.md.libmd.cc.
{
    DEBUG_2("exec is here");
    for(ui i=0;i<N;i++) network.skins[i].clear();
    ldf sszsq=std::pow(network.ssz,2);
    for(ui i=0;i<N;i++) for(ui j=i+1;j<N;j++) skinner(i, j, sszsq);
}
References DEBUG_2, and pow().
calc_forces()
template<ui dim>
void mpmd< dim >::calc_forces [final], [override], [virtual]
Integrate particle trajectoriess.
This function clears all the forces and then calls mpmd<dim>::mp_thread_calc_forces(ui i) for all particles.
Reimplemented from md< dim >.
Definition at line 203 of file mpmd.libmd.cc.
{
    if(network.update and (avars.reindex or test_index()))
    {
        DEBUG_2("regenerating skinlist");
        index();
    }
    DEBUG_2("exec is here");
    avars.export_force_calc=false;
    for(ui i=0;i<N;i++) thread_clear_forces(i);
    recalc_forces();
}
References DEBUG_2.
calc_geometry()
template<ui dim>
void mpmd< dim >::calc_geometry
Calculate Monge patch derivatives.
This function calls mpmd<dim>::thread_calc_geometry(ui i) for all particles.
Definition at line 170 of file mpmd.libmd.cc.
{
    for(ui i=0;i<N;i++) thread_calc_geometry(i);
}
cell()
template<ui dim>
void md< dim >::cell [inherited]
Cell indexing algorithm.
This indexing algorithm uses the cell method.
 The system is divided into cells of equal size, which are at least network.ssz in size in each dimension. The particles are put in their corresponding cells. Two particles that are in cells that do not share at least a corner will be more than network.ssz apart, therefore such pairs of cells need not be checked.
Definition at line 265 of file index.md.libmd.cc.
{
    DEBUG_2("exec is here");
    if (network.ssz <= 0)
    { ERROR("skinsize is not positive (network.ssz = " F_LDF ")", network.ssz);
        return;
    }
    ui c, d, i, k, cellId;
    ldf x;
    std::list<ui>::iterator a, b;
    ldf nc = 1;
    if (simbox.useLshear)
    { ldf R;
        for (d = 0; d < dim; d++)
        { R = std::pow(dotprod<dim>(simbox.LshearInv[d], simbox.LshearInv[d]), -.5);
            nc *= indexdata.celldata.Q[d] = (R < network.ssz ? 1 : R/network.ssz);
        }
    }
    else
        for (d = 0; d < dim; d++)
            nc *= indexdata.celldata.Q[d] = (simbox.L[d] < network.ssz ? 1 : simbox.L[d]/network.ssz);
    // If number of cells is very large (ssz very small): reduce until number of cells is in the order of N
    for (; nc > N; nc /= 2)
    {
        k = 0;
        for (d = 1; d < dim; d++)
            if (indexdata.celldata.Q[k] < indexdata.celldata.Q[d])
                k = d;
        indexdata.celldata.Q[k] = (indexdata.celldata.Q[k]+1)/2;
    }
    for (d = 0; d < dim; d++)
        DEBUG_3("indexdata.celldata.Q[" F_UI "] = " F_UI " (from " F_LDF " / " F_LDF " originally)", d, indexdata.celldata.Q[d], simbox.L[d], network.ssz);
    // Compute and check cell sizes
    for (d = 0; d < dim; d++)
        indexdata.celldata.CellSize[d] = simbox.L[d]/indexdata.celldata.Q[d];
    // Compute nCells and totNeighbors
    indexdata.celldata.nCells = 1;
    indexdata.celldata.totNeighbors = 0;
    for (d = 0; d < dim; d++)
        if (indexdata.celldata.Q[d] > 1) // Ignore dimensions with only one cell
        { indexdata.celldata.nCells *= indexdata.celldata.Q[d];
            indexdata.celldata.totNeighbors = 3*indexdata.celldata.totNeighbors+1;
        }
    // Declare dynamic arrays
    if (indexdata.celldata.IndexDelta == nullptr || sizeof(indexdata.celldata.Cells) != indexdata.celldata.nCells*sizeof(ui)
        || sizeof(indexdata.celldata.IndexDelta) != indexdata.celldata.totNeighbors*dim*sizeof(int)
        || sizeof(indexdata.celldata.OutsideBox) != N)
    { delete[] indexdata.celldata.Cells;
        delete[] indexdata.celldata.IndexDelta;
        delete[] indexdata.celldata.OutsideBox;
        indexdata.celldata.Cells = new std::vector<ui>[indexdata.celldata.nCells];
        indexdata.celldata.IndexDelta = new int[indexdata.celldata.totNeighbors][dim]; // Relative position of neighboring cell
        indexdata.celldata.OutsideBox = new bool[N];
    }
    // Determine all (potential) neighbors
    // Start with {0,0,...,0,+1}
    if (indexdata.celldata.totNeighbors > 0)
    { memset(indexdata.celldata.IndexDelta[0], 0, dim*sizeof(ui));
        for (d = dim-1; indexdata.celldata.Q[d] == 1; d--);
        indexdata.celldata.IndexDelta[0][d] = 1;
        for (i = 1; i < indexdata.celldata.totNeighbors; i++)
        { memcpy(indexdata.celldata.IndexDelta[i], indexdata.celldata.IndexDelta[i-1], dim*sizeof(ui));
            // Set all trailing +1's to -1
            for (d = dim-1; d < dim && (indexdata.celldata.Q[d] == 1 || indexdata.celldata.IndexDelta[i][d] == 1); d--)
                if (indexdata.celldata.Q[d] > 1)
                    indexdata.celldata.IndexDelta[i][d] = -1;
            // Increase last not-plus-one by one
            if (d < dim)
                indexdata.celldata.IndexDelta[i][d]++;
        }
    }
    // Put the particles in their cells
    for (c = 0; c < indexdata.celldata.nCells; c++)
        indexdata.celldata.Cells[c].clear();
    for (i = 0; i < N; i++)
    { cellId = 0;
        indexdata.celldata.OutsideBox[i] = false;
        for (d = 0; d < dim; d++)
        { x = (simbox.useLshear ? dotprod<dim>(simbox.LshearInv[d], particles[i].x) : particles[i].x[d] / simbox.L[d]);
            if (std::abs(x) > .5+1e-9)
            { indexdata.celldata.OutsideBox[i] = true;
                cellId = indexdata.celldata.Q[d] * cellId + (x < 0 ? 0 : indexdata.celldata.Q[d]-1);
            }
            else
                cellId = indexdata.celldata.Q[d] * cellId + (x < -.5+3e-9 ? 0 : (ui)(indexdata.celldata.Q[d]*(x+.5-2e-9)));
        }
        indexdata.celldata.Cells[cellId].push_back(i);
    }
    for (i = 0; i < N; i++)
        network.skins[i].clear();
    for(ui c=0;c<indexdata.celldata.nCells;c++) thread_cell(c);
}
References abs(), DEBUG_2, DEBUG_3, ERROR, F_LDF, F_UI, and pow().
clear()
template<ui dim>
void md< dim >::clear [inherited]
Clear all particles and interactions.
Remove all particles from the md structure, and clear all data types storing interactions and superparticle data. Leaves the system box and the boundary conditions unchanged.
Definition at line 50 of file md.libmd.cc.
{
    N=0;
    particles.clear();
    network.skins.clear();
    network.library.clear();
    network.lookup.clear();
    network.spid.clear();
    network.superparticles.clear();
    network.sptypes.clear();
    network.forcelibrary.clear();
    network.forces.clear();
    network.free_library_slots.clear();
}
clear_all_assigned_forcetype()
template<ui dim>
void md< dim >::clear_all_assigned_forcetype [inherited]
Clear all assigned forces.
This function removes all forcetypes from all particles.
Definition at line 633 of file interaction.md.libmd.cc.
{
    for(ui i=0;i<N;i++) network.forces[i].clear();
}
clone_particle()
template<ui dim>
ui md< dim >::clone_particle (ui i, ldf x[dim]) [inherited]
Clone a particle and translate.
This function creates a new particle that is a copy of particle i. The position of the new particle is translated by the vector x[] with respect to the original one. It returns the index of the new particle.
Definition at line 156 of file particles.md.libmd.cc.
{
    DEBUG_2("cloning particle #" F_UI "",i);
    ui retval=add_particle();
    particles[retval]=particles[i];
    translate_particle(retval,x);
    network.forces[retval]=network.forces[i];
    for(auto j:network.forces[i]) if(!network.forcelibrary[j].particles.empty()) network.forcelibrary[j].particles[retval]=network.forcelibrary[j].particles[i];
    for(auto f:network.forcelibrary) for(auto u:f.particles) for(auto v:u) if(v==i) u.push_back(retval);
    return retval;
}
References DEBUG_2, and F_UI.
clone_sp()
template<ui dim>
ui md< dim >::clone_sp (ui spi, ldf x[dim]) [inherited]
Clone a superparticle and translate.
This function creates a new superparticle that is a copy of the superparticle with index spi, with new particles. The position of all the new particles are translated by the vector x[] with respect to the original ones. It returns the index of the new superparticle in network.superparticles[].
Definition at line 198 of file sp.md.libmd.cc.
{
    DEBUG_2("cloning superparticle #" F_UI "",spi);
    ui retval=add_sp(network.superparticles[spi].sptype);
    network.superparticles[retval].backdoor=network.superparticles[spi].backdoor;
    ui K=network.superparticles[spi].backdoor.size(),i;
    for(ui k=0;k<K;k++)
    {
        if((i=network.superparticles[spi].backdoor[k])<UI_MAX)
        {
            ui p=clone_particle(i,x);
            network.spid[p]=retval;
            network.superparticles[retval].particles[p]=k;
            network.superparticles[retval].backdoor[k]=p;
        }
    }
    for(auto f:network.forcelibrary) for(auto u:f.particles) for(auto &v:u) if(network.spid[v]==spi) v=network.superparticles[retval].backdoor[network.superparticles[spi].particles[v]];
    return retval;
}
References DEBUG_2, F_UI, and UI_MAX.
clone_sptype()
template<ui dim>
ui md< dim >::clone_sptype (ui sp) [inherited]
Make a new sptype for superparticle sp if it is not unique to sp.
This function creates a new superparticle type that is exactly the same as that of superparticle spi, assigns it to the superparticle and returns its index in network.sptypes[]. If superparticle spi is the only superparticle of its type, this fuction does nothing and returns the index of its type in network.sptypes[].
Definition at line 382 of file bonds.md.libmd.cc.
{
    ui i, spt = network.superparticles[spi].sptype;
    // Check for uniqueness
    for (i = network.superparticles.size()-1; i < UI_MAX && (i == spi || network.superparticles[i].sptype != spt); i--);
    if (i < UI_MAX)
    { network.sptypes.push_back(network.sptypes[spt]);
        return network.superparticles[spi].sptype = network.sptypes.size()-1;
    }
    else
        return spt;
}
References UI_MAX.
dap()
template<ui dim>
ldf md< dim >::dap (ui d, ldf ad) [inherited]
Manipulate particle distances with respect to periodic boundary conditions.
Given a displacement ad and corresponding spatial dimension d, calculates the displacement modulo the periodic box size in that dimension.
Under periodic boundary conditions, distances are required to lie in the range (-simbox.L[d]/2,simbox.L[d]/2). If the displacement dap is outside this range, multiples of simbox.L[d] are added or subtracted until the displacement is within these bounds, and the result is returned.
Definition at line 6 of file distances.md.libmd.cc.
{
    ldf da;
    switch(simbox.bcond[d])
    {
        case BCOND::PERIODIC: da=std::abs(ad)<0.5*simbox.L[d]?ad:ad-std::abs(ad+0.5*simbox.L[d])+std::abs(ad-0.5*simbox.L[d]); break;
        default: da=ad; break;
    }
    return da;
}
References abs(), and BCOND::PERIODIC.
dd() [1/4]
template<ui dim>
ldf md< dim >::dd (ui d, ldf x1[dim], ldf x2[dim]) [inherited]
Calculate difference in particle positions in certain dimension i by particle index.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This version accepts as inputs the coordinates of two points in arrays x1[dim] and x2[dim] and returns the (periodic) distance between them along spatial dimension d.
Definition at line 91 of file distances.md.libmd.cc.
{
    ldf ddd=0;
    if (simbox.useLshear) for(ui mu=0;mu<dim;mu++) // use box matrix to calculate distances
    {
       ldf s=0;
       for(ui nu=0;nu<dim;nu++) s+=simbox.LshearInv[mu][nu]*(x2[nu]-x1[nu]);
       if (simbox.bcond[mu]==BCOND::PERIODIC or simbox.bcond[mu]==BCOND::BOXSHEAR) s=std::abs(s)<0.5?s:s-std::abs(s+0.5)+std::abs(s-0.5);
       ddd += simbox.Lshear[d][mu]*s;
    }
    else
    {
        ldf ad=x2[d]-x1[d];
        ddd=dap(d,ad);
    }
    return ddd;
}
References abs(), BCOND::BOXSHEAR, and BCOND::PERIODIC.
dd() [2/4]
template<ui dim>
ldf md< dim >::dd (ui d, ldf x1[dim], ui p2) [inherited]
Calculate difference in particle positions in certain dimension i by particle index.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This version accepts as inputs a point coordinate array x1[dim] and a point index p2 and returns the (periodic) distance between them along spatial dimension d.
Definition at line 126 of file distances.md.libmd.cc.
{
    return dd(d,x1,particles[p2].x);
}
dd() [3/4]
template<ui dim>
ldf md< dim >::dd (ui d, ui p1, ldf x2[dim]) [inherited]
Calculate difference in particle positions in certain dimension i by particle index.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This version accepts as inputs a point index p1 and point coordinate array x2[dim] and returns the (periodic) distance between them along spatial dimension d.
Definition at line 115 of file distances.md.libmd.cc.
{
    return dd(d,particles[p1].x,x2);
}
dd() [4/4]
template<ui dim>
ldf md< dim >::dd (ui d, ui p1, ui p2) [inherited]
Calculate difference in particle positions in certain dimension i by particle index.
Returns the distance between points indexed by p1 and p2 along spatial dimension d. If periodic boundary conditions are used, the distance is between the closest periodic images of the two points.
Definition at line 79 of file distances.md.libmd.cc.
{
    return dd(d,particles[p1].x,particles[p2].x);
}
direct_readout() [1/2]
template<ui dim>
ldf md< dim >::direct_readout (ui d, ui i, uc type) [inherited]
Directly readout a position'x'/velocity'v'/forces'F'.
This function is convenience function for type:
type='v' md<dim>::direct_readout_dx (d,i)
type='F' md<dim>::direct_readout_dx (d,i)
default md<dim>::direct_readout_dx (d,i)
Definition at line 345 of file importexport.md.libmd.cc.
{
    switch(type)
    {
        case 'v': return direct_readout_dx(d,i); break;
        case 'F': return direct_readout_F(d,i); break;
        default: return direct_readout_x(d,i); break;
    }
}
direct_readout() [2/2]
template<ui dim>
ldf md< dim >::direct_readout (ui i, uc type) [inherited]
Directly readout a position'x'/velocity'v'/forces'F'.
This function is convenience function for type:
type='v' md<dim>::direct_readout_dx (d=vvars,i)
type='F' md<dim>::direct_readout_dx (d=vvars,i)
default md<dim>::direct_readout_dx (d=vvars,i)
vvars is variadic_var
Definition at line 325 of file importexport.md.libmd.cc.
{
    ui d=vvars[6];
    switch(type)
    {
        case 'v': return direct_readout_dx(d,i); break;
        case 'F': return direct_readout_F(d,i); break;
        default: return direct_readout_x(d,i); break;
    }
}
direct_readout_dx()
template<ui dim>
ldf md< dim >::direct_readout_dx (ui d, ui i) [inherited]
Directly readout a velocity.
This function is a somewhat redundant function that returns particles[i].dx[d].
Definition at line 308 of file importexport.md.libmd.cc.
{
    return particles[i].dx[d];
}
direct_readout_F()
template<ui dim>
ldf md< dim >::direct_readout_F (ui d, ui i) [inherited]
Directly readout a forces.
This function returns particles[i].F[d] after it checks if a Force calculation is necessary.
Definition at line 316 of file importexport.md.libmd.cc.
{
    if(avars.export_force_calc) calc_forces();
    return particles[i].F[d];
}
direct_readout_x()
template<ui dim>
ldf md< dim >::direct_readout_x (ui d, ui i) [inherited]
Directly readout a position.
This function is a somewhat redundant function that returns particles[i].x[d].
Definition at line 300 of file importexport.md.libmd.cc.
{
    return particles[i].x[d];
}
distsq() [1/4]
template<ui dim>
ldf md< dim >::distsq (ldf x1[dim], ldf x2[dim]) [inherited]
Calculate distances between two particles (squared) ldf distsq(ui p1,ldf x2[dim]); ///< Calculate distances between two particles (squared)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This version accepts as inputs the coordinates of two points in arrays x1[dim] and x2[dim] and returns the squared (periodic) distance between them.
Definition at line 40 of file distances.md.libmd.cc.
{
    ldf retval=0.0;
    for(ui d=0;d<dim;d++) retval+=std::pow(dd(d,x1,x2),2);
    return retval;
}
References pow().
distsq() [2/4]
template<ui dim>
ldf md< dim >::distsq (ldf x1[dim], ui p2) [inherited]
Calculate distances between two particles (squared)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This version accepts as inputs a point coordinate array x1[dim] and a point index p2 and returns the squared (periodic) distance between them.
Definition at line 66 of file distances.md.libmd.cc.
{
    ldf retval=0.0;
    for(ui d=0;d<dim;d++) retval+=std::pow(dd(d,x1,p2),2);
    return retval;
}
References pow().
distsq() [3/4]
template<ui dim>
ldf md< dim >::distsq (ui p1, ldf x2[dim]) [inherited]
Calculate distances between two particles (squared)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This version accepts as inputs a point index p1 and point coordinate array x2[dim] and returns the squared (periodic) distance between them.
Definition at line 53 of file distances.md.libmd.cc.
{
    ldf retval=0.0;
    for(ui d=0;d<dim;d++) retval+=std::pow(dd(d,p1,x2),2);
    return retval;
}
References pow().
distsq() [4/4]
template<ui dim>
ldf md< dim >::distsq (ui p1, ui p2) [inherited]
Calculate distances between two particles (squared)
Returns the square of the distance between points indexed by p1 and p2. If periodic boundary conditions are used, the distance is between the closest periodic images of the two points.
Definition at line 26 of file distances.md.libmd.cc.
{
    ldf retval=0.0;
    for(ui d=0;d<dim;d++) retval+=std::pow(dd(d,p1,p2),2);
    return retval;
}
References pow().
drift_particle()
template<ui dim>
void md< dim >::drift_particle (ui i, ldf dx[dim]) [inherited]
Add velocity to a particle.
This function adds the vector dx[] to the velocity of particle i.
Definition at line 189 of file particles.md.libmd.cc.
{
    DEBUG_2("drifting particle #" F_UI "",i);
    for(ui d=0;d<dim;d++) particles[i].dx[d]+=dx[d];
}
References DEBUG_2, and F_UI.
drift_sp()
template<ui dim>
void md< dim >::drift_sp (ui spi, ldf dx[dim]) [inherited]
Add velocity to a super particle (all particles the same)
This function adds the vector dx[] to the velocities all particles belonging to the superparticle with index spi.
Definition at line 232 of file sp.md.libmd.cc.
{
    DEBUG_2("drifting superparticle #" F_UI "",spi);
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++) drift_particle(it->first,dx);
}
References DEBUG_2, and F_UI.
dv()
template<ui dim>
ldf md< dim >::dv (ui d, ui p1, ui p2) [inherited]
Calculate difference in particle velocities in certain dimension i by particle index.
Returns the dth component of the velocity difference between the closest periodic image of two particles indexed by p1 and p2. If the vector connecting the periodic images crosses a sheared boundary, the resulting velocity difference takes into account the shear velocity of the periodic image as well. The result is returned as a $d$-dimensional array of velocity components.
Definition at line 137 of file distances.md.libmd.cc.
{
    ldf dv = particles[p2].dx[d]-particles[p1].dx[d];
    if (simbox.useLshear)
    {
        // use box matrix to calculate boundary crossings, and adjust relative velocity accordingly
        for (ui j=0;j<dim;j++)
        {
            ldf s=0,bcross=0;
            for (ui k=0;k<dim;k++)
            {
               s+=simbox.LshearInv[j][k]*(particles[p2].x[k]-particles[p1].x[k]);
            }
            if (std::abs(s) > 0.5 and (simbox.bcond[j]==BCOND::PERIODIC or simbox.bcond[j]==BCOND::BOXSHEAR)) bcross = floor(s+.5);
            dv -= simbox.vshear[d][j]*bcross;
        }
    }
    return dv;
}
References abs(), BCOND::BOXSHEAR, and BCOND::PERIODIC.
embedded_dd_p1()
template<ui dim>
ldf mpmd< dim >::embedded_dd_p1 (ui d, ui p1, ui p2)
Calculate particles relative particle in certain dimension i wrt p1.
This function calculates the d'th component of the embedded distance vector with respect to particle p1.
 Note this function is signed hence permutations matter.
Definition at line 38 of file mpmd.libmd.cc.
{
    return dd(d,p1,p2)+((patch.geometryx[p2].x-patch.geometryx[p1].x)*patch.geometryx[p1].dx[d]);
}
embedded_dd_p2()
template<ui dim>
ldf mpmd< dim >::embedded_dd_p2 (ui d, ui p1, ui p2)
Calculate particles relative particle in certain dimension i wrt p2.
This function calculates the d'th component of the embedded distance vector with respect to particle p2.
 Note this function is signed hence permutations matter.
Definition at line 47 of file mpmd.libmd.cc.
{
    return dd(d,p2,p1)+((patch.geometryx[p1].x-patch.geometryx[p2].x)*patch.geometryx[p2].dx[d]);
}
embedded_distsq() [1/4]
template<ui dim>
ldf mpmd< dim >::embedded_distsq (ldf x1[dim], ldf x2[dim])
Calculate distances between two particles (squared)
This function calculates the embedded distance squared between coordinates x1 and x2.
Definition at line 14 of file mpmd.libmd.cc.
{
    return distsq(x1,x2)+std::pow(patch.f(x2).x-patch.f(x1),2);
}
References pow().
embedded_distsq() [2/4]
template<ui dim>
ldf mpmd< dim >::embedded_distsq (ldf x2[dim], ui p2)
Calculate distances between two particles (squared)
This function calculates the embedded distance squared between particle p1 and coordinate x2.
Definition at line 30 of file mpmd.libmd.cc.
{
    return distsq(x1,p2)+std::pow(patch.geometryx[p2].x-patch.f(x1),2);
}
References pow().
embedded_distsq() [3/4]
template<ui dim>
ldf mpmd< dim >::embedded_distsq (ui p1, ldf x2[dim])
Calculate distances between two particles (squared)
This function calculates the embedded distance squared between coordinate x1 and particle p2.
Definition at line 22 of file mpmd.libmd.cc.
{
    return distsq(p1,x2)+std::pow(patch.f(x2)-patch.geometryx[p1].x,2);
}
References pow().
embedded_distsq() [4/4]
template<ui dim>
ldf mpmd< dim >::embedded_distsq (ui p1, ui p2)
Calculate distances between two particles (squared)
This function calculates the embedded distance squared between particles p1 and p2.
Definition at line 6 of file mpmd.libmd.cc.
{
    return distsq(p1,p2)+std::pow(patch.geometryx[p2].x-patch.geometryx[p1].x,2);
}
References pow().
export_force() [1/4]
template<ui dim>
void md< dim >::export_force (ldf * F) [inherited]
Save forces from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Then for each ith particle force every dth component is assigned to that array
 As d is a variadic variable it is stored and increased for every array. This function checks if forces need to be recalculated
Definition at line 246 of file importexport.md.libmd.cc.
{
    ui d=vvars[5];
    if(avars.export_force_calc) calc_forces();
    for(ui i=0;i<N;i++) F[i]=particles[i].F[d];
}
export_force() [2/4]
template<ui dim>
template<typename... arg>
void md< dim >::export_force (ldf * F, arg... argv) [inherited]
Save forces to arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Then for each ith particle force every dth component is assigned to that array
 As d is a variadic variable it is stored and increased for every array. This function checks if forces need to be recalculated
Definition at line 260 of file importexport.md.libmd.cc.
{
    ui d=vvars[5];
    if(avars.export_force_calc) calc_forces();
    for(ui i=0;i<N;i++) F[i]=particles[i].F[d];
    export_force(argv...);
}
export_force() [3/4]
template<ui dim>
void md< dim >::export_force (ui i, ldf & F) [inherited]
Save forces from arrays.
This function takes an arbitrary number of values.
 Then for each ith particle force every dth component is assigned to that value
 As d is a variadic variable it is stored and increased for every array.
Definition at line 275 of file importexport.md.libmd.cc.
{
    ui d=vvars[5];
    if(avars.export_force_calc) calc_forces();
    F=particles[i].F[d];
}
export_force() [4/4]
template<ui dim>
template<typename... arg>
void md< dim >::export_force (ui i, ldf & F, arg... argv) [inherited]
Save forces to arrays.
This function takes an arbitrary number of values.
 Then for each ith particle force every dth component is assigned to that value
 As d is a variadic variable it is stored and increased for every array.
Definition at line 287 of file importexport.md.libmd.cc.
{
    ui d=vvars[5];
    if(avars.export_force_calc) calc_forces();
    F=particles[i].F[d];
    export_force(i,argv...);
}
export_pos() [1/4]
template<ui dim>
void md< dim >::export_pos (ldf * x) [inherited]
Save positions from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Then for each ith particle position every dth component is assigned to that array
 As d is a variadic variable it is stored and increased for every array.
Definition at line 150 of file importexport.md.libmd.cc.
{
    ui d=vvars[3];
    for(ui i=0;i<N;i++) x[i]=particles[i].x[d];
}
export_pos() [2/4]
template<ui dim>
template<typename... arg>
void md< dim >::export_pos (ldf * x, arg... argv) [inherited]
Save positions to arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Then for each ith particle position every dth component is assigned to that array
 As d is a variadic variable it is stored and increased for every array.
Definition at line 162 of file importexport.md.libmd.cc.
{
    ui d=vvars[3];
    for(ui i=0;i<N;i++) x[i]=particles[i].x[d];
    export_pos(argv...);
}
export_pos() [3/4]
template<ui dim>
void md< dim >::export_pos (ui i, ldf & x) [inherited]
Save positions from arrays.
This function takes an arbitrary number of values.
 Then for each ith particle position every dth component is assigned to that value
 As d is a variadic variable it is stored and increased for every array.
Definition at line 175 of file importexport.md.libmd.cc.
{
    ui d=vvars[3];
    x=particles[i].x[d];
}
export_pos() [4/4]
template<ui dim>
template<typename... arg>
void md< dim >::export_pos (ui i, ldf & x, arg... argv) [inherited]
Save positions to arrays.
This function takes an arbitrary number of values.
 Then for each ith particle position every dth component is assigned to that value
 As d is a variadic variable it is stored and increased for every array.
Definition at line 186 of file importexport.md.libmd.cc.
{
    ui d=vvars[3];
    x=particles[i].x[d];
    export_pos(i,argv...);
}
export_vel() [1/4]
template<ui dim>
void md< dim >::export_vel (ldf * dx) [inherited]
Save velocity from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Then for each ith particle velocity every dth component is assigned to that array
 As d is a variadic variable it is stored and increased for every array.
Definition at line 198 of file importexport.md.libmd.cc.
{
    ui d=vvars[4];
    for(ui i=0;i<N;i++) dx[i]=particles[i].dx[d];
}
export_vel() [2/4]
template<ui dim>
template<typename... arg>
void md< dim >::export_vel (ldf * dx, arg... argv) [inherited]
Save velocity to arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Then for each ith particle velocity every dth component is assigned to that array
 As d is a variadic variable it is stored and increased for every array.
Definition at line 210 of file importexport.md.libmd.cc.
{
    ui d=vvars[4];
    for(ui i=0;i<N;i++) dx[i]=particles[i].dx[d];
    export_vel(argv...);
}
export_vel() [3/4]
template<ui dim>
void md< dim >::export_vel (ui i, ldf & dx) [inherited]
Save positions from arrays.
This function takes an arbitrary number of values.
 Then for each ith particle velocity every dth component is assigned to that value
 As d is a variadic variable it is stored and increased for every array.
Definition at line 223 of file importexport.md.libmd.cc.
{
    ui d=vvars[4];
    dx=particles[i].dx[d];
}
export_vel() [4/4]
template<ui dim>
template<typename... arg>
void md< dim >::export_vel (ui i, ldf & dx, arg... argv) [inherited]
Save positions to arrays.
This function takes an arbitrary number of values.
 Then for each ith particle velocity every dth component is assigned to that value
 As d is a variadic variable it is stored and increased for every array.
Definition at line 234 of file importexport.md.libmd.cc.
{
    ui d=vvars[4];
    dx=particles[i].dx[d];
    export_vel(i,argv...);
}
fix_particle()
template<ui dim>
void md< dim >::fix_particle (ui i, bool fix) [inherited]
Fix a particle.
This function fixes (fix=true) or unfixes (fix=false) particle i
Definition at line 147 of file particles.md.libmd.cc.
{
    DEBUG_2("%sfixing particle #" F_UI "",fix?"":"un",i);
    particles[i].fix=fix;
}
References DEBUG_2, and F_UI.
fix_sp()
template<ui dim>
void md< dim >::fix_sp (ui spi, bool fix) [inherited]
Fix a super particles.
This function fixes (fix=true) or unfixes (fix=false) all the particles belonging to the superparticle with index spi.
Definition at line 188 of file sp.md.libmd.cc.
{
    DEBUG_2("%sfixing superparticle #" F_UI "",fix?"":"un",spi);
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++) particles[it->first].fix=fix;
}
References DEBUG_2, and F_UI.
get_position_sp()
template<ui dim>
void md< dim >::get_position_sp (ui spi, ldf x[dim]) [inherited]
Get center of mass of super particle.
This function puts the position of the center of mass of the superparticle with index spi in the vector x[].
Definition at line 272 of file sp.md.libmd.cc.
{
    DEBUG_2("calculating center of mass of superparticle #" F_UI "",spi);
    ldf m=0.0;
    memset(x,0,dim*sizeof(ldf));
    ui i=network.superparticles[spi].particles.begin()->first;
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++)
    {
        for(ui d=0;d<dim;d++) x[d]+=particles[it->first].m*dd(d,i,it->first);
        m+=particles[it->first].m;
    }
    for(ui d=0;d<dim;d++) x[d]=particles[i].x[d]+x[d]/m;
    thread_periodicity(x);
}
References DEBUG_2, and F_UI.
get_rco() [1/2]
template<ui dim>
ldf md< dim >::get_rco (ui i, ui j) [inherited]
Gets the cuttoff radius for a certain pair of particles.
This fucntion returns the $R_{\text{cutoff}}$ for an interacing pair of particles i and j
Definition at line 120 of file setget.md.libmd.cc.
{
    auto it=network.lookup.find(network.hash(particles[i].type,particles[j].type));
    if(it!=network.lookup.end()) return get_rco(it->second);
    else return std::numeric_limits<ldf>::quiet_NaN();
}
get_rco() [2/2]
template<ui dim>
ldf md< dim >::get_rco (ui interaction) [inherited]
Gets the cuttoff radius for a certain interaction.
This fucntion returns the $R_{\text{cutoff}}$ for a certain interaction
Definition at line 130 of file setget.md.libmd.cc.
{
    return network.library[interaction].rco;
}
get_velocity_sp()
template<ui dim>
void md< dim >::get_velocity_sp (ui spi, ldf dx[dim]) [inherited]
Get average velocity of a super particle.
This function puts the velocity of the center of mass of the superparticle with index spi in the vector dx[].
Definition at line 290 of file sp.md.libmd.cc.
{
    DEBUG_2("calculating velocity of center of mass of superparticle #" F_UI "",spi);
    ldf m=0.0;
    memset(dx,0,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) dx[d]=0.0;
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++)
    {
        for(ui d=0;d<dim;d++) dx[d]+=particles[it->first].m*particles[it->first].dx[d];
        m+=particles[it->first].m;
    }
    for(ui d=0;d<dim;d++) dx[d]/=m;
}
References DEBUG_2, and F_UI.
H()
template<ui dim>
ldf md< dim >::H [inherited]
Measure Hamiltonian.
Returns the total energy (kinetic and potential) of the system
Definition at line 45 of file energy.md.libmd.cc.
{
    return T()+V();
}
heat_particle()
template<ui dim>
void md< dim >::heat_particle (ui i, ldf lambda) [inherited]
Multiply velocity vector of a particle with a scalar.
This function increases the velocity of particle i by a factor of lambda.
Definition at line 198 of file particles.md.libmd.cc.
{
    DEBUG_2("heating particle #" F_UI "",i);
    for(ui d=0;d<dim;d++) particles[i].dx[d]*=lambda;
}
References DEBUG_2, and F_UI.
heat_sp()
template<ui dim>
void md< dim >::heat_sp (ui spi, ldf lambda) [inherited]
Multiply velocity vectors of a super particle with a scalar (all particles the same)
This function increases the velocity of all particles belonging to the superparticle with index spi by a factor of lambda.
Definition at line 241 of file sp.md.libmd.cc.
{
    DEBUG_2("heating superparticle #" F_UI "",spi);
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++) drift_particle(it->first,lambda);
}
References DEBUG_2, and F_UI.
history()
template<ui dim>
void mpmd< dim >::history
Set the history of all particles.
This function calls mpmd<dim>::thread_history(ui i) for all particles. Additionally, it calculates and updates the important geometric derivatives.
Definition at line 149 of file mpmd.libmd.cc.
{
    for(ui i=0;i<N;i++) thread_history(i);
    patch.geometryx.resize(N);
    patch.geometryxp.resize(N);
    for(ui i=0;i<N;i++) patch.calc(patch.geometryxp[i],particles[i].xp);
    for(ui i=0;i<N;i++) patch.calc(i,particles[i].x);
}
import_force() [1/4]
template<ui dim>
void md< dim >::import_force (ldf * F) [inherited]
Load forces from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Each ith element is then assigned to the particle the dth component of the particle's force
 As d is a variadic variable it is stored and increased for every array.
Definition at line 102 of file importexport.md.libmd.cc.
{
    ui d=vvars[2];
    for(ui i=0;i<N;i++) particles[i].F[d]=F[i];
}
import_force() [2/4]
template<ui dim>
template<typename... arg>
void md< dim >::import_force (ldf * F, arg... argv) [inherited]
Load forces from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Each ith element is then assigned to the particle the dth component of the particle's force
 As d is a variadic variable it is stored and increased for every array.
Definition at line 114 of file importexport.md.libmd.cc.
{
    ui d=vvars[2];
    for(ui i=0;i<N;i++) particles[i].F[d]=F[i];
    import_force(argv...);
}
import_force() [3/4]
template<ui dim>
void md< dim >::import_force (ui i, ldf F) [inherited]
Load position for i from value.
This function takes an arbitrary number of values.
 The values are then then assigned to the dth component of the ith particle's force
 As d is a variadic variable it is stored and increased for every value.
Definition at line 127 of file importexport.md.libmd.cc.
{
    ui d=vvars[2];
    particles[i].F[d]=F;
}
import_force() [4/4]
template<ui dim>
template<typename... arg>
void md< dim >::import_force (ui i, ldf F, arg... argv) [inherited]
Load position for i from value.
This function takes an arbitrary number of values.
 The values are then then assigned to the dth component of the ith particle's force
 As d is a variadic variable it is stored and increased for every value.
Definition at line 138 of file importexport.md.libmd.cc.
{
    ui d=vvars[2];
    particles[i].F[d]=F;
    import_force(i,argv...);
}
import_pos() [1/4]
template<ui dim>
void md< dim >::import_pos (ldf * x) [inherited]
Load positions from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Each ith element is then assigned to the particle the dth component of the particle's position
 As d is a variadic variable it is stored and increased for every array.
Definition at line 6 of file importexport.md.libmd.cc.
{
    ui d=vvars[0];
    for(ui i=0;i<N;i++) particles[i].x[d]=x[i];
}
import_pos() [2/4]
template<ui dim>
template<typename... arg>
void md< dim >::import_pos (ldf * x, arg... argv) [inherited]
Load positions from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Each ith element is then assigned to the particle the dth component of the particle's position
 As d is a variadic variable it is stored and increased for every array.
Definition at line 18 of file importexport.md.libmd.cc.
{
    ui d=vvars[0];
    for(ui i=0;i<N;i++) particles[i].x[d]=x[i];
    import_pos(argv...);
}
import_pos() [3/4]
template<ui dim>
void md< dim >::import_pos (ui i, ldf x) [inherited]
Load position for i from value.
This function takes an arbitrary number of values.
 The values are then then assigned to the dth component of the ith particle's position
 As d is a variadic variable it is stored and increased for every value.
Definition at line 31 of file importexport.md.libmd.cc.
{
    ui d=vvars[0];
    particles[i].x[d]=x;
}
import_pos() [4/4]
template<ui dim>
template<typename... arg>
void md< dim >::import_pos (ui i, ldf x, arg... argv) [inherited]
Load position for i from value.
This function takes an arbitrary number of values.
 The values are then then assigned to the dth component of the ith particle's position
 As d is a variadic variable it is stored and increased for every value.
Definition at line 42 of file importexport.md.libmd.cc.
{
    ui d=vvars[0];
    particles[i].x[d]=x;
    import_pos(i,argv...);
}
import_vel() [1/4]
template<ui dim>
void md< dim >::import_vel (ldf * dx) [inherited]
Load velocity from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Each ith element is then assigned to the particle the dth component of the particle's velocity
 As d is a variadic variable it is stored and increased for every array.
Definition at line 54 of file importexport.md.libmd.cc.
{
    ui d=vvars[1];
    for(ui i=0;i<N;i++) particles[i].dx[d]=dx[i];
}
import_vel() [2/4]
template<ui dim>
template<typename... arg>
void md< dim >::import_vel (ldf * dx, arg... argv) [inherited]
Load velocity from arrays.
This function takes an arbitrary number of arrays.
 The array is assumed to be of length N, the number of particles.
 Each ith element is then assigned to the particle the dth component of the particle's velocity
 As d is a variadic variable it is stored and increased for every array.
Definition at line 66 of file importexport.md.libmd.cc.
{
    ui d=vvars[1];
    for(ui i=0;i<N;i++) particles[i].dx[d]=dx[i];
    import_vel(argv...);
}
import_vel() [3/4]
template<ui dim>
void md< dim >::import_vel (ui i, ldf dx) [inherited]
Load velocity for i from value.
This function takes an arbitrary number of values.
 The values are then then assigned to the dth component of the ith particle's velocity
 As d is a variadic variable it is stored and increased for every value.
Definition at line 79 of file importexport.md.libmd.cc.
{
    ui d=vvars[1];
    particles[i].dx[d]=dx;
}
import_vel() [4/4]
template<ui dim>
template<typename... arg>
void md< dim >::import_vel (ui i, ldf dx, arg... argv) [inherited]
Load velocity for i from value.
This function takes an arbitrary number of values.
 The values are then then assigned to the dth component of the ith particle's velocity
 As d is a variadic variable it is stored and increased for every value.
Definition at line 90 of file importexport.md.libmd.cc.
{
    ui d=vvars[1];
    particles[i].dx[d]=dx;
    import_vel(i,argv...);
}
index()
template<ui dim>
void md< dim >::index [inherited]
Find neighbors.
This function finds all the pairs of particles that are within network.ssz of each other and have an interaction. They are then put in each other's skinlist (network.skins[]).
 It calls the algorithm specificied by indexdata.method: md<dim>::bruteforce(), md<dim>::kdtree() or md<dim>::cell().
Definition at line 14 of file index.md.libmd.cc.
{
    for(ui i=0;i<N;i++) thread_index_stick(i);
    switch(indexdata.method)
    {
        case INDEX::BRUTE_FORCE:
            bruteforce();
        break;
        case INDEX::KD_TREE:
            kdtree();
        break;
        default:
            cell();
        break;
    }
    avars.reindex=false;
}
References INDEX::BRUTE_FORCE, and INDEX::KD_TREE.
init()
template<ui dim>
void md< dim >::init (ui particlenr) [inherited]
Copy of the particle number constructor.
Initialize md structure for a given number of particles specified by particlenr. Resizes all lists of structures that require one element per particle.
Definition at line 16 of file md.libmd.cc.
{
    N=particlenr;
    DEBUG_1("creating md<" F_UI "> with " F_UI " particles",dim,N);
    if(N)
    {
        particles.resize(N);
        network.skins.resize(N);
        network.forces.resize(N);
        network.spid.resize(N);
        for(ui i=0;i<N;i++) network.spid[i]=UI_MAX;
    }
    avars.export_force_calc=true;
}
References DEBUG_1, F_UI, and UI_MAX.
integrate()
template<ui dim>
void mpmd< dim >::integrate [final], [override], [virtual]
Integrate particle trajectoriess.
This function is the Monge patch analog to md<dim>::integrate() and calculates the particle trajectories.
 After integrating (and updating the particle) it call md<dim>::periodicity(), and calculates the geomatric derivatives for the new particle position.
Reimplemented from md< dim >.
Definition at line 228 of file mpmd.libmd.cc.
{
    avars.export_force_calc=true;
    switch(integrator.method)
    {
        case MP_INTEGRATOR::VVERLET:
            WARNING("flatspace integrator");
            DEBUG_2("integrating using flatspace velocity Verlet");
            for(ui i=0;i<N;i++) if(!particles[i].fix) thread_vverlet_x(i);
            recalc_forces();
            for(ui i=0;i<N;i++) if(!particles[i].fix) thread_vverlet_dx(i);
        break;
        case MP_INTEGRATOR::SEULER:
            WARNING("flatspace integrator");
            DEBUG_2("integrating using flatspace symplectic Euler");
            for(ui i=0;i<N;i++) if(!particles[i].fix) thread_seuler(i);
        break;
        case MP_INTEGRATOR::VZ_WFI:
            WARNING("incomplete integrator");
            DEBUG_2("integrating using van Zuiden without fixed point iterations");
            for(ui i=0;i<N;i++) if(!particles[i].fix) thread_zuiden_wfi(i);
        break;
        case MP_INTEGRATOR::VZ_P:
            DEBUG_2("integrating using van Zuiden with protected (with " F_UI " generations) fixed point iterations",integrator.generations);
            for(ui i=0;i<N;i++) if(!particles[i].fix) thread_zuiden_protect(i);
        break;
        default:
            DEBUG_2("integrating using van Zuiden");
            for(ui i=0;i<N;i++) if(!particles[i].fix) thread_zuiden(i);
        break;
    }
    periodicity();
    patch.geometryxp=patch.geometryx;
    calc_geometry();
}
References DEBUG_2, F_UI, MP_INTEGRATOR::SEULER, MP_INTEGRATOR::VVERLET, MP_INTEGRATOR::VZ_P, MP_INTEGRATOR::VZ_WFI, and WARNING.
interactions()
template<ui dim>
void md< dim >::interactions (ui i, std::vector< std::pair< ui, ui >> & table) [inherited]
Dump interactions of a certain particle into a table.
This function puts a list of all interaction neighbors of particle i in table, as pairs of particles with i being the first.
Definition at line 6 of file interaction.md.libmd.cc.
{
    table.clear();
    for(auto sij: network.skins[i]) if(distsq(i,sij.neighbor)<std::pow(get_rco(sij.interaction),2)) table.push_back(std::pair<ui,ui>(i,sij.neighbor));
}
References pow().
kdtree()
template<ui dim>
void md< dim >::kdtree [inherited]
k-d tree indexing algorithm
This indexing function uses a k-d tree (a multidimensional binary tree).
 It makes use of the recursive functions md<dim>::kdtree_build() and md<dim>::kdtree_index().
 It does not work if there is both shear and a dimension with periodic boundary conditions.
Definition at line 140 of file index.md.libmd.cc.
{
    if (simbox.useLshear)
        for (ui d = 0; d < dim; d++)
            if (simbox.bcond[d] == BCOND::PERIODIC || simbox.bcond[d] == BCOND::BOXSHEAR)
            { ERROR("the kd-tree algorithm does not work with both shear and periodic boundary conditions");
                return;
            }
    if (indexdata.kdtreedata.Idx == nullptr || sizeof(indexdata.kdtreedata.Idx) != N*sizeof(ui))
    { delete[] indexdata.kdtreedata.Idx;
        delete[] indexdata.kdtreedata.Pmin;
        delete[] indexdata.kdtreedata.Pmax;
        indexdata.kdtreedata.Idx = new ui[N];
        indexdata.kdtreedata.Pmin = new ldf[N][dim];
        indexdata.kdtreedata.Pmax = new ldf[N][dim];
    }
    ldf S[dim];
    ui i, n, d, b;
    for (i = 0; i < N; i++)
        indexdata.kdtreedata.Idx[i] = i;
    // Decide on which dimensions to divide the particles by at each recursion level
    memcpy(S, simbox.L, sizeof(S));
    for (i = 0, n = N; n > 1; i++, n = (n+1)/2)
    { // Look for largest dimension
        b = 0;
        for (d = 1; d < dim; d++)
            if (S[b] < S[d])
                b = d;
        indexdata.kdtreedata.DivideByDim[i] = b;
        S[b] /= 2; // Assume that the system is nicely split into two parts
    }
    kdtree_build(0, N, 0);
    for (i = 0; i < N; i++)
        network.skins[i].clear();
    kdtree_index(0, N, 0, N);
}
References BCOND::BOXSHEAR, ERROR, and BCOND::PERIODIC.
kdtree_build()
template<ui dim>
ui md< dim >::kdtree_build (ui first, ui last, ui level) [inherited]
k-d tree indexing algorithm: tree build function (recursive)
This function recursively builds the k-d tree, to be used by md<dim>::kdtree().
 The particles in the subtree marked by first and last at recursion depth level are split into two subtrees of (about) equal size. The particles in one subtree have a lower value of their position coordinate in a given dimension than the particles in the other subtree. The dimension is specified by indexdata.kdtreedata.DivideByDim[level], which is set by md<dim>::kdtree(). The two subtrees are build recursively.
Definition at line 60 of file index.md.libmd.cc.
{
    if (last - first == 1) // Leaf
    { // Set minimum and maximum value equal to the position of this particle (Idx[first])
        memcpy(indexdata.kdtreedata.Pmin[first], particles[indexdata.kdtreedata.Idx[first]].x, dim*sizeof(ldf));
        memcpy(indexdata.kdtreedata.Pmax[first], particles[indexdata.kdtreedata.Idx[first]].x, dim*sizeof(ldf));
        return first;
    }
    ui m = (first+last)/2; // Median
    ui sortedDim = indexdata.kdtreedata.DivideByDim[level];
    // Put the index of particle with the median value of coordinate dim in its right place,
    // put all particles with lower values below, and all with higher values above
    std::nth_element(indexdata.kdtreedata.Idx+first, indexdata.kdtreedata.Idx+m, indexdata.kdtreedata.Idx+last,
                [=](ui i, ui j) -> bool { return particles[i].x[sortedDim]<particles[j].x[sortedDim];});
    // Recursively build subtrees
    ui m1 = kdtree_build(first, m, level+1), m2 = kdtree_build(m, last, level+1), d;
    // Determine minimum and maximum value of each coordinate
    for (d = 0; d < dim; d++)
    { indexdata.kdtreedata.Pmin[m][d] = std::min(indexdata.kdtreedata.Pmin[m1][d], indexdata.kdtreedata.Pmin[m2][d]);
        indexdata.kdtreedata.Pmax[m][d] = std::max(indexdata.kdtreedata.Pmax[m1][d], indexdata.kdtreedata.Pmax[m2][d]);
    }
    return m;
}
kdtree_index()
template<ui dim>
void md< dim >::kdtree_index (ui first1, ui last1, ui first2, ui last2) [inherited]
k-d tree indexing algorithm: neighbor finder (recursive)
This function recursively finds neighboring particles, one from subtree 1, the other from subtree 2 (possibly the same subtree).
 First it is checked if the subtrees are too far apart; nothing is done then. Otherwise, the function is called for every combination of subtrees. When a leaf is reached, the single particle is checked against the particle(s) in the other subtree.
Definition at line 91 of file index.md.libmd.cc.
{
    ui m1 = (first1+last1)/2, m2 = (first2+last2)/2, d;
    ldf sszsq = std::pow(network.ssz,2);
    // Base cases
    if (m1 == first1 || m2 == first2) // A single particle
    { // Note: the other subtree contains either one or two particles
        if (m1 != m2)
            skinner(indexdata.kdtreedata.Idx[m1], indexdata.kdtreedata.Idx[m2], sszsq);
        if (m2 != first2)
            skinner(indexdata.kdtreedata.Idx[m1], indexdata.kdtreedata.Idx[first2], sszsq);
        if (m1 != first1)
            skinner(indexdata.kdtreedata.Idx[first1], indexdata.kdtreedata.Idx[m2], sszsq);
        return;
    }
    // Compute distance (squared) between subtrees
    if (m1 != m2) // Note: m1 == m2 iff the subtrees are the same
    { ldf dissqBetweenSubtrees = 0;
        for (d = 0; d < dim; d++)
        { if (simbox.bcond[d] == BCOND::PERIODIC)
            { if (indexdata.kdtreedata.Pmin[m1][d] > indexdata.kdtreedata.Pmax[m2][d])
                    dissqBetweenSubtrees += std::pow(std::min(indexdata.kdtreedata.Pmin[m1][d] - indexdata.kdtreedata.Pmax[m2][d],
                                                    simbox.L[d] + indexdata.kdtreedata.Pmin[m2][d] - indexdata.kdtreedata.Pmax[m1][d]), 2);
                else if (indexdata.kdtreedata.Pmin[m2][d] > indexdata.kdtreedata.Pmax[m1][d])
                    dissqBetweenSubtrees += std::pow(std::min(indexdata.kdtreedata.Pmin[m2][d] - indexdata.kdtreedata.Pmax[m1][d],
                                                    simbox.L[d] + indexdata.kdtreedata.Pmin[m1][d] - indexdata.kdtreedata.Pmax[m2][d]), 2);
            }
            else if (indexdata.kdtreedata.Pmin[m1][d] > indexdata.kdtreedata.Pmax[m2][d])
                dissqBetweenSubtrees += std::pow(indexdata.kdtreedata.Pmin[m1][d] - indexdata.kdtreedata.Pmax[m2][d], 2);
            else if (indexdata.kdtreedata.Pmin[m2][d] > indexdata.kdtreedata.Pmax[m1][d])
                dissqBetweenSubtrees += std::pow(indexdata.kdtreedata.Pmin[m2][d] - indexdata.kdtreedata.Pmax[m1][d], 2);
        }
        if (dissqBetweenSubtrees >= sszsq) // Return if the subtrees are too far apart
            return;
    }
    // Recursively check subtrees
    kdtree_index(first1, m1, first2, m2);
    kdtree_index(first1, m1, m2, last2);
    if (m1 != m2)
        kdtree_index(m1, last1, first2, m2);
    kdtree_index(m1, last1, m2, last2);
}
References BCOND::PERIODIC, and pow().
mad_bond() [1/2]
template<ui dim>
void md< dim >::mad_bond (ui p1, ui p2, ui interaction) [inherited]
Force add/modify bond.
Same as md<dim>::add_bond(ui p1, ui p2, ui interaction), but performs no checks.
 Warning: Assumes that the specified interaction type actually exists, and replaces any previously defined interaction between p1 and p2.
Definition at line 115 of file bonds.md.libmd.cc.
{
    assign_unique_types(p1, p2);
    network.lookup[network.hash(particles[p1].type,particles[p2].type)]=interaction;
    update_skins(p1,p2);
}
mad_bond() [2/2]
template<ui dim>
void md< dim >::mad_bond (ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Force add/modify bond.
Same as md<dim>::add_bond(ui p1, ui p2, ui potential, std::vector<ldf> &parameters), but performs no checks.
 Warning: Replaces any previously defined interaction between p1 and p2.
Definition at line 171 of file bonds.md.libmd.cc.
{
    mad_bond(p1, p2, add_interaction(potential, parameters));
}
mad_sp_bond() [1/2]
template<ui dim>
void md< dim >::mad_sp_bond (ui p1, ui p2, ui interaction) [inherited]
Force add/modify superparticle bond.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then assigns an interaction to the two particles, using element interaction from network.library[]. It does not perform any checks.
Definition at line 299 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    network.sptypes[clone_sptype(spi)].splookup[id] = interaction;
    update_skins(p1,p2);
}
mad_sp_bond() [2/2]
template<ui dim>
void md< dim >::mad_sp_bond (ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Force add/modify superparticle bond.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then assigns an interaction to the two particles, using a new interaction of the given type and with the given parameters. It does not perform any checks.
Definition at line 350 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    network.sptypes[clone_sptype(spi)].splookup[id] = add_interaction(potential, parameters);
    update_skins(p1,p2);
}
mad_sp_interaction() [1/3]
template<ui dim>
ui md< dim >::mad_sp_interaction (ui spt, ui p1, ui p2, ui interaction) [inherited]
Force add/mod superparticle interaction rule.
This function assigns an interaction to particle numbers p1 and p2 of superparticles of type spt, using element interaction from network.library[]. If the given superparticletype does not exist, a new one is added to network.sptypes[]. It returns the index of the superparticletype (which is spt or the index of the newly created one). It does not perform any checks.
Definition at line 368 of file interaction.md.libmd.cc.
{
    if (spt >= network.sptypes.size())
    { spt = network.sptypes.size();
        network.sptypes.push_back(superparticletype());
    }
    network.sptypes[spt].splookup[network.hash(p1,p2)] = interaction;
    avars.reindex=true;
    return spt;
}
mad_sp_interaction() [2/3]
template<ui dim>
ui md< dim >::mad_sp_interaction (ui spt, ui p1, ui p2, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Force add/mod superparticle interaction rule.
This function assigns an interaction to particle numbers p1 and p2 of superparticles of type spt, using a new interaction of the given type and with the given parameters. If the given superparticletype does not exist, a new one is added to network.sptypes[]. It returns the index of the superparticletype (which is spt or the index of the newly created one). It does not perform any checks.
Definition at line 472 of file interaction.md.libmd.cc.
{
    if (spt >= network.sptypes.size())
    {
        spt = network.sptypes.size();
        network.sptypes.push_back(superparticletype());
    }
    network.sptypes[spt].splookup[network.hash(p1,p2)] = add_interaction(potential,rco,parameters);
    avars.reindex=true;
    return spt;
}
mad_sp_interaction() [3/3]
template<ui dim>
ui md< dim >::mad_sp_interaction (ui spt, ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Force add/mod superparticle interaction rule.
This function assigns an interaction to particle numbers p1 and p2 of superparticles of type spt, using a new interaction of the given type and with the given parameters. If the given superparticletype does not exist, a new one is added to network.sptypes[]. It returns the index of the superparticletype (which is spt or the index of the newly created one). It does not perform any checks.
Definition at line 460 of file interaction.md.libmd.cc.
{
    return mad_sp_interaction(spt,p1,p2,potential,network.rco,parameters);
}
mad_typeinteraction() [1/3]
template<ui dim>
void md< dim >::mad_typeinteraction (ui type1, ui type2, ui interaction) [inherited]
Force add/mod type interaction rule.
This function assigns a type interaction to the given pair of types, using element interaction from network.library[]. It does not perform any checks.
Definition at line 172 of file interaction.md.libmd.cc.
{
    network.lookup[network.hash(type1,type2)]=interaction;
    avars.reindex=true;
}
mad_typeinteraction() [2/3]
template<ui dim>
void md< dim >::mad_typeinteraction (ui type1, ui type2, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Force add/mod type interaction rule.
This function assigns a type interaction to the given pair of types, using a new interaction of the given type and with the given parameters. It does not perform any checks.
Definition at line 245 of file interaction.md.libmd.cc.
{
    network.lookup[network.hash(type1,type2)]=add_interaction(potential,rco,parameters);
    avars.reindex=true;
}
mad_typeinteraction() [3/3]
template<ui dim>
void md< dim >::mad_typeinteraction (ui type1, ui type2, ui potential, std::vector< ldf > & parameters) [inherited]
Force add/mod type interaction rule.
This function assigns a type interaction to the given pair of types, using a new interaction of the given type and with the given parameters. It does not perform any checks.
Definition at line 236 of file interaction.md.libmd.cc.
{
    mad_typeinteraction(type1,type2,potential,network.rco,parameters);
}
mod_bond() [1/2]
template<ui dim>
bool md< dim >::mod_bond (ui p1, ui p2, ui interaction) [inherited]
Modify a bond.
This function modifies any previous interaction between particles p1 and p2, and turns it into a bond of previously-defined interaction type specified in the third argument. (See the Interactions documentation for more information on interaction types.)
 Does nothing and returns false if one of the following holds:
no interaction exists between p1 and p2,
the interaction specified by the third argument does not exist or was previously removed.
Otherwise, creates a bond of the specified type between p1 and p2, and returns true.
Definition at line 79 of file bonds.md.libmd.cc.
{
    if (!network.lookup.count(network.hash(particles[p1].type,particles[p2].type)))
        return false;
    else if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    { assign_unique_types(p1, p2);
        network.lookup[network.hash(particles[p1].type,particles[p2].type)]=interaction;
        update_skins(p1,p2);
        return true;
    }
}
References WARNING.
mod_bond() [2/2]
template<ui dim>
bool md< dim >::mod_bond (ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Modify a bond.
This function modifies any previous interaction between particles p1 and p2 into a pair-specific bond with the potential type and parameters specified in the arguments. (See the Interactions documentation for more information on potential types and passing parameters.)
 Does nothing if an interaction already exists between p1 and p2, and returns false. Otherwise, creates a bond of the specified type between p1 and p2, and returns true.
Definition at line 150 of file bonds.md.libmd.cc.
{
    if (!network.lookup.count(network.hash(particles[p1].type,particles[p2].type)))
        return false;
    else
    { mad_bond(p1, p2, add_interaction(potential, parameters));
        return true;
    }
}
mod_forcetype() [1/2]
template<ui dim>
bool md< dim >::mod_forcetype (ui ftype, ui force, std::vector< ldf > & parameters) [inherited]
Modify force type.
This function replaces the forcetype in network.forcelibrary[] with index ftype with a forcetype of the given type and with the given parameters. It returns whether the given forcelibrary element exists.
Definition at line 532 of file interaction.md.libmd.cc.
{
    if(ftype<network.forcelibrary.size())
    {
        forcetype temp(force,parameters);
        network.forcelibrary[ftype]=temp;
        return true;
    }
    else return false;
}
mod_forcetype() [2/2]
template<ui dim>
bool md< dim >::mod_forcetype (ui ftype, ui force, std::vector< std::vector< ui >> & plist, std::vector< ldf > & parameters) [inherited]
Modify force type plist.
This function replaces the forcetype in network.forcelibrary[] with index ftype with a forcetype of the given type and with the given parameters. It returns whether the given forcelibrary element exists.
Definition at line 548 of file interaction.md.libmd.cc.
{
    if(ftype<network.forcelibrary.size())
    {
        forcetype temp(force,plist,parameters);
        network.forcelibrary[ftype]=temp;
        return true;
    }
    else return false;
}
mod_hook()
template<ui dim>
bool md< dim >::mod_hook (ui htype, ui nohook, std::vector< ldf > & parameters) [inherited]
Modify a hook.
This function replaces the forcetype in hook.hookers[] with index htype with a forcetype of the given type and with the given parameters. It returns whether the given forcelibrary element exists.
Definition at line 16 of file hooks.md.libmd.cc.
{
    if(htype<hooks.hookers.size())
    {
        hooktype temp(hook,parameters);
        hooks.hookers[htype]=temp;
        return true;
    }
    else return false;
}
mod_interaction() [1/2]
template<ui dim>
bool md< dim >::mod_interaction (ui interaction, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Modify type interaction rule.
This function replaces the interaction in network.library[] with index interaction with a potential of the given type and with the given parameters. It returns whether the given library element exists.
Definition at line 63 of file interaction.md.libmd.cc.
{
    if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    {
        interactiontype itype(potential,parameters,rco,v(potential,rco,parameters));
        network.library[interaction]=itype;
        avars.reindex=true;
        return true;
    }
}
References WARNING.
mod_interaction() [2/2]
template<ui dim>
bool md< dim >::mod_interaction (ui interaction, ui potential, std::vector< ldf > & parameters) [inherited]
Modify type interaction rule.
This function replaces the interaction in network.library[] with index interaction with a potential of the given type and with the given parameters. It returns whether the given library element exists.
Definition at line 53 of file interaction.md.libmd.cc.
{
    return mod_interaction(interaction,potential,network.rco,parameters);
}
mod_sp_bond() [1/2]
template<ui dim>
bool md< dim >::mod_sp_bond (ui p1, ui p2, ui interaction) [inherited]
Modify a superparticle bond.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then modifies the interaction between the two particles, using element interaction from network.library[]. If the two particles are not in the same superparticle, or do not have an interaction already, it does nothing and returns false.
Definition at line 280 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    if (spi == UI_MAX || spi != network.spid[p2])
        return false;
    ui spt = network.superparticles[spi].sptype;
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    if (!network.sptypes[spt].splookup.count(id))
        return false;
    network.sptypes[clone_sptype(spi)].splookup[id] = interaction;
    update_skins(p1,p2);
    return true;
}
References UI_MAX.
mod_sp_bond() [2/2]
template<ui dim>
bool md< dim >::mod_sp_bond (ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Modify a superparticle bond.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then modifies the interaction between the two particles, using a new interaction of the given type and with the given parameters. If the two particles are not in the same superparticle, or do not have an interaction already, it does nothing and returns false.
Definition at line 331 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    if (spi == UI_MAX || spi != network.spid[p2])
        return false;
    ui spt = network.superparticles[spi].sptype;
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    if (!network.sptypes[spt].splookup.count(id))
        return false;
    network.sptypes[clone_sptype(spi)].splookup[id] = add_interaction(potential, parameters);
    update_skins(p1,p2);
    return true;
}
References UI_MAX.
mod_sp_interaction() [1/3]
template<ui dim>
bool md< dim >::mod_sp_interaction (ui spt, ui p1, ui p2, ui interaction) [inherited]
Modify superparticle interaction rule.
This function modifies the interaction between particle numbers p1 and p2 of superparticles of type spt, using element interaction from network.library[]. It returns whether the given superparticletype and interaction exist and the particle numbers already had an interaction. If the two particle numbers do not already have an interaction, it is not added.
Definition at line 334 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(p1,p2);
    if(spt>=network.sptypes.size())
    {
        WARNING("superparticletype %d does not exist", spt);
        return false;
    }
    else if(!network.sptypes[spt].splookup.count(id))
        return false;
    else if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    {
        network.sptypes[spt].splookup[id]=interaction;
        avars.reindex=true;
        return true;
    }
}
References WARNING.
mod_sp_interaction() [2/3]
template<ui dim>
bool md< dim >::mod_sp_interaction (ui spt, ui p1, ui p2, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Modify superparticle interaction rule.
This function modifies the interaction between particle numbers p1 and p2 of superparticles of type spt, using a new interaction of the given type and with the given parameters. It returns whether the given superparticletype and interaction exist and the particle numbers already had an interaction. If the two particle numbers do not already have an interaction, it is not added and the interaction is not added to network.library[].
Definition at line 435 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(p1,p2);
    if(spt>=network.sptypes.size())
    {
        WARNING("superparticletype %d does not exist", spt);
        return false;
    }
    else if(!network.sptypes[spt].splookup.count(id))
        return false;
    else
    {
        network.sptypes[spt].splookup[id] = add_interaction(potential,rco,parameters);
        avars.reindex=true;
        return true;
    }
}
References WARNING.
mod_sp_interaction() [3/3]
template<ui dim>
bool md< dim >::mod_sp_interaction (ui spt, ui p1, ui p2, ui potential, std::vector< ldf > & parameters) [inherited]
Modify superparticle interaction rule.
This function modifies the interaction between particle numbers p1 and p2 of superparticles of type spt, using a new interaction of the given type and with the given parameters. It returns whether the given superparticletype and interaction exist and the particle numbers already had an interaction. If the two particle numbers do not already have an interaction, it is not added and the interaction is not added to network.library[].
Definition at line 423 of file interaction.md.libmd.cc.
{
    return mod_sp_interaction(spt,p1,p2,potential,network.rco,parameters);
}
mod_typeinteraction() [1/3]
template<ui dim>
bool md< dim >::mod_typeinteraction (ui type1, ui type2, ui interaction) [inherited]
Modify type interaction rule.
This function modifies the type interaction between the given types, using element interaction from network.library[]. It returns whether the given interaction exists and the two types already had an interaction. If the two types do not already have an interaction, it is not added.
Definition at line 144 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(type1,type2);
    if(!network.lookup.count(id))
        return false;
    else if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    {
        network.lookup[id]=interaction;
        avars.reindex=true;
        return true;
    }
}
References WARNING.
mod_typeinteraction() [2/3]
template<ui dim>
bool md< dim >::mod_typeinteraction (ui type1, ui type2, ui potential, ldf rco, std::vector< ldf > & parameters) [inherited]
Modify type interaction rule.
This function modifies the type interaction between the given types, using a new interaction of the given type and with the given parameters. It returns whether the two types already had an interaction. If the two types do not already have an interaction, it is not added and the interaction is not added to network.library[].
Definition at line 219 of file interaction.md.libmd.cc.
{
    std::pair<ui,ui> id=network.hash(type1,type2);
    if(!network.lookup.count(id)) return false;
    else
    {
        network.lookup[id]=add_interaction(potential,rco,parameters);
        avars.reindex=true;
        return true;
    }
}
mod_typeinteraction() [3/3]
template<ui dim>
bool md< dim >::mod_typeinteraction (ui type1, ui type2, ui potential, std::vector< ldf > & parameters) [inherited]
Modify type interaction rule.
This function modifies the type interaction between the given types, using a new interaction of the given type and with the given parameters. It returns whether the two types already had an interaction. If the two types do not already have an interaction, it is not added and the interaction is not added to network.library[].
Definition at line 209 of file interaction.md.libmd.cc.
{
    return mod_typeinteraction(type1,type2,potential,network.rco,parameters);
}
mp_thread_calc_pot_forces()
template<ui dim>
void mpmd< dim >::mp_thread_calc_pot_forces (ui i)
Calculate the forces for particle i>j with atomics.
This function is the Monge patch analog to md<dim>::thread_calc_pot_forces(ui i) and calculates the forces induced by the potentials acting on particle i.
Definition at line 178 of file mpmd.libmd.cc.
{
    for(auto sij: network.skins[i]) if(i>sij.neighbor)
    {
        const ldf rsq=embedded_distsq(i,sij.neighbor);
        if(!network.update or rsq<std::pow(get_rco(sij.interaction),2))
        {
            const ldf r=std::sqrt(rsq);
            DEBUG_3("r = " F_LDF,r);
            const ldf dVdr=v.dr(network.library[sij.interaction].potential,r,network.library[sij.interaction].parameters);
            DEBUG_3("dV/dr = " F_LDF,dVdr);
            for(ui d=0;d<dim;d++)
            {
                particles[i].F[d]+=embedded_dd_p1(d,i,sij.neighbor)*dVdr/r;
                DEBUG_3("particles[" F_UI "].F[" F_UI "] = " F_LDF,i,d,embedded_dd_p1(d,i,sij.neighbor)*dVdr/r);
                particles[sij.neighbor].F[d]+=embedded_dd_p2(d,i,sij.neighbor)*dVdr/r;
                DEBUG_3("particles[" F_UI "].F[" F_UI "] = " F_LDF,sij.neighbor,d,embedded_dd_p2(d,i,sij.neighbor)*dVdr/r);
            }
        }
    }
}
References DEBUG_3, F_LDF, F_UI, pow(), and sqrt().
periodicity()
template<ui dim>
void md< dim >::periodicity [inherited]
Called after integration to keep the particle within the defined boundaries.
Update positions and velocities of particles to respect the appropriate boundary conditions.
 This function loops through the dim dimensions, and updates the positions and velocities of all (non-fixed) particles that have passed through the boundary perpendicular to dimension d, based on the value of simbox.bcond[d].
Definition at line 26 of file periodicity.md.libmd.cc.
{
    for(ui i=0;i<N;i++) if(!particles[i].fix)
    {
        if(particles[i].usepbcond) for(ui d=0;d<dim;d++) boundary(particles[i].pbc[d],d,i,this);
        else for(ui d=0;d<dim;d++) boundary(d,i,this);
    }
}
recalc_forces()
template<ui dim>
void mpmd< dim >::recalc_forces [final], [override], [virtual]
Integrate particle trajectoriess.
This function calls mpmd<dim>::mp_thread_calc_forces(ui i) for all particles (without clearing the forces).
Reimplemented from md< dim >.
Definition at line 219 of file mpmd.libmd.cc.
{
    DEBUG_3("exec is here");
    if(!network.library.empty()) for(ui i=0;i<N;i++) mp_thread_calc_pot_forces(i);
    if(!network.forcelibrary.empty()) for(ui i=0;i<N;i++) thread_calc_ext_forces(i);
}
References DEBUG_3.
rem_bond()
template<ui dim>
bool md< dim >::rem_bond (ui p1, ui p2) [inherited]
Remove a bond from the system.
If a prior interaction between particles p1 and p2 exists, removes it and returns true, else returns false.
Definition at line 183 of file bonds.md.libmd.cc.
{
    if (!network.lookup.count(network.hash(particles[p1].type,particles[p2].type)))
        return false;
    else
    { assign_unique_types(p1,p2);
        network.lookup.erase(network.hash(particles[p1].type,particles[p2].type));
        update_skins(p1,p2);
        return true;
    }
}
rem_forcetype()
template<ui dim>
bool md< dim >::rem_forcetype (ui ftype) [inherited]
Delete force type.
This function removes the forcetype with index ftype from network.forcelibrary[]. It returns whether the given forcelibrary element existed.
 Note: the last forcetype in network.forcelibrary[] takes the place of the old one.
Definition at line 564 of file interaction.md.libmd.cc.
{
    ui pos=network.forcelibrary.size();
    if(ftype<pos)
    {
        for(ui i=0;i<N;i++) for(ui j=network.forces[i].size()-1;j<UI_MAX;j--) if(network.forces[i][j]==ftype)
        {
            network.forces[i][j]=network.forces[i].back();
            network.forces[i].pop_back();
            break;
        }
        if(ftype<pos-1)
        {
            network.forcelibrary[ftype]=network.forcelibrary.back();
            for(ui i=0;i<N;i++) for(ui j=network.forces[i].size()-1;j<UI_MAX;j--) if(network.forces[i][j]==pos-1) network.forces[i][j]=ftype;
        }
        network.forcelibrary.pop_back();
        return true;
    }
    else return false;
}
References UI_MAX.
rem_hook()
template<ui dim>
bool md< dim >::rem_hook (ui htype) [inherited]
Remove a hook.
This function removes the forcetype with index htype from hook.hookers[]. It returns whether the given forcelibrary element existed.
 Note: the last forcetype in hook.hookers[] takes the place of the old one.
Definition at line 32 of file hooks.md.libmd.cc.
{
    ui pos=hooks.hookers.size();
    if(htype<pos)
    {
        if(htype<pos-1) hooks.hookers[htype]=hooks.hookers.back();
        hooks.hookers.pop_back();
        return true;
    }
    else return false;
}
rem_interaction()
template<ui dim>
bool md< dim >::rem_interaction (ui interaction) [inherited]
Delete type interaction rule.
This function removes the interaction with index interaction from network.library[]. It returns whether the given library element existed.
 The other interactions retain their index.
Definition at line 89 of file interaction.md.libmd.cc.
{
    if(interaction>=network.library.size())
    {
        WARNING("interaction %d does not exist", interaction);
        return false;
    }
    else if(network.free_library_slots.count(interaction))
    {
        WARNING("interaction %d was previously removed", interaction);
        return false;
    }
    else
    {
        network.free_library_slots.insert(interaction);
        for(auto it=network.lookup.begin();it!=network.lookup.end();) (it->second==interaction)?network.lookup.erase(it++):it++;
        for(ui i=network.sptypes.size()-1;i<UI_MAX;i--) for(auto it=network.sptypes[i].splookup.begin();it!=network.sptypes[i].splookup.end();) (it->second==interaction)?network.sptypes[i].splookup.erase(it++):it++;
        avars.reindex=true;
        return true;
    }
}
References UI_MAX, and WARNING.
rem_particle()
template<ui dim>
void md< dim >::rem_particle (ui i) [inherited]
Remove a particle from the system.
This function removes particle i and all references to it from the system.
 Note: particle N-1 becomes the new particle i (if $i<N-1$).
Definition at line 76 of file particles.md.libmd.cc.
{
    DEBUG_2("removing particle #" F_UI "",i);
    if(network.spid[i]<UI_MAX)
        network.superparticles[network.spid[i]].particles.erase(i);
    ui j, k, p;
    if (i < N-1)
    { // swap particle to delete with last particle, to prevent changing index of all particles after particlenr, and then delete it
        iter_swap(particles.begin()+i, particles.rbegin());
        // update the network
        iter_swap(network.skins.begin()+i, network.skins.rbegin());
        iter_swap(network.forces.begin()+i, network.forces.rbegin());
        // Modify skins
        for (j = network.skins[i].size()-1; j < UI_MAX; j--)
        { p = network.skins[i][j].neighbor;
            if (p == i)
                p = N-1;
            for (k = network.skins[p].size()-1; k < UI_MAX && network.skins[p][k].neighbor != N-1; k--);
            if (k > N)
            { ERROR("(formerly) last particle not found in skinlist of particle #%d", p);
                return;
            }
            network.skins[p][k].neighbor = i;
        }
        // Modify superparticle
        if ((network.spid[i] = network.spid[N-1]) < UI_MAX)
        { auto it = network.superparticles[network.spid[i]].particles.find(N-1);
            if (it == network.superparticles[network.spid[i]].particles.end())
            { ERROR("particle #" F_UI " not found in superparticle #" F_UI "", N-1, network.spid[i]);
                return;
            }
            network.superparticles[network.spid[i]].particles[i] = it->second;
            network.superparticles[network.spid[i]].backdoor[it->second] = i;
            network.superparticles[network.spid[i]].particles.erase(it);
        }
        for(auto ftype:network.forcelibrary) if(!ftype.particles.empty()) iter_swap(ftype.particles.begin()+i,ftype.particles.rbegin());
    }
    for(auto ftype:network.forcelibrary) if(!ftype.particles.empty())
    {
        ftype.particles.pop_back();
        for(j=0;j<N-1;j++) for(k=ftype.particles[j].size()-1;k<UI_MAX;k--) if(ftype.particles[j][k]==i)
        {
            iter_swap(ftype.particles[j].begin()+k,ftype.particles[j].rbegin());
            ftype.particles[j].pop_back();
        }
    }
    if(i<N-1) for(auto ftype:network.forcelibrary) if(!ftype.particles.empty()) for(j=0;j<N-1;j++) for(k=ftype.particles[j].size()-1;k<UI_MAX;k--) if(ftype.particles[j][k]==N-1) ftype.particles[j][k]=i;
    // Modify skins
    for (j = network.skins[N-1].size()-1; j < UI_MAX; j--)
    { p = network.skins[N-1][j].neighbor;
        for (k = network.skins[p].size()-1; k < UI_MAX && network.skins[p][k].neighbor != i; k--);
        if (k > N)
        { ERROR("particle to be deleted not found in skinlist of particle #%d", p);
            return;
        }
        iter_swap(network.skins[p].begin()+k, network.skins[p].rbegin());
        network.skins[p].pop_back();
    }
    // Remove last particle
    N--;
    particles.pop_back();
    network.skins.pop_back();
    network.forces.pop_back();
    network.spid.pop_back();
    avars.reindex=true;
}
References DEBUG_2, ERROR, F_UI, and UI_MAX.
rem_sp()
template<ui dim>
bool md< dim >::rem_sp (ui spi) [inherited]
Remove a superparticle (i.e. the structure, not the particles)
This function removes the superparticle with index spi from network.superparticles[] and resets the superparticle reference (network.spid[]) of all its particles. It returns whether the given superparticle existed.
 Note: the last superparticle in network.superparticles[] takes the place of the removed one
Definition at line 18 of file sp.md.libmd.cc.
{
    if(spi>=network.superparticles.size())
    {
        WARNING("superparticle #%d does not exist", spi);
        return false;
    }
    else
    {
        ui spn=network.superparticles.size()-1;
        if(spi<spn)
        {
            for(auto m: network.superparticles[spn].particles) network.spid[m.first]=spi;
            iter_swap(network.superparticles.begin()+spi,network.superparticles.rbegin());
        }
        for(auto m: network.superparticles[spn].particles) network.spid[m.first]=UI_MAX;
        network.superparticles.pop_back();
        DEBUG_2("removed superparticle #" F_UI "",spi);
        return true;
    }
}
References DEBUG_2, F_UI, UI_MAX, and WARNING.
rem_sp_bond()
template<ui dim>
bool md< dim >::rem_sp_bond (ui p1, ui p2) [inherited]
Remove a superparticle bond from the system.
This function creates a new superparticle type and assigns it to the superparticle that p1 and p2 belong to. It then removes the interaction between the two particles. If the two particles are not in the same superparticle, or do not have an interaction, it does nothing and returns false.
Definition at line 363 of file bonds.md.libmd.cc.
{
    ui spi = network.spid[p1];
    if (spi == UI_MAX || spi != network.spid[p2])
        return false;
    ui spt = network.superparticles[spi].sptype;
    std::pair<ui,ui> id = network.hash(network.superparticles[spi].particles[p1], network.superparticles[spi].particles[p2]);
    if (!network.sptypes[spt].splookup.count(id))
        return false;
    network.sptypes[clone_sptype(spi)].splookup.erase(id);
    update_skins(p1,p2);
    return true;
}
References UI_MAX.
rem_sp_interaction()
template<ui dim>
bool md< dim >::rem_sp_interaction (ui spt, ui p1, ui p2) [inherited]
Delete superparticle interaction rule.
This function removes the interaction between particle numbers p1 and p2 of superparticles of type spt. It does not remove the interaction fromnetwork.library[]. It returns whether the given superparticletype exists and the two particle numbers had an interaction.
Definition at line 491 of file interaction.md.libmd.cc.
{
    if(spt>=network.sptypes.size())
    {
        WARNING("superparticletype %d does not exist", spt);
        return false;
    }
    else
    {
        avars.reindex=true;
        return network.sptypes[spt].splookup.erase(network.hash(p1,p2));
    }
}
References WARNING.
rem_sp_particles()
template<ui dim>
bool md< dim >::rem_sp_particles (ui spi) [inherited]
Remove all particles in a superparticle.
This function removes all the particles of the superparticle with index spi from the system and clears the superparticle (but does not remove it). It returns whether the given superparticle exists.
Definition at line 46 of file sp.md.libmd.cc.
{
    if(spi>=network.superparticles.size())
    {
        WARNING("superparticle #%d does not exist", spi);
        return false;
    }
    else
    {
        ui k=0;
        std::vector<ui> target(network.superparticles[spi].particles.size());
        for(auto m: network.superparticles[spi].particles) target[k++]=m.first;
        for(auto i: target) rem_particle(i);
        network.superparticles[spi].particles.clear();
        network.superparticles[spi].backdoor.clear();
        DEBUG_2("removed particles of superparticle #" F_UI "",spi);
        return true;
    }
}
References DEBUG_2, F_UI, and WARNING.
rem_sptype()
template<ui dim>
bool md< dim >::rem_sptype (ui spt) [inherited]
Delete superparticletype.
This function removes the superparticletype with index spt from network.sptypes[]. It returns whether this element existed.
 Note: the last superparticletype in network.sptypes[] takes the place of the old one.
Definition at line 277 of file interaction.md.libmd.cc.
{
    if(spt<network.sptypes.size())
    {
        ui spn=network.sptypes.size()-1;
        for(ui i=network.superparticles.size()-1;i<UI_MAX;i--)
        {
            if(network.superparticles[i].sptype==spt) network.superparticles[i].sptype=UI_MAX;
            if(network.superparticles[i].sptype==spn) network.superparticles[i].sptype=spt;
        }
        iter_swap(network.superparticles.begin()+spt,network.superparticles.rbegin());
        network.sptypes.pop_back();
        avars.reindex=true;
        return true;
    }
    else return false;
}
References UI_MAX.
rem_typeinteraction()
template<ui dim>
bool md< dim >::rem_typeinteraction (ui type1, ui type2) [inherited]
Delete type interaction rule.
This function removes the type interaction between the given types. It does not remove the interaction fromnetwork.library[]. It returns whether the two types had an interaction.
Definition at line 255 of file interaction.md.libmd.cc.
{
    avars.reindex=true;
    return network.lookup.erase(network.hash(type1,type2));
}
run_hook()
template<ui dim>
bool md< dim >::run_hook (ui htype) [inherited]
Run a certain hook.
This function runs the hook with index htype from hook.hookers[].
Definition at line 49 of file hooks.md.libmd.cc.
{
    if(htype<hooks.hookers.size())
    {
        hooks.hook(hooks.hookers[htype].hook,hooks.hookers[htype].parameters,this);
        return true;
    }
    else return false;
}
run_hooks()
template<ui dim>
void md< dim >::run_hooks [inherited]
Run all hooks.
This function runs all the hook in hook.hookers[].
Definition at line 62 of file hooks.md.libmd.cc.
{
    for(hooktype htype:hooks.hookers) hooks.hook(htype.hook,htype.parameters,this);
}
References hooktype::hook, and hooktype::parameters.
set_bcond()
template<ui dim>
void md< dim >::set_bcond (uc bcond[dim]) [inherited]
Set the global boundary conditions.
Sets the global boundary conditions
Definition at line 222 of file setget.md.libmd.cc.
{
    memcpy(simbox.bcond,bcond,dim*sizeof(uc));
}
set_damping()
template<ui dim>
void md< dim >::set_damping (ldf coefficient) [inherited]
Enables damping and sets damping coefficient.
This function adds damping with the given coefficient, or changes the coefficient if damping was already set.
Definition at line 6 of file setget.md.libmd.cc.
{
    if(avars.noftypedamping==UI_MAX)
    {
        DEBUG_2("activating damping with damping coefficient: " F_LDF,coefficient);
        std::vector<ldf> parameters(1,coefficient);
        avars.noftypedamping=add_forcetype(EXTFORCE::DAMPING,parameters);
        assign_all_forcetype(avars.noftypedamping);
    }
    else
    {
        DEBUG_2("modifying damping coefficient to: " F_LDF,coefficient);
        network.forcelibrary[avars.noftypedamping].parameters[0]=coefficient;
    }
}
References EXTFORCE::DAMPING, DEBUG_2, F_LDF, and UI_MAX.
set_index_method()
template<ui dim>
void md< dim >::set_index_method (ui method) [inherited]
Set indexmethod.
Sets the indexing method to method.
Definition at line 214 of file setget.md.libmd.cc.
{
    indexdata.method=method;
}
set_langevin()
template<ui dim>
void mpmd< dim >::set_langevin (ldf T, ldf gamma) [final], [override], [virtual]
Enables Langevin thermostat (and damping) and sets T and gamma (does not use metric)
This function adds a Langevin thermostat with the given coefficient T and gamma, or changes the coefficient if it was already set.
Reimplemented from md< dim >.
Definition at line 298 of file mpmd.libmd.cc.
{
    if(avars.noftypelangevin==UI_MAX)
    {
        DEBUG_2("activating langevin (mp) thermostat with temperature: " F_LDF " and damping coefficient: " F_LDF,T,gamma);
        std::vector<ldf> parameters={T,gamma};
        avars.noftypelangevin=add_forcetype(EXTFORCE::LANGEVIN_MP,parameters);
        assign_all_forcetype(avars.noftypelangevin);
        set_damping(gamma);
    }
    else
    {
        DEBUG_2("modifying langevin (mp) coefficient T to: " F_LDF " and gamma to: " F_LDF,T,gamma);
        network.forcelibrary[avars.noftypedamping].parameters[0]=T;
        network.forcelibrary[avars.noftypedamping].parameters[0]=gamma;
        set_damping(gamma);
    }
}
References DEBUG_2, F_LDF, EXTFORCE::LANGEVIN_MP, and UI_MAX.
set_overdamped()
template<ui dim>
void md< dim >::set_overdamped (ldf coefficient) [inherited]
Enable overdamped dynamics (with First oder integration)
This function changes the integrator to INTEGRATOR::FO_OVERDAMPED Using this function with set_damping() might result in unwanted results
Definition at line 87 of file setget.md.libmd.cc.
{
    avars.overdamped_gamma=coefficient;
    if(avars.overdamped_pre_integrator!=INTEGRATOR::FO_OVERDAMPED) avars.overdamped_pre_integrator=integrator.method;
    integrator.method=INTEGRATOR::FO_OVERDAMPED;
    if(avars.noftypedamping<UI_MAX)
    {
        (void) coefficient;
        WARNING("set_damping in the overdamped regime might produce unwanted results");
    }
}
References INTEGRATOR::FO_OVERDAMPED, UI_MAX, and WARNING.
set_pbcond()
template<ui dim>
void md< dim >::set_pbcond (ui i, uc bcond[dim], bool toggle = true) [inherited]
Set the boundary conditions for particle i.
Sets particle's boundary conditions
Definition at line 230 of file setget.md.libmd.cc.
{
    particles[i].usepbcond=toggle;
    memcpy(particles[i].pbc,bcond,dim*sizeof(uc));
}
set_position_sp()
template<ui dim>
void md< dim >::set_position_sp (ui spi, ldf x[dim]) [inherited]
Get center of mass of super particle.
This function translates the superparticle with index spi such that its center of mass is at position x[].
Definition at line 250 of file sp.md.libmd.cc.
{
    DEBUG_2("repositioning superparticle #" F_UI "",spi);
    avars.export_force_calc=true;
    ldf delx[dim];
    get_position_sp(spi,delx);
    for(ui d=0;d<dim;d++) delx[d]=x[d]-delx[d];
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++) translate_particle(it->first,delx);
}
References DEBUG_2, and F_UI.
set_rco() [1/2]
template<ui dim>
void md< dim >::set_rco (ldf rco) [inherited]
Sets the cuttoff radius.
Sets network.rco, the interaction cut-off distance, to rco.
Definition at line 138 of file setget.md.libmd.cc.
{
    network.rco=rco;
    for (auto itype: network.library) itype.vco = v(itype.potential,network.rco,itype.parameters);
    if (network.rco > network.ssz)
    {
        WARNING("network.rco is now larger than network.ssz (" F_LDF " > " F_LDF ")",network.rco,network.ssz);
    }
}
References F_LDF, and WARNING.
set_rco() [2/2]
template<ui dim>
void md< dim >::set_rco (ui interaction, ldf rco) [inherited]
Sets the cuttoff radius.
Sets network.rco, the interaction cut-off distance, to rco.
Definition at line 151 of file setget.md.libmd.cc.
{
    auto itype=network.library[interaction];
    itype.rco = rco;
    itype.vco = v(itype.potential,rco,itype.parameters);
    if (rco > network.ssz)
    {
        WARNING("this rco is now larger than network.ssz (" F_LDF " > " F_LDF ")",rco,network.ssz);
    }
}
References F_LDF, and WARNING.
set_reserve() [1/2]
template<ui dim>
void md< dim >::set_reserve (ldf ssz) [inherited]
Set reserve memory according to skin size.
This function reserves space for the vectors in network.skins[], assuming that (approximately) all particles interact with each other.
Definition at line 182 of file setget.md.libmd.cc.
{
    set_reserve(ssz,N);
}
set_reserve() [2/2]
template<ui dim>
void md< dim >::set_reserve (ldf ssz, ui M) [inherited]
Set reserve memory according to skin size and some arbitrary number of particles.
This function reserves space for the vectors in network.skins[], the amount of space being based on the assumption that each particle has at most M particles it interacts with and they are uniformly distributed over the system.
Definition at line 191 of file setget.md.libmd.cc.
{
    ldf area=1.0;
    for(ui d=0;d<dim;d++) area*=simbox.L[d];
    const ldf vol=(std::pow(std::acos(-1.0),((ldf)dim)/2.0)/std::tgamma(1.0+((ldf)dim)/2.0))*std::pow(ssz,dim);
    const ui fed=std::min(N-1,(ui)(((ldf)M)*(vol)/(area))*2+4);
    DEBUG_1("reserved skin size set to " F_UI " skins",fed);
    for(ui i=0;i<N;i++) network.skins[i].reserve(fed);
}
References acos(), DEBUG_1, F_UI, and pow().
set_spbcond()
template<ui dim>
void md< dim >::set_spbcond (ui spi, uc bcond[dim], bool toggle = true) [inherited]
Set the boundary conditions for superparticle spi.
Sets particle's boundary conditions for the superparticles
Definition at line 239 of file setget.md.libmd.cc.
{
    ui K=network.superparticles[spi].backdoor.size(),i;
    for(ui k=0;k<K;k++)
    {
        if((i=network.superparticles[spi].backdoor[k])<UI_MAX)
        {
            particles[i].usepbcond=toggle;
            memcpy(particles[i].pbc,bcond,dim*sizeof(uc));
        }
    }
}
References UI_MAX.
set_ssz()
template<ui dim>
void md< dim >::set_ssz (ldf ssz) [inherited]
Sets the skin size radius and its square.
Sets network.ssz, the skinsize, to ssz and reserves space for network.skins[].
Definition at line 165 of file setget.md.libmd.cc.
{
    network.ssz=ssz;
    set_reserve(ssz);
    for(auto itype:network.library) if(itype.rco>network.ssz)
    {
        WARNING("rco of interaction %zu is now larger than network.ssz (" F_LDF " > " F_LDF ")",&itype-&network.library[0],itype.rco,network.ssz);
    }
    if(network.rco>network.ssz)
    {
        WARNING("network.rco is now larger than network.ssz (" F_LDF " > " F_LDF ")",network.rco,network.ssz);
    }
}
References F_LDF, and WARNING.
set_type()
template<ui dim>
void md< dim >::set_type (ui p, ui newtype) [inherited]
Update the type associated with particle p.
Sets the type of particle p to newtype.
Definition at line 206 of file setget.md.libmd.cc.
{
    particles[p].type=newtype;
}
set_velocity_sp()
template<ui dim>
void md< dim >::set_velocity_sp (ui spi, ldf dx[dim]) [inherited]
Assign velocity to a super particle (all particles the same)
This function sets the velocity of all particles belonging to the superparticle with index spi equal to dx[].
Definition at line 263 of file sp.md.libmd.cc.
{
    DEBUG_2("setting velocity of superparticle #" F_UI "",spi);
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++) memcpy(particles[it->first].dx,dx,dim*sizeof(ldf));
}
References DEBUG_2, and F_UI.
skinner()
template<ui dim>
void md< dim >::skinner (ui i, ui j, ldf sszsq) [inherited]
Places interactionneighbor in skin.
This function is used by the indexing algorithms. It checks if the squared distance between particles i and j is less than sszsq and if they have a (superparticle) type interaction; if so, it adds them (with the interaction) to each other's skinlist.
Definition at line 382 of file index.md.libmd.cc.
{
    if (distsq(i,j) > sszsq)
        return;
    const ui K=network.spid[i];
    std::pair<ui,ui> it;
    if(K<UI_MAX and K==network.spid[j] and network.sptypes[network.superparticles[K].sptype].splookup.count(it=network.hash(network.superparticles[K].particles[i],network.superparticles[K].particles[j])))
    {
        interactionneighbor in(j,network.sptypes[network.superparticles[K].sptype].splookup[it]);
        network.skins[i].push_back(in);
        in.neighbor=i;
        network.skins[j].push_back(in);
        DEBUG_3("super particle skinned (i,j)=(" F_UI "," F_UI ") in " F_UI " with interaction " F_UI "",i,j,K,network.sptypes[network.superparticles[K].sptype].splookup[it]);
    }
    else
    {
        it=network.hash(particles[i].type,particles[j].type);
        if(network.lookup.count(it))
        {
            interactionneighbor in(j,network.lookup[it]);
            network.skins[i].push_back(in);
            in.neighbor=i;
            network.skins[j].push_back(in);
            DEBUG_3("normally skinned (i,j)=(" F_UI "," F_UI ") with interaction " F_UI "",i,j,network.lookup[it]);
        }
    }
}
References DEBUG_3, F_UI, interactionneighbor::neighbor, and UI_MAX.
sp_dispose()
template<ui dim>
bool md< dim >::sp_dispose (ui i) [inherited]
Remove a particle from a superparticle.
This function removes particle i from its superparticle (but not from the system) It returns whether the given particle was in a superparticle.
Definition at line 110 of file sp.md.libmd.cc.
{
    ui spi=network.spid[i];
    if(spi==UI_MAX) return false;
    else
    {
        network.spid[i]=UI_MAX;
        DEBUG_2("particle #" F_UI " is removed from superparticle #" F_UI "",i,spi);
        ui j=network.superparticles[spi].particles[i];
        if(j==network.superparticles[spi].backdoor.size()-1)
        {
            network.superparticles[spi].backdoor.pop_back();
            while(!network.superparticles[spi].backdoor.empty() and network.superparticles[spi].backdoor.back()==UI_MAX) network.superparticles[spi].backdoor.pop_back();
        }
        else network.superparticles[spi].backdoor[j]=UI_MAX;
        network.superparticles[spi].particles.erase(i);
        avars.reindex=true;
        return true;
    }
}
References DEBUG_2, F_UI, and UI_MAX.
sp_dispose_idx()
template<ui dim>
bool md< dim >::sp_dispose_idx (ui spi, ui idx) [inherited]
Remove a particle from a superparticle.
This function removes the particle from slot idx of the superparticle with index spi from the superparticle (but not from the system). It returns whether the given superparticle exists and has a particle in the given slot.
Definition at line 135 of file sp.md.libmd.cc.
{
    if(spi>=network.superparticles.size())
    {
        WARNING("superparticle #" F_UI " does not exist",spi);
        return false;
    }
    else if(idx>=network.superparticles[spi].backdoor.size())
    {
        WARNING("superparticle #" F_UI " does not contain index #" F_UI "",spi,idx);
        return false;
    }
    else
    {
        ui i=network.superparticles[spi].backdoor[idx];
        if(i<UI_MAX)
        {
            sp_dispose(i);
            DEBUG_2("particle #" F_UI " is removed from superparticle #" F_UI "",i,spi);
            return true;
        }
        else
        {
            WARNING("superparticle #" F_UI " does not contain index #" F_UI "",spi,idx);
            return false;
        }
    }
}
References DEBUG_2, F_UI, UI_MAX, and WARNING.
sp_ingest()
template<ui dim>
ui md< dim >::sp_ingest (ui spi, ui i, ui idx = UI_MAX) [inherited]
Add a particle to a superparticle.
This function puts particle i in slot idx of the superparticle with index spi. If idx = UI_MAX, the index is set to highest index plus one. It returns the index. If the given superparticle does not exist, or the given particle is already in a superparticle, or the given slot is already taken, nothing is done and UI_MAX is returned.
Definition at line 71 of file sp.md.libmd.cc.
{
    if(spi>=network.superparticles.size())
    {
        WARNING("superparticle #%d does not exist", spi);
        return UI_MAX;
    }
    else if(network.spid[i] < UI_MAX)
    {
        WARNING("particle #" F_UI " is already in superparticle #" F_UI "",i,network.spid[i]);
        return UI_MAX;
    }
    else
    {
        if(idx>=network.superparticles[spi].backdoor.size())
        {
            if(idx==UI_MAX) idx=network.superparticles[spi].backdoor.size();
            network.superparticles[spi].backdoor.resize(idx+1,UI_MAX);
        }
        else if(network.superparticles[spi].backdoor[idx]<UI_MAX)
        {
            WARNING("superparticle #" F_UI " already contains index #" F_UI "",spi,idx);
            return UI_MAX;
        }
        network.spid[i]=spi;
        network.superparticles[spi].backdoor[idx]=i;
        DEBUG_2("particle #" F_UI " is ingested by superparticle #" F_UI "",i,spi);
        avars.reindex=true;
        return network.superparticles[spi].particles[i]=idx;
    }
}
References DEBUG_2, F_UI, UI_MAX, and WARNING.
sp_pid()
template<ui dim>
ui md< dim >::sp_pid (ui spi, ui idx) [inherited]
Reverse lookup of particle id in superparticle.
This function returns the id of the particle in slot idx of the superparticle with index spi. If the superparticle does not exist or it does not have a particle in the given slot, it returns UI_MAX.
Definition at line 169 of file sp.md.libmd.cc.
{
    if(spi>=network.superparticles.size())
    {
        WARNING("superparticle #" F_UI " does not exist",spi);
        return UI_MAX;
    }
    else if(idx>=network.superparticles[spi].backdoor.size())
    {
        WARNING("superparticle #" F_UI " does not contain index #" F_UI "",spi,idx);
        return UI_MAX;
    }
    else return network.superparticles[spi].backdoor[idx];
}
References F_UI, UI_MAX, and WARNING.
T()
template<ui dim>
ldf md< dim >::T [inherited]
Measure kinetic energy.
Returns the total kinetic energy of the system
Definition at line 53 of file energy.md.libmd.cc.
{
    ldf retval=0.0;
    for(ui i=0;i<N;i++) retval+=thread_T(i);
    return retval;
}
test_index()
template<ui dim>
bool md< dim >::test_index [inherited]
Test if we need to run the indexing algorithm.
This function determines if re-indexing is necessary, based on the position of each particle at the last time of indexing (xsk[]): If no particle has moved by more than $(ssz-rco)/2$, then there is no pair of particles that were more than network.ssz apart, but now less than network.rco apart, so re-indexing is not necessary. Otherwise, re-indexing might be necessary and thus should be done.
Definition at line 37 of file index.md.libmd.cc.
{
    ldf rcomax=0.0;
    for(auto itype:network.library) rcomax=std::max(rcomax,itype.rco);
    const ldf delta=std::pow(network.ssz-rcomax,2)/4.0;
    for(ui i=0;i<N;i++)
    {
        ldf test=0.0;
        for(ui d=0;d<dim;d++) test+=std::pow(dap(d,particles[i].xsk[d]-particles[i].x[d]),2);
        if(test>delta) return true;
    }
    return false;
}
References pow().
thread_calc_ext_forces()
template<ui dim>
void md< dim >::thread_calc_ext_forces (ui i) [inherited]
Calculate the forces for particle i>j with atomics.
This function calculates the forces induced by external forces acting on particle i
Definition at line 40 of file forces.md.libmd.cc.
{
    for(auto ftype: network.forces[i]) f(network.forcelibrary[ftype].externalforce,i,network.forcelibrary[ftype].particles[i],network.forcelibrary[ftype].parameters,(md<dim>*)this);
}
thread_calc_geometry()
template<ui dim>
void mpmd< dim >::thread_calc_geometry (ui i)
Calculate Monge patch derivatives for partice i.
This function update and calculates the new geometric information for a (new) particle position for particle i.
Definition at line 162 of file mpmd.libmd.cc.
{
    patch.calc(i,particles[i].x);
}
thread_calc_pot_forces()
template<ui dim>
void md< dim >::thread_calc_pot_forces (ui i) [inherited]
Calculate the forces for particle i>j with atomics.
This function calculates the forces induced by the potentials acting on particle i
Definition at line 14 of file forces.md.libmd.cc.
{
    for(auto sij: network.skins[i]) if(i>sij.neighbor)
    {
        const ldf rsq=distsq(i,sij.neighbor);
        if(!network.update or rsq<std::pow(get_rco(sij.interaction),2))
        {
            const ldf r=std::sqrt(rsq);
            DEBUG_3("r = " F_LDF,r);
            const ldf dVdr=v.dr(network.library[sij.interaction].potential,r,network.library[sij.interaction].parameters);
            DEBUG_3("dV/dr = " F_LDF,dVdr);
            for(ui d=0;d<dim;d++)
            {
                ldf F_i=dd(d,i,sij.neighbor)*dVdr/r;
                particles[i].F[d]+=F_i;
                DEBUG_3("particles[" F_UI "].F[" F_UI "] = " F_LDF,i,d,F_i);
                particles[sij.neighbor].F[d]-=F_i;
                DEBUG_3("particles[" F_UI "].F[" F_UI "] = " F_LDF,sij.neighbor,d,-F_i);
            }
        }
    }
}
References DEBUG_3, F_LDF, F_UI, pow(), and sqrt().
thread_cell()
template<ui dim>
void md< dim >::thread_cell (ui c) [inherited]
Cell indexer for cell c (thread)
This function finds the neighbors of all particles in cell c. It does this by considering (half of) all neighboring cells, such that no pairs of cells are processed twice.
Definition at line 183 of file index.md.libmd.cc.
{
    ui nNeighbors; // Number of neighbors of a cell
    int CellIndices[dim]; // Indices (0 to Q[d]) of cell
    ldf DissqToEdge[dim][3]; // Distance squared from particle to cell edges
    ui NeighboringCells[indexdata.celldata.totNeighbors]; // Cells to check (accounting for boundary conditions)
    ui NeighborIndex[indexdata.celldata.totNeighbors]; // Index (0 to totNeighbors) of neighboring cell
    ui d, i, j, k, p1, cellId;
    int ci;
    ldf dissqToCorner, sszsq = std::pow(network.ssz,2);
    // Determine cell indices
    k = c;
    for (d = dim-1; d < UI_MAX; d--)
    { DEBUG_3("indexdata.celldata.Q[" F_UI "]= " F_UI "", d, indexdata.celldata.Q[d]);
        CellIndices[d] = k % indexdata.celldata.Q[d];
        k /= indexdata.celldata.Q[d];
    }
    // Determine all neighbors
    nNeighbors = 0;
    for (k = 0; k < indexdata.celldata.totNeighbors; k++)
    { cellId = 0;
        for (d = 0; d < dim && (((ci = CellIndices[d]+indexdata.celldata.IndexDelta[k][d]) < (int)indexdata.celldata.Q[d] && ci >= 0)
                                || ((simbox.bcond[d] == BCOND::PERIODIC || simbox.bcond[d] == BCOND::BOXSHEAR) && indexdata.celldata.Q[d] != 2)); d++)
            cellId = indexdata.celldata.Q[d] * cellId + (indexdata.celldata.Q[d] + ci) % indexdata.celldata.Q[d];
        if (d == dim)
        { NeighboringCells[nNeighbors] = cellId;
            NeighborIndex[nNeighbors] = k;
            nNeighbors++;
        }
    }
    // Loop over all particles in this cell
    for (i = indexdata.celldata.Cells[c].size()-1; i < UI_MAX; i--)
    { p1 = indexdata.celldata.Cells[c][i];
        // Loop over all remaining particles in the same cell
        for (j = i-1; j < UI_MAX; j--)
            skinner(p1, indexdata.celldata.Cells[c][j], sszsq);
        if (simbox.useLshear || indexdata.celldata.OutsideBox[i])
        { // Loop over neighboring cells
            for (k = 0; k < nNeighbors; k++)
            { // Check all particles in cell
                for (ui p2 : indexdata.celldata.Cells[NeighboringCells[k]])
                    skinner(p1, p2, sszsq);
            }
        }
        else
        { for (d = 0; d < dim; d++)
            { DissqToEdge[d][1] = 0;
                if (indexdata.celldata.Q[d] == 2 && (simbox.bcond[d] == BCOND::PERIODIC || simbox.bcond[d] == BCOND::BOXSHEAR)) // Special case: two cells and pbc
                    DissqToEdge[d][0] = DissqToEdge[d][2] = std::pow(indexdata.celldata.CellSize[d]/2 - std::abs((CellIndices[d]+.5) * indexdata.celldata.CellSize[d] - simbox.L[d]/2 - particles[p1].x[d]), 2);
                else
                { DissqToEdge[d][0] = std::pow(simbox.L[d]/2 + particles[p1].x[d] - CellIndices[d] * indexdata.celldata.CellSize[d], 2);
                    DissqToEdge[d][2] = std::pow((CellIndices[d]+1) * indexdata.celldata.CellSize[d] - simbox.L[d]/2 - particles[p1].x[d], 2);
                }
            }
            // Loop over neighboring cells
            for (k = 0; k < nNeighbors; k++)
            {
                // Calculate distance (squared) to closest corner
                dissqToCorner = 0;
                for (d = 0; d < dim; d++)
                    dissqToCorner += DissqToEdge[d][indexdata.celldata.IndexDelta[NeighborIndex[k]][d]+1];
                // Ignore cell if it is more than sszsq away
                if (dissqToCorner < sszsq)
                    // Check all particles in cell
                    for (ui p2 : indexdata.celldata.Cells[NeighboringCells[k]])
                        skinner(p1, p2, sszsq);
            }
        }
    }
}
References abs(), BCOND::BOXSHEAR, DEBUG_3, F_UI, BCOND::PERIODIC, pow(), and UI_MAX.
thread_clear_forces()
template<ui dim>
void md< dim >::thread_clear_forces (ui i) [inherited]
Clear forces for particle i.
Clear the forces variable of particle i
Definition at line 6 of file forces.md.libmd.cc.
{
    memset(particles[i].F,0,dim*sizeof(ldf));
}
thread_first_order()
template<ui dim>
void md< dim >::thread_first_order (ui i) [inherited]
First order (Euler) integrator (threaded)
This function integrates particle position i using Euler first order.
 This is useful for implementing Vicsek type models
Definition at line 54 of file integrator.md.libmd.cc.
{
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) particles[i].x[d]+=integrator.h*particles[i].dx[d];
}
thread_H()
template<ui dim>
ldf md< dim >::thread_H (ui i) [inherited]
Measure Hamiltonian for particle i.
Returns the total energy (kinetic and potential) of particle i.
Definition at line 6 of file energy.md.libmd.cc.
{
    return T(i)+V(i);
}
thread_history()
template<ui dim>
void mpmd< dim >::thread_history (ui i)
Set the history of particle i.
This function generates the history $ x^{\mu}_p $ for particle i from its position and velocity.
Definition at line 141 of file mpmd.libmd.cc.
{
    for(ui d=0;d<dim;d++) particles[i].xp[d]=particles[i].x[d]-particles[i].dx[d]*integrator.h;
}
thread_index_stick()
template<ui dim>
void md< dim >::thread_index_stick (ui i) [inherited]
Save the particle position at indexing.
This function copies the current position x[] of particle i to xsk[], for use by md<dim>::test_index().
Definition at line 6 of file index.md.libmd.cc.
{
    memcpy(particles[i].xsk,particles[i].x,dim*sizeof(ldf));
}
thread_overdamped()
template<ui dim>
void md< dim >::thread_overdamped (ui i) [inherited]
First order (Euler) integrator for overdamped dynamics (threaded)
This function integrates particle position i using Euler first order.
 This is useful for implementing overdamped systems
Definition at line 64 of file integrator.md.libmd.cc.
{
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) particles[i].dx[d]=-particles[i].F[d]/avars.overdamped_gamma;
    for(ui d=0;d<dim;d++) particles[i].x[d]+=integrator.h*particles[i].dx[d];
}
thread_periodicity() [1/2]
template<ui dim>
void md< dim >::thread_periodicity (ldf x[dim]) [inherited]
Apply periodicity to one particle only.
This function loops through the dim dimensions, and updates the position and velocity of particle i to respect the boundary conditions of any boundary it might have passed through in the last time step.
Definition at line 16 of file periodicity.md.libmd.cc.
{
    for(ui d=0;d<dim;d++) boundary(d,x,this);
}
thread_periodicity() [2/2]
template<ui dim>
void md< dim >::thread_periodicity (ui i) [inherited]
Apply periodicity to one particle only.
This function loops through the dim dimensions, and updates the position and velocity of particle i to respect the boundary conditions of any boundary it might have passed through in the last time step.
Definition at line 6 of file periodicity.md.libmd.cc.
{
    for(ui d=0;d<dim;d++) boundary(d,i,this);
}
thread_seuler()
template<ui dim>
void md< dim >::thread_seuler (ui i) [inherited]
Symplectic euler integrator (threaded)
This function integrates particle i using symplectic Euler.
 The symplectic Euler integrator is simpelest (and fastest) symplectic integrator.
 The integrator is a first order integrator.
 Sometimes symplectic Euler is also refered: to as Semi-implicit Euler, Euler--Cromer or Newton-Stoermer-Verlet.
 Symplectic Euler takes the following form:
 \dot{x}^{\mu}_{t+1}=&\dot{x}^{\mu}_{t}+\tfrac{h}{m} F^{\mu}_{t}\\ x^{\mu}_{t+1}=& x^{\mu}_{t}+h\dot{x}^{\mu}_{t+1}
Definition at line 6 of file integrator.md.libmd.cc.
{
    ldf o=integrator.h/particles[i].m;
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++)
    {
        particles[i].dx[d]+=o*particles[i].F[d];
        particles[i].x[d]+=integrator.h*particles[i].dx[d];
    }
}
thread_T()
template<ui dim>
ldf mpmd< dim >::thread_T (ui i) [final], [override], [virtual]
Calculate kinetic energy of a particle.
This function calculates the kinetic energy of a particle i in the presence of curvature.
Reimplemented from md< dim >.
Definition at line 268 of file mpmd.libmd.cc.
{
    ldf retval=0.0;
    for(ui mu=0;mu<dim;mu++) for(ui nu=0;nu<dim;nu++) retval+=patch.g(i,mu,nu)*particles[i].dx[mu]*particles[i].dx[nu];
    return 0.5*particles[i].m*retval;
}
thread_V()
template<ui dim>
ldf mpmd< dim >::thread_V (ui i, bool higher_index_only = false) [final], [override], [virtual]
Calculate potential energy.
This function calculates the potential energy of a particle i in the presence of curvature.
Reimplemented from md< dim >.
Definition at line 278 of file mpmd.libmd.cc.
{
    ldf retval=0.0;
    ldf rcosq=std::pow(network.rco,2);
    for(auto sij: network.skins[i]) if(!higher_index_only or i<sij.neighbor)
    {
        const ldf rsq=embedded_distsq(i,sij.neighbor);
        if(rsq<rcosq)
        {
            const ldf r=std::sqrt(rsq);
            retval+=v(network.library[sij.interaction].potential,r,network.library[sij.interaction].parameters);
            if(network.update) retval-=network.library[sij.interaction].vco;
        }
    }
    return retval;
}
References pow(), and sqrt().
thread_vverlet_dx()
template<ui dim>
void md< dim >::thread_vverlet_dx (ui i) [inherited]
Velocity verlet integrator for velocity (threaded)
This function integrates particle velocity i using Velocity Verlet.
 See md<dim>::thread_vverlet_x for the particle position part.
 Velocity Verlet is a second order symplectic integrator.
 It is slower than symplectic Euler (see md<dim>::thread_seuler), yet more accurate.
 Velocity Verlet takes the following form:
x^{\mu}_{t+1}=&x^{\mu}_{t}+h\dot{x}^{\mu}_{t}+\tfrac{h^2}{2}F^{\mu}_{t}\\ \dot{x}^{\mu}_{t+1}=&\dot{x}^{\mu}_{t}+\tfrac{h}{2}(F^{\mu}_{t}+F^{\mu}_{t+1})
 Because of the second force ($F^{\mu}_{t+1}$) calculation this function is split in two.
Definition at line 40 of file integrator.md.libmd.cc.
{
    for(ui d=0;d<dim;d++) particles[i].dx[d]+=0.5*integrator.h*particles[i].F[d]/particles[i].m;
}
thread_vverlet_x()
template<ui dim>
void md< dim >::thread_vverlet_x (ui i) [inherited]
Velocity verlet integrator for position (threaded)
This function integrates particle position i using Velocity Verlet.
 See md<dim>::thread_vverlet_dx for the particle velocity part.
 Velocity Verlet is a second order symplectic integrator.
 It is slower than symplectic Euler (see md<dim>::thread_seuler), yet more accurate.
 Velocity Verlet takes the following form:
x^{\mu}_{t+1}=&x^{\mu}_{t}+h\dot{x}^{\mu}_{t}+\tfrac{h^2}{2}F^{\mu}_{t}\\ \dot{x}^{\mu}_{t+1}=&\dot{x}^{\mu}_{t}+\tfrac{h}{2}(F^{\mu}_{t}+F^{\mu}_{t+1})
 Because of the second force ($F^{\mu}_{t+1}$) calculation this function is split in two.
Definition at line 25 of file integrator.md.libmd.cc.
{
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) particles[i].x[d]+=integrator.h*particles[i].dx[d]+0.5*std::pow(integrator.h,2)*particles[i].F[d]/particles[i].m;
}
References pow().
thread_zuiden()
template<ui dim>
void mpmd< dim >::thread_zuiden (ui i)
The van Zuiden integrator for Riemannian manifolds (fails for pseudo-Riemannian manifolds)
This function runs the van Zuiden integrator with fixed point iterations and updates the position and velocity for particle i accordingly. This function unlike mpmd<dim>::thread_zuiden_protect(ui i) waits until the integrator has converged.
Definition at line 118 of file mpmd.libmd.cc.
{
    ldf ZC[dim],eps[dim],epsp[dim],val;
    zuiden_C(i,ZC);
    memcpy(eps,ZC,dim*sizeof(ldf));
    do
    {
        val=0.0;
        memcpy(epsp,eps,dim*sizeof(ldf));
        zuiden_A(i,eps);
        for(ui d=0;d<dim;d++) eps[d]+=ZC[d];
        for(ui d=0;d<dim;d++) val+=std::abs(epsp[d]-eps[d]);
    }
    while(val>std::numeric_limits<ldf>::epsilon());
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) particles[i].x[d]+=eps[d];
    for(ui d=0;d<dim;d++) particles[i].dx[d]=eps[d]/integrator.h;
}
References abs().
thread_zuiden_protect()
template<ui dim>
void mpmd< dim >::thread_zuiden_protect (ui i)
The van Zuiden integrator with protected fixed point itterations (makes sure you don't get stuck in a loop)
This function runs the van Zuiden integrator with fixed point iterations and updates the position and velocity for particle i accordingly. Should the integrator not converge after integrator.generations iterations this function stops with the fixed point iterations.
Definition at line 92 of file mpmd.libmd.cc.
{
    ui counter=0;
    ldf ZC[dim],eps[dim],epsp[dim],val;
    zuiden_C(i,ZC);
    memcpy(eps,ZC,dim*sizeof(ldf));
    do
    {
        val=0.0;
        counter++;
        memcpy(epsp,eps,dim*sizeof(ldf));
        zuiden_A(i,eps);
        for(ui d=0;d<dim;d++) eps[d]+=ZC[d];
        for(ui d=0;d<dim;d++) val+=std::abs(epsp[d]-eps[d]);
        DEBUG_3("fixed point iterators cycle: " F_UI "",counter);
    }
    while(counter<integrator.generations and val>std::numeric_limits<ldf>::epsilon());
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) particles[i].x[d]+=eps[d];
    for(ui d=0;d<dim;d++) particles[i].dx[d]=eps[d]/integrator.h;
}
References abs(), DEBUG_3, and F_UI.
thread_zuiden_wfi()
template<ui dim>
void mpmd< dim >::thread_zuiden_wfi (ui i)
The van Zuiden integrator without fixed point itterations.
This function runs the van Zuiden integrator without fixed point iterations and updates the position and velocity for particle i accordingly.
Definition at line 80 of file mpmd.libmd.cc.
{
    ldf eps[dim]={};
    zuiden_C(i,eps);
    memcpy(particles[i].xp,particles[i].x,dim*sizeof(ldf));
    for(ui d=0;d<dim;d++) particles[i].x[d]+=eps[d];
    for(ui d=0;d<dim;d++) particles[i].dx[d]=eps[d]/integrator.h;
}
timestep()
template<ui dim>
void md< dim >::timestep [inherited]
Do one timestep.
This function defines a timestep by combining the md<dim>::calc_forces and md<dim>::integrate functions.
 If there is a boxshear present it updates the boundaries.
Definition at line 106 of file integrator.md.libmd.cc.
{
    if(simbox.useLshear)
    {
        DEBUG_2("updating boxshear boundaries");
        update_boundaries();
    }
    calc_forces();
    integrate();
    run_hooks();
}
References DEBUG_2.
timesteps()
template<ui dim>
void md< dim >::timesteps (ui k) [inherited]
Do multiple timesteps.
This function calls md<dim>::timestep k times.
 (The looped is sandwiched between DEBUG_TIMER statements.)
Definition at line 122 of file integrator.md.libmd.cc.
{
    DEBUG_TIMER("start timesteps");
    for(ui i=0;i<k;i++) timestep();
    DEBUG_TIMER("stop timesteps");
}
References DEBUG_TIMER.
translate_particle()
template<ui dim>
void md< dim >::translate_particle (ui i, ldf x[dim]) [inherited]
Translate (or move) a particle.
This function translates particle i by the vector x[].
Definition at line 173 of file particles.md.libmd.cc.
{
    DEBUG_2("translating particle #" F_UI "",i);
    avars.export_force_calc=true;
    for(ui d=0;d<dim;d++)
    {
        particles[i].x[d]+=x[d];
        particles[i].xp[d]+=x[d];
    }
    thread_periodicity(i);
    avars.reindex=true;
}
References DEBUG_2, and F_UI.
translate_sp()
template<ui dim>
void md< dim >::translate_sp (ui spi, ldf x[dim]) [inherited]
Translate (or move) a super particle.
This function translates all particles belonging to the superparticle with index spi by the vector x[].
Definition at line 223 of file sp.md.libmd.cc.
{
    DEBUG_2("translating superparticle #" F_UI "",spi);
    for(auto it=network.superparticles[spi].particles.begin();it!=network.superparticles[spi].particles.end();it++) translate_particle(it->first,x);
}
References DEBUG_2, and F_UI.
unassign_all_forcetype()
template<ui dim>
void md< dim >::unassign_all_forcetype (ui ftype) [inherited]
Unassign force type to all particles.
This function removes the forcetype network.forcelibrary[ftype] from all particles.
Definition at line 625 of file interaction.md.libmd.cc.
{
    for(ui i=0;i<N;i++) unassign_forcetype(i,ftype);
}
unassign_forcetype()
template<ui dim>
bool md< dim >::unassign_forcetype (ui i, ui ftype) [inherited]
Unassign force type to particle.
This function removes the forcetype network.forcelibrary[ftype] from particle i. It returns whether the given forcetype was assigned to the given particle.
Definition at line 610 of file interaction.md.libmd.cc.
{
    for(ui j=network.forces[i].size()-1;j<UI_MAX;j--) if(network.forces[i][j]==ftype)
    {
        network.forces[i][j]=network.forces[i].back();
        network.forces[i].pop_back();
        return true;
    }
    return false;
}
References UI_MAX.
unset_damping()
template<ui dim>
bool md< dim >::unset_damping [inherited]
Disables damping.
This function disables damping and returns whether it was set.
Definition at line 25 of file setget.md.libmd.cc.
{
    if(avars.noftypedamping<UI_MAX)
    {
        DEBUG_2("disabling damping");
        rem_forcetype(avars.noftypedamping);
        avars.noftypedamping=UI_MAX;
        return true;
    }
    else
    {
        WARNING("no damping set");
        return false;
    }
}
References DEBUG_2, UI_MAX, and WARNING.
unset_langevin()
template<ui dim>
bool md< dim >::unset_langevin [inherited]
Disable Langevin thermostat.
This function disables Langevin thermostat and returns whether it was set.
Definition at line 66 of file setget.md.libmd.cc.
{
    if(avars.noftypelangevin<UI_MAX)
    {
        DEBUG_2("disabling Langevin thermostat");
        rem_forcetype(avars.noftypelangevin);
        rem_forcetype(avars.noftypedamping);
        avars.noftypelangevin=UI_MAX;
        avars.noftypedamping=UI_MAX;
        return true;
    }
    else
    {
        WARNING("no Langevin thermostat set");
        return false;
    }
}
References DEBUG_2, UI_MAX, and WARNING.
unset_overdamped()
template<ui dim>
bool md< dim >::unset_overdamped [inherited]
Disable overdamped dynamics.
This function restors the old integrator iff set_overdamped is used
Definition at line 103 of file setget.md.libmd.cc.
{
    if(avars.overdamped_pre_integrator!=INTEGRATOR::FO_OVERDAMPED)
    {
        integrator.method=avars.overdamped_pre_integrator;
        return true;
    }
    else
    {
        WARNING("unset_overdamped cannot unset overdamped dynamics as no other dynamics was previously defined");
        return false;
    }
}
References INTEGRATOR::FO_OVERDAMPED, and WARNING.
update_boundaries()
template<ui dim>
void md< dim >::update_boundaries [inherited]
Shifts the periodic boxes appropriately for sheared BC.
Update the box matrix using the shear velocities. Increments the box matrix $L_{ij}$ (stored in simbox.Lshear) by $h\times v_{ij}$ where $v_{ij}$ is the shear velocity matrix (stored in simbox.vshear) and $h$ is the integration timestep (stored in integrator.h).
 Also shifts $L_{ij}$ to ensure that it remains within the bounds $-L_{ii}/2 \leq L_{ij} \leq L_{ii}/2$.
Definition at line 43 of file periodicity.md.libmd.cc.
{
    // update box matrix for shear
    for(ui j=0;j<dim;j++) for (ui k=0; k<dim; k++)
    {
        simbox.Lshear[j][k] += simbox.vshear[j][k]*integrator.h;
        // shift by appropriate box lengths so that the off-diagonal entries are in the range -L[j][j]/2 to L[j][j]/2 consistent with the positions
        if (j != k && (simbox.bcond[j]==BCOND::PERIODIC || simbox.bcond[j]==BCOND::BOXSHEAR))
        {
            while(simbox.Lshear[j][k]>simbox.Lshear[j][j]/2.) simbox.Lshear[j][k]-=simbox.Lshear[j][j];
            while(simbox.Lshear[j][k]<-simbox.Lshear[j][j]/2.) simbox.Lshear[j][k]+=simbox.Lshear[j][j];
        }
    }
    simbox.invert_box();
}
References BCOND::BOXSHEAR, and BCOND::PERIODIC.
update_skins()
template<ui dim>
void md< dim >::update_skins (ui p1, ui p2) [inherited]
Modify skins after adding/modifying/removing bond.
Updates the skin lists of p1 and p2. This function is called by functions that modify pairwise interactions between specific particle pairs, to rebuild the skins taking into account new particle ID assignments and interaction definitions.
Definition at line 6 of file bonds.md.libmd.cc.
{
    ui interaction, s, t, j, k;
    std::pair<ui,ui> id;
    if ((s = network.spid[p1]) < UI_MAX && s == network.spid[p2]
        && network.sptypes[t = network.superparticles[s].sptype].splookup.count(id = network.hash(network.superparticles[s].particles[p1], network.superparticles[s].particles[p2])))
        interaction = network.sptypes[t].splookup[id];
    else if (network.lookup.count(id = network.hash(particles[p1].type, particles[p2].type)))
        interaction = network.lookup[id];
    else
        interaction = UI_MAX;
    for (j = network.skins[p1].size()-1; j < UI_MAX && network.skins[p1][j].neighbor != p2; j--);
    if (j < UI_MAX)
    {
        for (k = network.skins[p2].size()-1; network.skins[p2][k].neighbor != p1; k--);
        if (interaction < UI_MAX)
            network.skins[p1][j].interaction = network.skins[p2][k].interaction = interaction;
        else
        { std::iter_swap(network.skins[p1].begin()+j, network.skins[p1].rbegin());
            network.skins[p1].pop_back();
            std::iter_swap(network.skins[p2].begin()+k, network.skins[p2].rbegin());
            network.skins[p2].pop_back();
        }
    }
    else if (interaction < UI_MAX)
    { network.skins[p1].push_back(interactionneighbor(p2,interaction));
        network.skins[p2].push_back(interactionneighbor(p1,interaction));
    }
}
References UI_MAX.
V()
template<ui dim>
ldf md< dim >::V [inherited]
Measure potential energy.
Returns the total potential energy of the system
Definition at line 63 of file energy.md.libmd.cc.
{
    ldf retval=0.0;
    for(ui i=0;i<N;i++) retval+=thread_V(i,true);
    return retval;
}
zuiden_A()
template<ui dim>
void mpmd< dim >::zuiden_A (ui i, ldf eps[dim])
Calculates $g^{\rho \sigma} A_{\sigma \mu \nu} \epsilon^{\mu} \epsilon^{\nu}$ for particle i of the van Zuiden integrator.
This function calculates $g^{\rho \sigma} A_{\sigma \mu \nu} \epsilon^{\mu} \epsilon^{\nu}$ for particle i of the van Zuiden integrator for particle i. It overwrites ldf eps[dim] after it is read as input.
Definition at line 69 of file mpmd.libmd.cc.
{
    ldf ZA[dim]={};
    for(ui rho=0;rho<dim;rho++) for(ui sigma=0;sigma<dim;sigma++) for(ui mu=0;mu<dim;mu++) for(ui nu=0;nu<dim;nu++) ZA[rho]+=patch.ginv(i,rho,sigma)*patch.A(i,sigma,mu,nu)*eps[mu]*eps[nu];
    memcpy(eps,ZA,dim*sizeof(ldf));
}
zuiden_C()
template<ui dim>
void mpmd< dim >::zuiden_C (ui i, ldf ZC[dim])
Calculates $g^{\rho \sigma} C_{\sigma}$ for particle i of the van Zuiden integrator.
This function calculates $g^{\rho \sigma} C_{\sigma} = g^{\rho \sigma} (g^p_{\sigma \mu}(x^{\mu}-x^{\mu}_p)+h^2 \frac{F^{\sigma}}{m}) $ for particle i of the van Zuiden integrator for particle i. It overwrites ldf ZC[dim] after it is read as input.
Definition at line 56 of file mpmd.libmd.cc.
{
    ldf C[dim]={};
    memset(ZC,0,dim*sizeof(ldf));
    for(ui sigma=0;sigma<dim;sigma++) for(ui mu=0;mu<dim;mu++) C[sigma]+=patch.gp(i,sigma,mu)*(particles[i].x[mu]-particles[i].xp[mu]);
    for(ui sigma=0;sigma<dim;sigma++) C[sigma]+=std::pow(integrator.h,2)*particles[i].F[sigma]/particles[i].m;
    for(ui rho=0;rho<dim;rho++) for(ui sigma=0;sigma<dim;sigma++) ZC[rho]+=patch.ginv(i,rho,sigma)*C[sigma];
}
References pow().
Member Data Documentation
avars
template<ui dim>
additional_vars<dim> md< dim >::avars [inherited]
Bunch of additonal variables.
Definition at line 388 of file libmd.h.
boundary
template<ui dim>
bcond<dim> md< dim >::boundary [inherited]
Boundary conditions functor.
Definition at line 379 of file libmd.h.
f
template<ui dim>
externalforces<dim> md< dim >::f [inherited]
External forces functor.
Definition at line 384 of file libmd.h.
hooks
template<ui dim>
hooker<dim> md< dim >::hooks [inherited]
Hook functor.
Definition at line 385 of file libmd.h.
indexdata
template<ui dim>
indexer<dim> md< dim >::indexdata [inherited]
Data structure for indexing.
Definition at line 382 of file libmd.h.
integrator
template<ui dim>
integrators md< dim >::integrator [inherited]
Integration method.
Definition at line 386 of file libmd.h.
N
template<ui dim>
ui md< dim >::N [inherited]
Number of particles.
Definition at line 377 of file libmd.h.
network
template<ui dim>
interact md< dim >::network [inherited]
Interaction network.
Definition at line 381 of file libmd.h.
particles
template<ui dim>
std::vector<particle<dim> > md< dim >::particles [inherited]
Particle array.
Definition at line 380 of file libmd.h.
patch
template<ui dim>
mp<dim> mpmd< dim >::patch
Geometric monge patch information.
Definition at line 619 of file libmd.h.
simbox
template<ui dim>
box<dim> md< dim >::simbox [inherited]
Simulation box.
Definition at line 378 of file libmd.h.
v
template<ui dim>
pairpotentials md< dim >::v [inherited]
Pair potential functor.
Definition at line 383 of file libmd.h.
vvars
template<ui dim>
variadic_vars<dim> md< dim >::vvars [inherited]
Bunch of variables for variadic functions.
Definition at line 387 of file libmd.h.
The documentation for this struct was generated from the following files:
libmd.h
libmd-src/mpmd.libmd.cc